### ISSUE TITLE
Logo FatturaElettronica

### ISSUE THREAD

**Issue by andreatosato** [FatturaElettronica/FatturaElettronica.NET#101]
Ciao a tutti, 
come proposto da @nicolaiarocci, FatturaElettronica è alla ricerca di un logo.
Inserite le proposte in questo thread e votate con un like quello che vi piace di più

**Comment by jacktric** [comment]
Sarebbe bello quello di Giulio Cesare sostituendo le lettere Ae con Fe, magari con lo stesso format delle prime due proposte.

**Comment by andreatosato** [comment]
![](https://pbs.twimg.com/media/Dtedi2MWsAAX9UK.jpg)

Nuova versione
Autore: Giulio Cesare

**Comment by jacktric** [comment]
> ![](https://camo.githubusercontent.com/02021b7321897829228509e762e99cf62b5862eb/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f4474656469324d577341415839554b2e6a7067)
> 
> Nuova versione
> Autore: Giulio Cesare

Ma perché quel 3 davanti? Vuole essere un cuore? :-D 
Comunque non male, attendiamo altre opinioni.

**Comment by gs-marco** [comment]
Anche avrei suggerito il logo di Giulio Cesare con Fe al poste di Ae (ma senza il 3 davanti!!)

**Comment by andreatosato** [comment]
![51044161-be2c7700-15c0-11e9-85a3-87dd50f2c71d](https://user-images.githubusercontent.com/24985956/51044619-cfc24e80-15c1-11e9-9bc4-9537048e64bf.png)

**Comment by nicolaiarocci** [comment]
ho aggiornato commento sopra per fa sì che si veda. Mi piace che suggerisca la transizione (o co-esistenza?) di analogico (a sx) e digitale (a dx - punch card!).

**Comment by kalamun** [comment]
La mia icona è in SVG, si può cambiare il colore semplicemente modificando l'esadecimale nel codice :-)

**Comment by nicolaiarocci** [comment]
sì @kalamun ma il colore preferirei glielo mettessi tu che sei l'artista. Se poi mi dai un png ancora meglio (quello che vedi qua sopra l'ho creato io dal tuo svg)

**Comment by nicolaiarocci** [comment]
ho messo su un arancione copiato dalla vecchia colorazione PA. Non mi fa impazzire, ma per ora ce lo facciamo bastare. 

@kalamun ho messo attribuzione in README e changelog; sentiti libero di ritoccarla liberamente, e di aggistare li logo come preferisci :-)
