### ISSUE TITLE
Controllo Unità di Misura

### ISSUE THREAD

**Issue by Loredano88** [FatturaElettronica/FatturaElettronica.NET#102]
https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/a3e459e6a7216b61e708dda76b036972fe783479/Validators/DettaglioLineeValidator.cs#L24

Ciao! Ho notato che questa condizione va a limitare il controllo nel caso in cui il tag esiste ma è vuoto. In questo caso, secondo questa validazione, la fattura è valida. Andando invece a controllare la stessa sul sito https://sdi.fatturapa.gov.it viene generato un errore:
![image](https://user-images.githubusercontent.com/3784865/49433335-11393000-f7b2-11e8-893b-9b65a395f699.png)

Togliendo la condizione imposta alla riga 24, il problema si risolve e il controllo genera l'errore quando il tag è presente ed è vuoto, mentre valida la fattura se il tag non c'è o è inserito correttamente.

**Comment by neoDD69** [comment]
Scusate, giusto per contribuire.

Ho fatto controllare un XML generato prima di questa modfiica da https://sdi.fatturapa.gov.it/SdI2FatturaPAWeb/ControllaFatturaAction.do e mi ha detto che è ok, come mi diceva il validatore della 1.0.1.

Mentre ora il validatore non mi valida una fattura con righe che non abbiano UnitaMisura == "".

Secondo me il messaggio di errore postato da @Loredano88  forse significava che:
Non puoi mettere nello XML un elemento "UnitaMisura" e NON VALORIZZARLO, se il valore è "" l'elemento non deve essere inserito nell'XML, come faceva la versione 1.0.1

Anche perché il documento di AgEntrate riporta l'elemento UnitaMisura sotto DettaglioLinee come elemento NON OBBLIGATORIO.
Mentre ore il validatore lo rende obbligatorio.

**Comment by nicolaiarocci** [comment]
@neoDD69 sono d'accordo con te. Avrei dovuto controolare sul convalidatore PA.
