### ISSUE TITLE
Problema ScontoMaggiorazione in DatiGeneraliDocumento

### ISSUE THREAD

**Issue by carmas123** [FatturaElettronica/FatturaElettronica.NET#104]
Salve a tutti, durante l'implementazione della generazione del file XML mi sono ritrovato a dover gestire dei documenti con sconti sul totale e di conseguenza a doverlo gestire nella compilazione del file stesso.
Il problema nasce quando nella verifica dal file e mi spiego meglio:
Lo sconto di piede "dovrebbe" essere specificato nell'header al Tag DatiGeneraliDocumento e tale sconto almeno per quanto riportato nella guida 

> (Controllo corretto calcolo del PrezzoTotale
>  codice errore 00423: 2.2.1.11 <PrezzoTotale> non calcolato secondo le regole definite nelle specifiche tecniche)

 dovrebbe essere poi applicato al tag PrezzoTotale su ogni riga (senza doverlo riportare nuovamente riga per riga), quindi ad esempio se ho uno sconto di piede del 10% dovrebbe essere applicato solo al tag PrezzoTotale e non riportato in DettaglioLinee. Ad esempio avendo in oggetto un dettaglio del genere (preso dai vostri esempi):

`
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>LA DESCRIZIONE DELLA FORNITURA PUO' SUPERARE I CENTO CARATTERI CHE RAPPRESENTAVANO IL PRECEDENTE LIMITE DIMENSIONALE. TALE LIMITE NELLA NUOVA VERSIONE E' STATO PORTATO A MILLE CARATTERI</Descrizione>
        <Quantita>5.00</Quantita>
        <PrezzoUnitario>1.00</PrezzoUnitario>
        <PrezzoTotale>5.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
`

applicando lo sconto del 10% si "dovrebbe" avere un dettaglio come questo:

`
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>LA DESCRIZIONE DELLA FORNITURA PUO' SUPERARE I CENTO CARATTERI CHE RAPPRESENTAVANO IL PRECEDENTE LIMITE DIMENSIONALE. TALE LIMITE NELLA NUOVA VERSIONE E' STATO PORTATO A MILLE CARATTERI</Descrizione>
        <Quantita>5.00</Quantita>
        <PrezzoUnitario>1.00</PrezzoUnitario>
        <PrezzoTotale>4.50</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
`

cosa che comporta l'errore 00423, ma allora perché nella guida che espressamente indicata una verifica "sbagliata":

![image](https://user-images.githubusercontent.com/6574219/49498309-ea8b0000-f86a-11e8-949d-e82257b91c3b.png)

Come si può notare il controllo "dovrebbe" essere effettuato tenendo presente lo "ScontoTot", oppure per "ScontoTot" non si intende lo sconto inserito nel blocco DatiGeneraliDocumento, ma smplicemente tutti gli sconti di riga?
Anche se fosse così, allora che senso ha dover aggiungere in tastata lo Sconto se poi bisogna riapplicarlo su tutte le righe?

Se qualcuno sa qualcosa in più di me in merito fatemelo sapere, grazie.

**Comment by davidthegray** [comment]
Mi sono trovato davanti allo stesso problema. Ho visto come ha risolto TeamSystem: tagliando la testa al toro, lo sconto di piede viene trasferito esclusivamente riga per riga, e non viene messo in testata. Ho fatto la stessa cosa.

**Comment by carmas123** [comment]
Fatto anche io così, il discorso è che non capisco che senso ho avere uno sconto di testata se poi non serve a nulla.
Quello che si dovrebbe analizzare è se questo sconto in realtà identifica lo sconto complessivo applicato all'intero documento. Quindi ad esempio se sulle righe ho scontato un totale del 20% allora lo sconto di testata andrebbe valorizzato con il 20%. Ma ne dubito visto che in testata vengono comunque gestiti gli sconti in cascata.

**Comment by biapar** [comment]
Stesso problema com gli omaggi. Abbiamo preferito portare a 0 le righe omaggio senza imbarcarsi nello sconto 100%

**Comment by carmas123** [comment]
Mentre per le righe ad omaggio imponibile come avete risolto?

**Comment by biapar** [comment]
Questo ancora non l'abbiamo considerato dato che non avviene quasi mai nell'azienda per cui sto facendo il convertitore XML FE.
