### ISSUE TITLE
problema installazione via nuget

### ISSUE THREAD

**Issue by mrsavvy** [FatturaElettronica/FatturaElettronica.NET#106]
Ciao a tutti,

ho un progetto windows forms  con VisualStudio 2013 (versione 12.0.31101 update 4) ho provato a installare via UI e "console gestione pacchetti" il pacchetto "fatturaelettronica" ma mi viene mostrato il seguente messaggio di errore.  
Purtroppo sono un pò arruginito con microsoft.net (ma devo aggiornare un softwarino non mio) e volevo studiare la vostra soluzione, se la domanda è troppo banale vi chiederei un riferimento dove studiare la soluzione. 

Grazie a tutti
  
Installazione non riuscita. Ripristino dello stato precedente in corso...
Impossibile installare il pacchetto 'FatturaElettronica 1.0.1'. Si sta tentando di eseguire l'installazione in un progetto destinato a '.NETFramework,Version=v4.6.1', ma il pacchetto non contiene riferimenti ad assembly o file di dati compatibili con il framework. Per ulteriori informazioni, contattare l'autore del pacchetto.

**Comment by nicolaiarocci** [comment]
Ciao, il tuo progetto che versione del .NET Framework supporta? Non ricordo, ma credo che per default VS2013 crei progetti NET45 e non NET461
