### ISSUE TITLE
Errore caricamento xml in caso di dati non validi

### ISSUE THREAD

**Issue by dimdar74** [FatturaElettronica/FatturaElettronica.NET#112]
Ciao a tutti,

In alcuni casi il caricamento di un file xml genera errore prima di poterne eseguire la convalida. 
Suggerisco di modificare nella BaseClassSerializable la funzione

`public virtual void ReadXml(XmlReader r)`

sostituendo l'istruzione

`
property.SetValue(this, r.ReadElementContentAs(type, null), null);
`
che nel mio caso andava in errore cercando di convertire la stringa vuota del PesoNetto in un decimal 
con le seguenti

```
object elementContent = r.ReadElementContentAsObject();
try
{                    
    property.SetValue(this, Convert.ChangeType(elementContent, type), null);
}
catch
{
    throw new Exception($"Invalid property '{property.Name}' type '{type.Name}' value '{elementContent.ToString()}'");
}
```
così da ritornare un eccezione con i dettagli del nome della proprietà, del tipo e del valore.

Saluti

[EDIT]
Forse avrei dovuto postare nel progetto FatturaElettronica.Core, scusate.

**Comment by nicolaiarocci** [comment]
Giusto per chiarire, si trattava di errore formale nel XML, giusto? Essendo definito numerico numerico, PesoNetto non poteva essere una stringa vuota.

**Comment by dimdar74** [comment]
Si, esatto, il gestionale ha generato il file in modo errato. Ho modificato il codice come descritto giusto per non avere un eccezione in fase di caricamento del file xml perché l'elenco degli errori di validazione viene poi restituito al gestionale che lo visualizza all'utente ma, in questo caso, il file era scartato come xml invalido e quindi senza indicarne il motivo preciso all'utente.

**Comment by nicolaiarocci** [comment]
ok chiudo il ticket per ora in quanto non rilevante con questo repository. Eventualmente proponi una pull request sul Core e la valuteremo.
