### ISSUE TITLE
NumeroLinea obbligatorio

### ISSUE THREAD

**Issue by jacktric** [FatturaElettronica/FatturaElettronica.NET#113]
Salve a tutti,
il processo di validazione non mi obbliga a settare un valore esplicito per NumeroLinea nel blocco DettaglioLinee. NumeroLinea viene settato = 0 su ogni linea.
Testando l'import di xml su piattaforma Aruba il documento viene bloccato perchè NumeroLinea non può essere = 0.
Avete avuto modo di riscontrare lo stesso comportamento su altre piattaforme?

**Comment by nicolaiarocci** [comment]
Visto che il sito di test di fatturaPA li accetta, direi che si tratta di un problema di Aruba.
