### ISSUE TITLE
Quantità negativa

### ISSUE THREAD

**Issue by brux88** [FatturaElettronica/FatturaElettronica.NET#115]
ciao, se provo a generare un xml con il campo quantita in negativo me lo valida ma se lo vado a controllare nel sito dell'agenzia dell'entrate mi torna questo errore:

File non conforme al formato (nella descrizione del messaggio Ã¨ riportata lâ¬"indicazione puntuale della non conformitÃ ) - The value '-7.00' of element 'Quantita' is not valid. riga: 134 - colonna: 35 | Verificare che il file inviato sia conforme al formato previsto | 00200
-- | -- | --

**Comment by nicolaiarocci** [comment]
Ciao @brux88 grazie per la segnalazione. Puoi verificare cosa succede se metti zero nella quantità, la accetta? Avevo testato a suo tempo, ma non ricordo (e sono pigro).

**Comment by carmas123** [comment]
Il tag per la quantità se è 0 dovrebbe essere omesso
