### ISSUE TITLE
Errori di diciture

### ISSUE THREAD

**Issue by fverponziani** [FatturaElettronica/FatturaElettronica.NET#116]
Ciao,
ti lascio solo alcuni errori che ho notato nel codice di diciture errate.
Nella classe LatinValidators.cs alla riga 13 c'è scritto contentente anziché contenente.
Nella classe RegimeFiscale.cs alla riga 13 c'è scritto Agricoultura anziché Agricoltura.
Grazie mille per il tuo lavoro

**Comment by nicolaiarocci** [comment]
Grazie a te.
