### ISSUE TITLE
Content is not allowed in prolog.

### ISSUE THREAD

**Issue by foga92** [FatturaElettronica/FatturaElettronica.NET#117]
Buonasera, 

Provando ad inviare il file per la fattura FPR al SDI ritorna con errore 
0200 Content is not allowed in prolog.
Provando a cercare un po su internet sembrerebbe essere un problem di formalità xml. 
Dopo averlo controllato confermo che di problemi non cene sono lo stesso strumento di verifica fattura sul sito dell'agenzia delle entrate non rileva problemi. 
La fattura verso la PA non da problemi quella tra privati invece da questo errore formale. 
Possibile che ci sia qualche carattere strano nella generazione del file?

Grazie
Mirko

**Comment by nicolaiarocci** [comment]
Il fatto che la fattura PA non dia problemi mi fa pensare non sia un problema di serializzazione: è la stessa sia per privati che PA. Che sia un problema lato Ag. Entrate?

**Comment by foga92** [comment]
Non disattivi l'UTF8 ma il BOM che sono una serie di byte che viene aggiunta all'inizio del file e di conseguenza da problemi di validazione. 
La cosa diventa problematica perchè ti accorgi solo nel momento dell'invio allo SDI oppure se provi a fare una validazione specifica del formato xml tramite dei tools, il sito dell'agenzia non rileva nessun problema. 
Almeno se qualcun'altro ha lo stesso problema trova la soluzione velocemente 👍

**Comment by nicolaiarocci** [comment]
Cosa è esattamente `nodoPrincipale`?

**Comment by foga92** [comment]
`var nodoPrincipale = Fattura.CreateInstance(tipoFatturaElettronica == TipoFatturaElettronica.Privati ? FatturaElettronica.Defaults.Instance.Privati : FatturaElettronica.Defaults.Instance.PubblicaAmministrazione);
                `

**Comment by nicolaiarocci** [comment]
👍

**Comment by nicolaiarocci** [comment]
Se vuoi fare una pull request con aggiornamento del README, ti meriti l'attribuzione :-)
