### ISSUE TITLE
Multi-target .NET Standard 1.1 e 2.0

### ISSUE THREAD

**Issue by fdipuma** [FatturaElettronica/FatturaElettronica.NET#119]
Vorrei proporre di aggiungere, come target framework della libreria, .NET Standard 2.0. Ciò ci consentirebbe di ridurre notevolmente il numero di dipendenze (Netstandard.Library in primis) scaricate quando utilizzata in progetti che compilano nativamente .NET Standard 2.0+.

La stessa cosa è ormai fortemente consigliata come best practice da MS (vedi https://docs.microsoft.com/it-it/dotnet/standard/net-standard#which-net-standard-version-to-target ).

L'impatto dovrebbe essere minimo, ci sarebbe giusto modificare l'attributo `<TargetFramework>` in `<TargetFrameworks>` ed aggiungere `netstandard2.0`, e poco altro. Chiaramente la stessa cosa è da fare nei progetti correlati (es. FatturaElettronica.Core).

Se serve posso mettere su una pull-request.

**Comment by nicolaiarocci** [comment]
Non ci vedo particolari problemi, anzi.

**Comment by fdipuma** [comment]
Ok, allora procedo.

**Comment by fdipuma** [comment]
Sembra tutto ok, attendo il merge di https://github.com/FatturaElettronica/FatturaElettronica.Core/pull/14 (e il rilascio del nuovo pacchetto nuget) prima di aggiungere la PR qui.
