### ISSUE TITLE
Errore di validazione "'' non può essere vuoto". 

### ISSUE THREAD

**Issue by Caloyski** [FatturaElettronica/FatturaElettronica.NET#121]
Quando non viene inserita una causale, non passa la validazione, ma l' errore è il seguente:

**'' non può essere vuoto**

invece di visualizzare il nome della proprietà, sta visualizzando il valore.

**Comment by VitalieH** [comment]
Buongiorno, Causale di cosa? "CausaleTrasporto" ? "CausalePagamento".

**Comment by Caloyski** [comment]
Proprietà List<string> Causale dentro l' oggetto DatiGeneraliDocumento

**Comment by nicolaiarocci** [comment]
Ciao, a occhio quella è la descrizione del errore (`ErrorMessage`), per sapere qualche è la proprietà coinvolta devi usare `PropertyName`. Puoi verificare?

**Comment by Caloyski** [comment]
Sì, la proprietà coinvolta si può visualizzare tramite PropertyName, ma vedere un messaggio del tipo **'' non può essere vuoto** non mi sembra naturale.
Spero di non essere stato frainteso, non ho aperto questa Issue perchè rappresenta un problema a sviluppare la mia applicazione, bensì solamente per provare ad aiutare :D

**Comment by nicolaiarocci** [comment]
è la risposta di default della regola `NotEmpty()` di FluentValidation. Per ora la terrei così anche se è customizzabible, perchè altrimenti dobbiamo cambiarle ovunque la applicahiamo (e sono praticamente tutti i campi obbligatori).

**Comment by nicolaiarocci** [comment]
PS: grazie per il suggerimento :-)
