### ISSUE TITLE
Errore non individuato PECDestinatario non può essere vuota

### ISSUE THREAD

**Issue by gianlucacambareri** [FatturaElettronica/FatturaElettronica.NET#123]
Ciao volevo segnalarti il seguente possibile errore:
la validazione non rileva l'errore in caso inserimento del tag PECDestinatario vuoto, mentre il tool online dell'Agenzia restituisce il messaggio che il tag non può essere vuoto:
Esempio:
`     ....`
   `       <CodiceDestinatario>0000000</CodiceDestinatario>` 
     ` <PECDestinatario />`
  `  </DatiTrasmissione>`
mentre per lo stesso file, omettendo il tag PECDestinatario, non viene segnalato nessun errore (sempre dal tool online dell'AdE).

Da specifiche tecniche il campo PECDestinatario è obbligatorio solo se la fattura è destinata ad un soggetto privato e tale soggetto intende ricevere le fatture elettroniche attraverso il canale PEC. 
Non so se questo è un caso 'anomalo' visto che che non conoscendo il codice destinatario è stato indicato 0000000 (a me il file arriva già così).

**Comment by V1tal1e** [comment]
Questo lo confermo anche io, ho segnalato il problema telefonicamente ad PA. Mi hanno detto che si, la pec puo in quanto a loro non è necessario avere la pec per inviare la fattura alle imprese.... (per lo meno cosi ho capito dalla signorina al telefono).

Cordiali saluti.
Vitalie.

**Comment by nicolaiarocci** [comment]
Ciao, su che versione di Fattura Elettronica hai fatto il test?

**Comment by ilMes** [comment]
Devi lasciarno Null (Nothing in VB), così non esporta `<PECDestinatario />`

ff.FatturaElettronicaHeader.DatiTrasmissione.PECDestinatario = Nothing ' Io programmo in VB

oppure, non lo valorizzi (probabilmente tu lo valorizzi con una stringa vuota)

Ettore
