### ISSUE TITLE
XMLOptions DecimalFormat

### ISSUE THREAD

**Issue by matteobiss** [FatturaElettronica/FatturaElettronica.NET#125]
Ciao,
non so se sia un bug o una configurazione errata, Volevo segnalare che nel costruttore della classe "BaseClassSerializable" viene inizializzato XmlOptions con DecimalFormat = "0.00###"
A mio avviso bisognerebbe impostarlo per default  "0.00######" in quanto se ho prezzi unitari con più di 5 decimali questi vengono arrotondati e quindi in questi casi il file non passa i controlli sui totali.

**Comment by nicolaiarocci** [comment]
ah, la gara sui decimali su ma aspettavo prima o poi, non ci si prende mai 😄

**Comment by mastroxc** [comment]
buongiorno,
ho postato una pull request sul Core a riguardo per permettere fino a 19 decimali (da specifica il campo puo essere lungo fino a 21 caratteri) #https://github.com/FatturaElettronica/FatturaElettronica.Core/pull/15
