### ISSUE TITLE
Validazione provincia

### ISSUE THREAD

**Issue by gminutillo** [FatturaElettronica/FatturaElettronica.NET#129]
un mio cliente ha ricevuto, senza che il servizio di interscambio la bloccasse, una fattura con il valore **FO** nel campo **Ufficio** dell'**Iscrizione REA**. (se non ricordo male 'FO' era la sigla della provincia di Forlì prima che diventasse 'FC' (Forlì-Cesena)

Il validatore della libreria segnala il valore come errato, mentre in realtà non dovrebbe. Sono andato a riguardare lo schema ed effettivamente a validazione del tipo **ProvinciaType** controlla solo che il valore sia composto da due lettere maiuscole:

```
<xs:simpleType name="ProvinciaType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2}" />
    </xs:restriction>
  </xs:simpleType>
```
non so se è il caso di modificare il Validator del campo provincia , oppure aggiungere le 'vecchie' province nella tabella.

**Comment by nicolaiarocci** [comment]
Ricordi bene, FO era la vecchia provincia di Forlì prima che diventasse FC. 

Premesso che oggigiorno nessuno dovrebbe fatturare per la provincia FO visto che non esiste, alla luce dei controlli "ufficiali", probabilmente ha senso semplificare il controllo come suggerisci.
