### ISSUE TITLE
Validazione sconti

### ISSUE THREAD

**Issue by gminutillo** [FatturaElettronica/FatturaElettronica.NET#136]
ciao,
non so se capitano tutte a me, ma sembra che ci sia un altra incongruenza tra il validatore della libreria e i controlli dell'SDI. 

Ho ricevuto una fattura con righe come questa:

```
<DettaglioLinee>
	<NumeroLinea>7</NumeroLinea>
	<TipoCessionePrestazione>SC</TipoCessionePrestazione>
	<CodiceArticolo>
		<CodiceTipo>COD</CodiceTipo>
		<CodiceValore>011441</CodiceValore>
	</CodiceArticolo>
	<Descrizione>PENNE RIGATE 30X500G SM ITA</Descrizione>
	<Quantita>60.000</Quantita>
	<UnitaMisura>PZ</UnitaMisura>
	<PrezzoUnitario>0.00</PrezzoUnitario>
	<ScontoMaggiorazione>
		<Tipo>SC</Tipo>
		<Percentuale>0.00</Percentuale>
	</ScontoMaggiorazione>
	<PrezzoTotale>0.00</PrezzoTotale>
	<AliquotaIVA>0.00</AliquotaIVA>
	<Natura>N1</Natura>
</DettaglioLinee>

```
**In pratica il SDI fa passare senza problemi righe dettaglio con sconto in percentuale a zero**

**Comment by nicolaiarocci** [comment]
Potresti per cortesia verificare se è vero anche il contrario, ovvero se accetta `ScontoMaggiornazione.Importo` a 0 quando `Percentuale` non viene usato?

**Comment by gminutillo** [comment]
si, accetta anche l'importo.
Ho modificato il file così:

```
<DettaglioLinee>
	<NumeroLinea>7</NumeroLinea>
	<TipoCessionePrestazione>SC</TipoCessionePrestazione>
	<CodiceArticolo>
		  <CodiceTipo>COD</CodiceTipo>
		  <CodiceValore>011441</CodiceValore>
	</CodiceArticolo>
	<Descrizione>PENNE RIGATE 30X500G SM ITA</Descrizione>
	<Quantita>60.000</Quantita>
	<UnitaMisura>PZ</UnitaMisura>
	<PrezzoUnitario>0.00</PrezzoUnitario>
	<ScontoMaggiorazione>
		  <Tipo>SC</Tipo>
		  <Importo>0.00</Importo>
	</ScontoMaggiorazione>
	<PrezzoTotale>0.00</PrezzoTotale>
	<AliquotaIVA>0.00</AliquotaIVA>
	<Natura>N1</Natura>
</DettaglioLinee>
```
e il risultato è comunque **file corretto**

**Comment by gminutillo** [comment]
ho installato la 1.1.2 ma continuo a ricevere gli stessi errori.

ti allego il file con l'errore così puoi effettuare dei test.
[test-sconti.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/2779735/test-sconti.zip)

**Comment by nicolaiarocci** [comment]
Ora dovrebbe essere a posto, grazie.

**Comment by gminutillo** [comment]
si, la 1.1.3 funziona correttamente.
grazie a te :-)
