### ISSUE TITLE
Fattura semplificata td07/td08

### ISSUE THREAD

**Issue by brux88** [FatturaElettronica/FatturaElettronica.NET#137]
ciao, ricevo alcune fatture semplificate con codice td07, ma quando eseguo il comando var fattura = Fattura.CreateInstance(Instance.Privati);
 perde il tag FatturaElettronicaBody nonostante se vedo xml invece c'è.
ho allegato l'esempio del file xml che sto provando ad importare.
[IT00990690885_00B33.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/2779263/IT00990690885_00B33.zip)

**Comment by nicolaiarocci** [comment]
Attualmente non c'è supporto per le semplificate e francamente dubito di avere il tempo di implementarlo.

**Comment by brux88** [comment]
mentre i tag sono sempre gli stessi , non capisco perche non dovrebbe prendersi solo il tag del body

**Comment by nicolaiarocci** [comment]
Lavori in corso. Vedi #156.

**Comment by nicolaiarocci** [comment]
Vedi #163
