### ISSUE TITLE
Using the project on .NET Core on Mac

### ISSUE THREAD

**Issue by samuelpath** [FatturaElettronica/FatturaElettronica.NET#138]
Hi, 

Have you ever tried installing the project on a different OS than Windows, and using .NET Core instead of .NET standard?

I'm trying to launch it on .NET Core with MacOS.

First of all, when I launch `dotnet add package FatturaElettronica`, I have the following error:

```
error: Cycle detected.
error:   FatturaElettronica -> FatturaElettronica.
```

It looks like the issue is caused by the fact that a project and a dependency cannot have the same name.

So I renamed the PackageId from `FatturaElettronica` to `FatturaElettronicaUnique`.

Then, the add package works.

But when I run `dotnet run`, I have hundreds of errors like:

```
Validators/DatiDocumentoValidator.cs(12,18): error CS0121: L'appel est ambigu entre les méthodes ou propriétés suivantes : 'FatturaElettronica.Validators.MyValidatorExtensions.BasicLatinValidator<T, TElement>(FluentValidation.IRuleBuilder<T, TElement>)' et 'FatturaElettronica.Validators.MyValidatorExtensions.BasicLatinValidator<T, TElement>(FluentValidation.IRuleBuilder<T, TElement>)' [/Users/samuelpath/Documents/Esker/Tools/FatturaElettronica.NET/FatturaElettronica.csproj]
```

Meaning: "the call is ambiguous between the following methods and properties…"

And: 

```
Tabelle/Divisa.cs(76,25): warning CS0436: Le type 'Divisa' dans '/Users/samuelpath/Documents/Esker/Tools/FatturaElettronica.NET/Tabelle/Divisa.cs' est en conflit avec le type importé 'Divisa' dans 'FatturaElettronica, Version=1.1.2.0, Culture=neutral, PublicKeyToken=null'. Utilisation du type défini dans '/Users/samuelpath/Documents/Esker/Tools/FatturaElettronica.NET/Tabelle/Divisa.cs'. [/Users/samuelpath/Documents/Esker/Tools/FatturaElettronica.NET/FatturaElettronica.csproj]
```

Meaning: "The type 'Divisa' in Divisa.cs is in conflict with the imported type 'Divisa' in FatturaElettronica.

Do you have any idea how I can run the project locally?

I'm working for an Italian Business trying to send invoices through the SDI portal, and I need to troubleshoot some issues, and I'd like to be able to either run in debug mode or add some logs.

Thanks.

**Comment by nicolaiarocci** [comment]
I develop this project on a Mac, with VSCode, on a NetCore test project as you can see from sources.

**Comment by samuelpath** [comment]
Sorry, I'm a newbie with .NET Core, I usually work with JavaScript.

How can I run the Demo code in the Readme and use the dependencies?

Do you create a separate project to run the demo code? If so, how do you reference the FatturaElettronica dependencies in your demo csproj, so that it doesn't try to look them up on nuget?

Or do you run the demo code directly in the main project folder? If so, what command do you use to run it?

**Comment by nicolaiarocci** [comment]
try:

`dotnet add -h`

will show you that you can either add a package from nuget, or you can do this:

`dotnet add project <PROJECT_PATH>`

**Comment by samuelpath** [comment]
Thanks @nicolaiarocci I am now able to run your demo test using the FatturaElettronica Nuget dependency.

If you've got a few minutes, could you quickly explain how to run the main project in Debug mode? The demo code allows me to get the error message, but sometimes I need to know exactly how we get to the error message.

For instance, with error 00422, I know that it is launched by the method DatiRiepilogoValidateAgainstError00422 where when we have a mismatch between the sum of ImponibileImporto and the sum of PrezzoTotale. However, since I have a huge invoice with thousands of lines, I'm not sure if I've either extracted too many (PrezzoTotale > ImponibileImporto) or too few lines (PrezzoTotale > ImponibileImporto). Running in Debug mode would allow me to see exactly what sums you compare for instance.

**Comment by biapar** [comment]
I suggest to use Visual Studio for Mac.
