### ISSUE TITLE
specifiche tecniche ufficiali.

### ISSUE THREAD

**Issue by etzellava** [FatturaElettronica/FatturaElettronica.NET#139]
Penso che che il link delle specifiche tecniche ufficiali  debba essere questo.

https://www.agenziaentrate.gov.it/wps/content/Nsilib/Nsi/Schede/Comunicazioni/Fatture+e+corrispettivi/Fatture+e+corrispettivi+ST/ST+invio+di+fatturazione+elettronica/?page=ivacomimp

in quanto nel link attuale il riferimento alla versione è la 1.2.1 mentre l'ufficiale  è alla versione 1.3
cambia poco , ma cambia.

**Comment by nicolaiarocci** [comment]
ciao, ti riferisci al link nel README vero?

**Comment by etzellava** [comment]
si certo 
"Lettura e scrittura nel formato XML conforme alle specifiche tecniche ufficiali."

**Comment by nicolaiarocci** [comment]
grazie
