### ISSUE TITLE
Codifica dei caratteri Non ASCII nel  codice articolo (forse funziona anche nelle descrizioni, da testare)

### ISSUE THREAD

**Issue by ilMes** [FatturaElettronica/FatturaElettronica.NET#140]
Come forse già sai, non si possono mettere caratteri non ASCII nel campo del codice articolo (esempio il carattere di euro € ma non solo). Ho scoperto che la soluzione è la conversione con la sintassi HTML.
Vedi questa discussione:  https://forum.italia.it/t/simbolo-in-codice-articolo/7276
Da verificare con test.
Ettore

**Comment by nicolaiarocci** [comment]
Non mi sembra una soluzione valida, come si evince anche dal seguito della discussione. No comment sull'uso di CDATA. Per ora chiudo.
