### ISSUE TITLE
Creazione Righe FatturaElettronicaBody

### ISSUE THREAD

**Issue by next100years** [FatturaElettronica/FatturaElettronica.NET#141]
Scusate domanda forse banale,
devo creare l'xml fatturaPA tag <FatturaElettronicaHeader> è ok
il tag <FatturaElettronicaBody> non riesco ad inserirlo con questo codice mi dice che l'indice non esiste

                fattura.FatturaElettronicaBody[0].DatiGenerali.DatiGeneraliDocumento.TipoDocumento = "TD01";
                fattura.FatturaElettronicaBody[0].DatiGenerali.DatiGeneraliDocumento.Divisa = "EUR";
                fattura.FatturaElettronicaBody[0].DatiGenerali.DatiGeneraliDocumento.Numero = "123";
                fattura.FatturaElettronicaBody[0].DatiGenerali.DatiGeneraliDocumento.Causale = causale;

mi fornite un esempio?
grazie

**Comment by nicolaiarocci** [comment]
Se la fattura è nuova (appena instanziata) devi prima aggiungere gli elementi `FatturaElettronicaBody` all'array, che è necessariamente vuoto. Qualcosa del genere:

```cs
            var newItem = new FatturaElettronica.FatturaElettronicaBody.FatturaElettronicaBody();
            // puoi impostare le proprietà di newItem ora, oppure in seguito dopo averlo aggiunto al
            // corpo della fattura, come fai nel tuo snippet qui sopra.
            // newItem.DatiGenerali.DatiGeneraliDocumento.Numero = "1";
            fattura.FatturaElettronicaBody.Add(newItem);
```

Dopodichè puoi usare l'elemento 0 dell'array, che ora esiste.
