### ISSUE TITLE
Validazione tag: Attachment

### ISSUE THREAD

**Issue by gminutillo** [FatturaElettronica/FatturaElettronica.NET#142]
Eccomi di nuovo.
Ti segnalo un'altra differenza tra la validazione della libreria e quella del Servizio di Interscambio.

Mi è arrivata una fattura con il l'elemento Allegati compilato così:
```
<Allegati>
	<NomeAttachment>9999999999</NomeAttachment>
	<FormatoAttachment>PDF</FormatoAttachment>
	<DescrizioneAttachment>FATTURA PER LA FORNITURA DI ENERGIA ELETTRICA</DescrizioneAttachment>
	<Attachment></Attachment>
</Allegati>
```
La validazione con la libreria mi riporta l'errore:  **'Attachment' non può essere vuoto** ma evidentemente il tag Attachment può essere vuoto... mah.

**Comment by gminutillo** [comment]
si probabilmente è così.
come il restante 99% dei controlli, il valore del tag viene semplicemente validato con la regola dello schema:

`<xs:element name="Attachment" type="xs:base64Binary"/>`

che evidentemente accetta anche valori vuoti.
Poi vai a capire perché i 'geni' dell'Enel hanno indicato anche il formato e poi non hanno messo l'allegato...

**Comment by nicolaiarocci** [comment]
Qui sono restio ad intervenire: mi sembra corretto controllare che l'allegato ci sia, come da specifiche. 

Domanda: come mai nel tuo workflow convalidi le fatture in ingresso, che evidentemente sono state già convalidate da Sdi?

**Comment by Tudor44** [comment]
> si probabilmente è così.
> come il restante 99% dei controlli, il valore del tag viene semplicemente validato con la regola dello schema:
> 
> `<xs:element name="Attachment" type="xs:base64Binary"/>`
> 
> che evidentemente accetta anche valori vuoti.
> Poi vai a capire perché i 'geni' dell'Enel hanno indicato anche il formato e poi non hanno messo l'allegato...

Già capitata una cosa del genere a me. Purtroppo l'xml te lo valida correttamente sia lo sdi, sia il sito dell'ADE che controlla la fattura.

**Comment by gminutillo** [comment]
> Domanda: come mai nel tuo workflow convalidi le fatture in ingresso, che evidentemente sono state già convalidate da Sdi?
infatti, me lo stavo chiedendo anch'io... la tolgo immediatamente così la smetto :-)

**Comment by nicolaiarocci** [comment]
ok, per ora chiudo. Se diventa un problema, siamo sempre in tempo a ritornarci sopra.
