### ISSUE TITLE
Validazione identificativo fiscale IVA

### ISSUE THREAD

**Issue by emanuele-fasano** [FatturaElettronica/FatturaElettronica.NET#143]
[Chiuso per test effettuati direttamente su  SDI]

**Comment by nicolaiarocci** [comment]
Ciao, "diverse fonti" mi pare un po' generico. Se riceviamo conferme ufficiali o perlomeno indiziarie, ci ragioniamo 😄 

@sgardini ne sai qualcosa?

**Comment by emanuele-fasano** [comment]
Cercando la stringa "fatturazione elettronica 9999999" su google escono decine e decine di fonti diverse che ne parlano (credo che da qualche parte abbiano letto questo valore).
In ogni caso appena trovo una comunicazione ufficiale invio il link.
