### ISSUE TITLE
ScontoMaggiorazione puo' accettare sia Importo che Percentuale

### ISSUE THREAD

**Issue by gianlucacambareri** [FatturaElettronica/FatturaElettronica.NET#146]
Ho notato che nella versione 1.1.3 è presente un esplicito fix che verifica se per il tag **ScontoMaggiorazione** sono compilati contemporaneamente i campi **Importo** e **Percentuale**, segnalando come error questa situazione.
Ora da specifiche i campi possono essere compilati entrambi, solo che diciamo è sconsigliato visto che l'agenzia per il calcolo darà priorità al campo **Importo** (rendendo superflua la presenza del campo Percentuale).
Si può convertire questo controllo in Warning? (Validators.ScontoMaggiorazioneValidator):

` RuleFor(x => x.Tipo)
                .Must((challenge, _) => challenge.Importo == null || challenge.Percentuale == null)
                .WithMessage("Percentuale e Importo sono entrambi presenti, si suggerisce di indicare esclusivamente Importo")
                .WithErrorCode("00200")
                .WithSeverity(Severity.Warning);`

**Comment by nicolaiarocci** [comment]
Ciao, mi domando se non sia meglio rimuovere quella convalida del tutto lasciando solo il 437. In fin dei conti, come giustamente segnali, non è un errore formali se entrambi i campi sono compilati. Opinioni?

**Comment by gianlucacambareri** [comment]
A mio avviso tecnicamente sì, sarebbe più corretto rimuovere il controllo.

Visto che c'era stato un Fix apposito, pensavo che avessi avuto la necessità d'inserire questo controllo magari a seguito di qualche segnalazione o per necessità pratiche (da qui l'idea del Warning).
