### ISSUE TITLE
Cliente Fuori CEE

### ISSUE THREAD

**Issue by brux88** [FatturaElettronica/FatturaElettronica.NET#147]
alcuni miei clienti devono emettere delle fatture per dei clienti in arabia saudita, ma il dizionario delle nazioni  non prevede la sigla dello stato e comunque leggendo ho visto che basta mettere OO in nazione e 99999999999 nella partita iva, ma nemmeno OO è inserito nel dizionario, come posso fare

di seguito il link che ho letto:
[https://www.guidafisco.it/esterometro-cos-e-come-funziona-obbligo-scadenza-fatture-estero-quando-2158](url)

**Comment by nicolaiarocci** [comment]
Mi sembra un caso come quello della Provincia (vedi #129): in realtà dovremmo forse limitarci a controllare che IdPaese sia di 2 caratteri maiuscoli.

```
  <xs:simpleType name="NazioneType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2}" />
    </xs:restriction>
  </xs:simpleType>
```

**Comment by gminutillo** [comment]
mmm... non sono d'accordo.
Il codice nazione 'OO' non è ammesso (lo era per lo spesometro).

Ho appena provato a validare una fattura con **OO** e **99999999999** e mi viene scartata mentre con **US** e **99999999999** viene accettata.

Ne deduco che del IDPaese viene controllato non solo la sua correttezza formale, ma anche la sua esistenza.

**Comment by gminutillo** [comment]
il codice nazione dell'Arabia Saudita è **SA**, la fattura con **SA** e **99999999999** viene accettata senza errori.

**Comment by tid3840** [comment]
Salve, mi sembra di avere riscontrato un'ulteriore problematica sul Paese...in questo caso la Grecia non è GR ma EL.

Potreste per favore verificare?

Grazie

Alessandro Facchini

**Comment by gminutillo** [comment]
> Salve, mi sembra di avere riscontrato un'ulteriore problematica sul Paese...in questo caso la Grecia non è GR ma EL.

ci sono già passato :(
**GR** è quello giusto, EL non è ammesso

**Comment by tid3840** [comment]
> > Salve, mi sembra di avere riscontrato un'ulteriore problematica sul Paese...in questo caso la Grecia non è GR ma EL.
> 
> ci sono già passato :(
> **GR** è quello giusto, EL non è ammesso

@gminutillo  Salve ha per caso un link di riferimento?  Grazie per l'informazione:)

**Comment by gminutillo** [comment]
nella documentazione della fattura elettronica è specificato che nel campo IDPaese va compilato con

> Codice della nazione espresso secondo lo standard ISO 3166-1 alpha-2 code

L'elenco dei codici validi lo trovi qui:
https://it.wikipedia.org/wiki/ISO_3166-1

Per lo spesometro (adesso si chiama Esterometro) invece si deve usare **EL** ma solo per l'elemento IDPaese contenuto nell'elemento IDFiscale

**Comment by gminutillo** [comment]
> Che però non riporta ovviamente questo fantomatico OO

il codice **OO** è stato 'inventato' appositamente per lo Spesometro

**Comment by tid3840** [comment]
> nella documentazione della fattura elettronica è specificato che nel campo IDPaese va compilato con
> 
> > Codice della nazione espresso secondo lo standard ISO 3166-1 alpha-2 code
> 
> L'elenco dei codici validi lo trovi qui:
> https://it.wikipedia.org/wiki/ISO_3166-1
> 
> Per lo spesometro (adesso si chiama Esterometro) invece si deve usare **EL** ma solo per l'elemento IDPaese contenuto nell'elemento IDFiscale

@gminutillo Grazie...scusa non non ho capito la differenza: io sto cercando di validare una fattura estera (codice destinatario xxxxxxx) di un cliente greco: mettendo EL nel campo FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici.IdFiscaleIVA.IdPaese  non viene validato in quanto EL non è presente nella tabella paesi.
Dove sbaglio?

Grazie

alessandro Facchini

**Comment by gminutillo** [comment]
> mettendo EL nel campo FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici.IdFiscaleIVA.IdPaese non viene validato in quanto EL non è presente nella tabella paesi.
> Dove sbaglio?

**EL** non è un codice nazione valido, devi metterci **GR**

**Comment by tid3840** [comment]
> > mettendo EL nel campo FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici.IdFiscaleIVA.IdPaese non viene validato in quanto EL non è presente nella tabella paesi.
> > Dove sbaglio?
> 
> **EL** non è un codice nazione valido, devi metterci **GR**
@gminutillo GRAZIE ma..mettendo xxxxxxx nel codice destinatario sto facendo una fattura per l'esterometro o l'esterometro è un'altra cosa?
grazie

alessandro facchini

**Comment by gminutillo** [comment]
L'esterometro è un'altra cosa. 

Mi spiego meglio, le fatture emesse verso clienti esteri:

- possono essere comunicate come fatture elettroniche (al pari delle fatture emesse a clienti italiani). 
In questo caso per i clienti greci devi impostare IDPaese = GR
- oppure possono essere comunicate come Esterometro cioè inviando un file xml che le contiene tutte le fatture emesse a clienti esteri in un mese.
In questo caso, oltre a dover creare un file completamente diverso, per i clienti greci devi il campo IDPaese = EL

se ti sembra assurdo è perché lo è :-)

**Comment by tid3840** [comment]
> L'esterometro è un'altra cosa.
> 
> Mi spiego meglio, le fatture emesse verso clienti esteri:
> 
> * possono essere comunicate come fatture elettroniche (al pari delle fatture emesse a clienti italiani).
>   In questo caso per i clienti greci devi impostare IDPaese = GR
> * oppure possono essere comunicate come Esterometro cioè inviando un file xml che le contiene tutte le fatture emesse a clienti esteri in un mese.
>   In questo caso, oltre a dover creare un file completamente diverso, per i clienti greci devi il campo IDPaese = EL
> 
> se ti sembra assurdo è perché lo è :-)

@gminutillo  Grazie mille per le preziose spiegazioni. Alessandro Facchini

**Comment by tid3840** [comment]
> > L'esterometro è un'altra cosa.
> > Mi spiego meglio, le fatture emesse verso clienti esteri:
> > 
> > * possono essere comunicate come fatture elettroniche (al pari delle fatture emesse a clienti italiani).
> >   In questo caso per i clienti greci devi impostare IDPaese = GR
> > * oppure possono essere comunicate come Esterometro cioè inviando un file xml che le contiene tutte le fatture emesse a clienti esteri in un mese.
> >   In questo caso, oltre a dover creare un file completamente diverso, per i clienti greci devi il campo IDPaese = EL
> > 
> > se ti sembra assurdo è perché lo è :-)
> 
> @gminutillo Grazie mille per le preziose spiegazioni. Alessandro Facchini

Ho comunque visto che validando una fattura con EL il link preposto per il controllo lo valida (https://sdi.fatturapa.gov.it/SdI2FatturaPAWeb/ControllaFatturaAction.do)..se metto un codice inesistente invece dà errore. Quindi a livello agenzia il controllo viene fatto e sembrerebbe comprendere anche EL.

Al limite potreste valutare di  aggiungerlo in un prossimo aggiornamento

Grazie

alessandro Facchini

**Comment by nicolaiarocci** [comment]
Chiudo per ora.

**Comment by tid3840** [comment]
> Chiudo per ora.

ok, rimane il fatto che a mio avviso occorrerebbe aggiungere EL nell'elenco stati validi dato che l'agenzia entrate l'accetta e la libreria no

Grazie per l'attenzione

Alessandro Facchini
