### ISSUE TITLE
Cliente "Nazioni Unite" - ONU

### ISSUE THREAD

**Issue by MarcoGiorgi** [FatturaElettronica/FatturaElettronica.NET#148]
L'organizzazione delle Nazioni Unite non ha una giurisdizione ed e' un ente extraterritoriale, senza partita iva, codice fiscale, ed esente da fatturazione, IVA, ecc...

Ho chiesto all'AdE come fare ad emettere fattura e mi hanno risposto come segue:
Gentile utente,
Il codice XXXXXXX   va utilizzato solo da parte del fornitore italiano che emette fattura verso cliente estero;
in questo caso per il cliente estero va compilato il campo IdFiscaleIVA, valorizzando IdPaese con il codice del paese del cliente (standard ISO 3166-1 alpha 2 code) e IdCodice con un valore (min 1 max 28 caratteri alfanumerici)
che, normalmente, dovrebbe coincidere con l'identificativo fiscale attribuito al cliente dal suo paese di appartenenza; se non conosciuto possono mettere qualsiasi valore che rispetti le caratteristiche del campo.

Quindi non saprei cosa inserire nel codice paese. Potrei mettere IT e ignorare il tutto, ma non sarebbe corretto in quanto e' un'organizzazione extraterritoriale (quando entri nei loro uffici di Roma, di fatto non sei in Italia e non valgono le leggi italiane al loro interno)

Il codice OO non e' giustamente supportato in quanto usato solo per lo spesometro
Qualcuno sa come fare?

**Comment by gminutillo** [comment]
secondo me hai due possibilità:

- inserisci un codice nazione 'a caso'
- emetti la fattura solo in modo 'tradizionale' cartacea, pdf (o quello che hai usato fino a ieri), e poi comunichi la fattura con l'esterometro mettendo 'OO' nell'IDPaese

**Comment by MarcoGiorgi** [comment]
vado per la prima, in quanto non voglio avere due canali separati ma gestire tutto digitalmente per non impazzire (con questa fantastica libreria!)
Grazie!
