### ISSUE TITLE
ScontoMaggiorazioni: Tipo "SC" non accettato

### ISSUE THREAD

**Issue by lalenzos** [FatturaElettronica/FatturaElettronica.NET#149]
Purtroppo nella verifica mi viene segnalato sempre il seguente errore nel blocco ScontoMaggiorazioni: Tipo "SC" non valido.

Sia nella parte dei DatiGeneraliDocumento che nella parte DettaglioLinee non viene accettato il valore "SC". Ovviamente tutti gli altri campi come importo e percentuale hanno un valore giusto. Anche la verifica sul sito fatturapa.gov.it funziona con successo.

Non sono riuscito a trovare l'errore. Grazie.

**Comment by nicolaiarocci** [comment]
Ciao, 

1) che versione di FE.NET stai usando?
2) Hai inserito sia `Importo` che `Percentuale`?

**Comment by nicolaiarocci** [comment]
Se la risposta alla 2 è affermativa e stai usando la 1.1.3 allora la risposta potrebbe essere la #146. Versione breve: problema conosciuto, verrà fissato nella prossima release.

**Comment by lalenzos** [comment]
> Ciao,
> 
> 1. che versione di FE.NET stai usando?
> 2. Hai inserito sia `Importo` che `Percentuale`?

1. Versione 1.1.3
2. Sia Importo che Percentuale hanno un valore.

Grazie!

**Comment by nicolaiarocci** [comment]
Per ora puoi mettere solo Importo o Percentuale (se li metti entrambi Importo ha comunque la precedenza). Con la 1.1.4 il problema è comunque risolto (validazione allineata a quella ufficiale)
