### ISSUE TITLE
File Xml

### ISSUE THREAD

**Issue by amerlin** [FatturaElettronica/FatturaElettronica.NET#150]
Ciao, 
sto valutando la vostra libreria, ma ho qualche domanda. 
Per la generazione della fattura elettronica è necessario partire da un file xml estrapolato dal gestionale, corretto? Quali dovrebbero essere le specifiche di questo file ? Esiste qualche libreria .NET che consente di generare il file xml a partire dai dati "grezzi"? Grazie in anticipo.

**Comment by nicolaiarocci** [comment]
Ciao, Il README l'hai letto? Puoi creare una nuova istanza della classe, impostare le proprietà dell'oggetto, quindi serializzare su XML o JSON.
