### ISSUE TITLE
IdPaese "OO" non accettato

### ISSUE THREAD

**Issue by filippoangileri** [FatturaElettronica/FatturaElettronica.NET#152]
Come da oggetto non è accettato il valore "OO" nel campo IdPaese del IdFiscaleIVA del CessionarioCommittente.
Potete correggere questo errore?
Grazie.

**Comment by filippoangileri** [comment]
@nicolaiarocci grazie per il vostro lavoro, potete darmi una mano?

**Comment by nicolaiarocci** [comment]
Ciao, hai datto occhiata ai vecchi ticket, in particolare #148 e #147? Sembr che OO non sia suportato (e in effetti non compare nella tabella ISO)
