### ISSUE TITLE
Soluzione che si spacca aggiornando alla versione 1.1.x

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.NET#153]
Installando la versione 1.1 le soluzioni si spaccano. Il probme agenerato deve avere a che fare con la dll System.Net.Http, che panna nel webconfig da

   `<bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />`
 a 
   `<bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />`

e non compila più

Le referenze passano da

System.Diagnostics.Tracing -> D:\Lavoro\tecnositalia.visualstudio.com\tools.scooter.it\packages\System.Diagnostics.DiagnosticSource.4.5.1\lib\net46\System.Diagnostics.DiagnosticSource.dll
System.Reflection -> D:\Lavoro\tecnositalia.visualstudio.com\tools.scooter.it\packages\System.Reflection.4.3.0\lib\net462\System.Reflection.dll
System.Xml.ReaderWriter -> D:\Lavoro\tecnositalia.visualstudio.com\tools.scooter.it\packages\System.Xml.ReaderWriter.4.3.1\lib\net46\System.Xml.ReaderWriter.dll
System.Linq -> D:\Lavoro\tecnositalia.visualstudio.com\tools.scooter.it\packages\System.Linq.4.3.0\lib\net463\System.Linq.dll
System.Linq.Expressions -> D:\Lavoro\tecnositalia.visualstudio.com\tools.scooter.it\packages\System.Linq.Expressions.4.3.0\lib\net463\System.Linq.Expressions.dll
System.Text.RegularExpressions -> D:\Lavoro\tecnositalia.visualstudio.com\tools.scooter.it\packages\System.Text.RegularExpressions.4.3.0\lib\net463\System.Text.RegularExpressions.dll
System.Runtime.InteropServices.RuntimeInformation -> D:\Lavoro\tecnositalia.visualstudio.com\tools.scooter.it\packages\System.Runtime.InteropServices.RuntimeInformation.4.3.0\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll
System.Net.Http -> D:\Lavoro\tecnositalia.visualstudio.com\tools.scooter.it\packages\System.Net.Http.4.3.4\lib\net46\System.Net.Http.dll

a

System.Diagnostics.Tracing -> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.Tracing.dll 
System.Reflection -> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Reflection.dll     
System.Xml.ReaderWriter -> C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\System.Xml.dll
System.Linq -> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Linq.dll
System.Linq.Expressions -> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Linq.Expressions.dll
System.Text.RegularExpressions -> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Text.RegularExpressions.dll
System.Runtime.InteropServices.RuntimeInformation -> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net47\lib\System.Runtime.InteropServices.RuntimeInformation.dll
System.Net.Http -> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Http.dll     

ci sto sbattendo la testa da tutto il giorno senza venirne a capo,
qualche aiuto?

**Comment by nicolaiarocci** [comment]
Ciao, l'unica cosa che mi viene in mente è che proprio nella 1.1 abbiamo aggiunto NetStandard 2.0 come target framework (ma rimane anche 1.1).

**Comment by fdipuma** [comment]
Che versione di VS utilizzi? E qual è il target framework del progetto in cui stai avendo problemi? Da quello che vedo dal tuo post alcuni pacchetti sono ripristinati come .net47, mentre altri come .net461.

La cosa più probabile è che il tuo progetto (che ha come target una versione direttamente indirizzata su .net standard 2.0) abbia fatto casino con i binding redirects.

Prova a dare un'occhiata qui: https://github.com/dotnet/standard/issues/481
