### ISSUE TITLE
Conversione p7m --> xml

### ISSUE THREAD

**Issue by Redmaro84** [FatturaElettronica/FatturaElettronica.NET#155]
Salve, con questa libreria è possibile convertire da p7m ad xml, "ripulendolo" dei dati della firma?

**Comment by nicolaiarocci** [comment]
Hai dato occhiata a https://github.com/FatturaElettronica/FatturaElettronica.Extensions?

**Comment by Redmaro84** [comment]
Grazie,praticamente quello che mi serviva era già pronto
