### ISSUE TITLE
Validazione Peso netto e lordo

### ISSUE THREAD

**Issue by Artusoft** [FatturaElettronica/FatturaElettronica.NET#157]
Ciao, da specifiche il peso netto e il peso lordo nei dati di trasporto non può essere maggiore di 9999.99:

<xs:simpleType name="PesoType">
    <xs:restriction base="xs:decimal">
      <xs:pattern value="[0-9]{1,4}\.[0-9]{1,2}" />
    </xs:restriction>
  </xs:simpleType>

è il caso di aggiungere una rule in DatiTrasportoValidator?

**Comment by nicolaiarocci** [comment]
non sarebbe male in effetti.

**Comment by nicolaiarocci** [comment]
Ci sono in realtà anche altri valori decimali che hanno limiti (direi a occhio quasi tutti). Questo intanto è fatto.
