### ISSUE TITLE
Validazione Latin dell'unitá di misura

### ISSUE THREAD

**Issue by swampie** [FatturaElettronica/FatturaElettronica.NET#162]
Buongiorno,
in relazione alla issue #102 
stiamo utilizzando la libreria per effettuare la validazione delle fatture elettroniche e in alcuni casi nel campo Unitá Di Misura vengono utilizzate lettere accentate (es. "unitá") e il validator BasicLatin non consente l'inserimento. Sarebbe possibile disabilitare il validatore programmaticamente?

**Comment by nicolaiarocci** [comment]
vengono accettate da PA?

**Comment by swampie** [comment]
Ciao @nicolaiarocci 
Sí abbiamo diverse fatture del cliente con l'unitá di misura con accenti che sono giá state accettate dallo SDI

**Comment by nicolaiarocci** [comment]
Ho provato a controllare sul sito SDI una fattura con `UnitaMisuraPeso` = "unità" ma lo respinge. Ho anche ricontrollato le specifiche e in effetti dovrebbe essere BasicLatin, coerentemente con errore. Non so come possa essere passato da SDI un file fattura con lettera accentata. Per ora chiudo per impossibilità di riscontro.
