### ISSUE TITLE
Proprietà di tipo oggetto opzionali non devono restituire NullException quando nulle

### ISSUE THREAD

**Issue by dieric** [FatturaElettronica/FatturaElettronica.NET#165]
Ho seguito i passi indicati nel doc di esempio per validare il mio oggetto fattura prima di salvarlo su file.
Ma quando eseguo validator.validate(fattura) va in errore "Object reference not set to an instance of an object".
Ho verificato di avere le ultime versioni disponibili sia dei pacchetti.

Preciso che lavoro in vb.net ma non credo sia questo il problema.

Suggerimenti?

Grazie
Diego

**Comment by nicolaiarocci** [comment]
@liborpansky code amended, please let me know if this fixes the issue for you.

**Comment by liborpansky** [comment]
Works as expected, thank you!
