### ISSUE TITLE
Errore in Xamarin Forms (Net Standard 2.0)

### ISSUE THREAD

**Issue by AlexF12004Roma** [FatturaElettronica/FatturaElettronica.NET#173]
La libreria importata in un progetto Xamarin Forms 3.5 (NetStandard 2.0 class Library) non funziona.
Appare un punto esclamativo nel pacchetto Nuget senza dare ulteriori errori.
L'API non è utilizzabile nel codice.

**Comment by nicolaiarocci** [comment]
![image](https://user-images.githubusercontent.com/512968/54109676-95b5d300-43df-11e9-9206-079c611dae45.png)


Ciao, ho appena provato su VSMac e non sembra ci siano problemi.

**Comment by AlexF12004Roma** [comment]
Era un problema legato alla libreria Newtonsoft.
Nel Progetto era già presente la 12, la libreria richiede la 11.
Anche se 12>11 per qualche motivo VS2017 genera questo errore.
Ho allineato tutto alla 11 ed ora il pacchetto viene installato correttamente.
