### ISSUE TITLE
Add support to apps based to v1.5., please :D

### ISSUE THREAD

**Issue by AlexBream** [FatturaElettronica/FatturaElettronica.NET#174]
Please add somewhere a code like :)
```
namespace FatturaElettronica
{
    [Obsolete("Fattura is deprecated, please use FatturaOrdinaria instead.", false)]
    public class Fattura : FatturaOrdinaria
    {
    }
}
```

**Comment by nicolaiarocci** [comment]
Ciao Alessandro. 

Preferirei evitarlo, anche perchè non sarebbe che un rinvio. Immagino tu non possa ricompilare? La modifica richiesta è davvero minima in cambio di una superficie API più chiara e definita.

**Comment by AlexBream** [comment]
Nessun problema, era solo un suggerimento.
