### ISSUE TITLE
Il root node della fattura semplificata ha il nome sbagliato

### ISSUE THREAD

**Issue by gminutillo** [FatturaElettronica/FatturaElettronica.NET#176]
il nome dell'elemento root dell'xml della fattura semplificata deve essere **FatturaElettronicaSemplificata**  non **FatturaElettronica** 
anche il namespace sembra errato, nello schema viene indicato **http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0** mentre nel file xml prodotto dalla libreria c'è **http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2**

**Comment by gminutillo** [comment]
forse ti è sfuggito  perché ho modificato il messaggi precedente invece di aprire una nuova issue, ma anche il namespace sembra errato, nello schema della semplificata c'è  **http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0** mentre nel file xml prodotto dalla libreria c'è **http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2**

**Comment by nicolaiarocci** [comment]
ACK

**Comment by nicolaiarocci** [comment]
dovrebbe essere ok ora che ne pensi @gminutillo

**Comment by gminutillo** [comment]
si adesso dovrebbe essere ok. 👍
