### ISSUE TITLE
Classe Allegati

### ISSUE THREAD

**Issue by gminutillo** [FatturaElettronica/FatturaElettronica.NET#177]
La classe Allegati è definita in entrambi i namespaces **FatturaElettronica.Semplificata** e **FatturaElettronica.Ordinaria**.
visto che sono identiche sarebbe comodo spostarla in **FatturaElettronica.Common**

**Comment by nicolaiarocci** [comment]
Ci pensi tu?

**Comment by gminutillo** [comment]
fatto

**Comment by nicolaiarocci** [comment]
#179

**Comment by timer86** [comment]
Ciao,
scusate se mi aggiungo alla conversazione, sono un neofita mi sono appena addentrato anche io in questo mondo e sto
sto avendo difficoltà con la gestione della classe allegati.

FatturaElettronica.Common.Allegati

hai qualche documentazione o guida sul suo utilizzo?
onestamente vorrei esportare l'allegato all'interno di una fattura e so come fare il decoding di xbase64
ma onestamente non so gestirl con la classe allegati in modo da ottenere, la riga per poi fare il decondig.

Grazie in anticipo.
