### ISSUE TITLE
Installazione

### ISSUE THREAD

**Issue by dario75it** [FatturaElettronica/FatturaElettronica.NET#178]
Buongiorno, sto tentando di installare le librerie FatturaElettronica.Core e FatturaElettronica sul mio progetto ma riscontro i seguenti problemi.
Ho VS2017 e se installate su progetto con .NetFramework 4.0 non mi è possibile compilare a causa dell'errore seguente:

non è stato possibile risolvere il riferimento primario "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" perché ha una dipendenza indiretta dall'assembly "System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"....

Ho allora provato a creare un progetto con .NetFrameword 2.0 ma l'installazione tramite NuGet mi da questo errore:

Non è stato possibile installare il pacchetto 'FatturaElettronica.Core 2.0.0'. Si sta tentando di eseguire l'installazione in un progetto destinato a '.NETFramework,Version=v2.0', ma il pacchetto non contiene riferimenti ad assembly o file di dati compatibili con il framework. Per altre informazioni, contattare l'autore del pacchetto.

Come posso risolvere l'uno o l'altro caso ? Chiedo scusa in anticipo se l'errore è dovuto a una mia carenza.

Grazie

**Comment by nicolaiarocci** [comment]
Ciao Dario, Fattura Elettronica essendo un progetto netstandard 1.1 supporta .NET Framework dalla versione 4.5 e successive.
