### ISSUE TITLE
Error on total price validation

### ISSUE THREAD

**Issue by MassimoLinossi** [FatturaElettronica/FatturaElettronica.NET#181]
I have a problem with the validation.
With Qty 22633.00, UnitPrice 0.030987 and a total price calculated of 701.34 the validator is not giving an error. The correct totalprice must be 701.33
Is it possible to correct ?
Thanks a lot

**Comment by nicolaiarocci** [comment]
Ciao Massimo, in realtà secondo le specifiche tecniche è consentita la tolleranza di 1 centesimo, quindi tutto bene lato validazione (se provi a convalidare la stessa fattura sul sito PA dovrebbe accettarla.)

**Comment by MassimoLinossi** [comment]
Ciao Nicola.
Ad un cliente la fattura l’ha respinta, per questo avevo scritto. Ho risolto modificando il test sul totale riga togliendo il centesimo.
Grazie mille
Massimo

**Comment by nicolaiarocci** [comment]
In effetti la diff è > di 0,01 se lo calcoli non arrotondato, riapro.
