### ISSUE TITLE
Unicode Latin-1 show non valid characters

### ISSUE THREAD

**Issue by michaelmairegger** [FatturaElettronica/FatturaElettronica.NET#185]
Hi,

I create the invoice by program and show validation errors, if any, to the user. Therefore meaningful error messages are necessary. Therefore I thought that LatinBaseValidator can be extended to show the invalid charactes directly in the error message.
If you want I can open a PR for the branch https://github.com/michaelmairegger/FatturaElettronica.NET/commits/DisplayNonValidLatinCodes

**Comment by nicolaiarocci** [comment]
Hi @michaelmairegger,

Looks like a good idea, pleaso submit a PR, I'll gladly review it.
