### ISSUE TITLE
Segnalazione errore 00403

### ISSUE THREAD

**Issue by stefanodelbosco** [FatturaElettronica/FatturaElettronica.NET#187]
Buongiorno,
volevo suggerire l'implementazione del controllo 00403 o se già implementato esso presenta un'anomalia nella validazione del file XML.

Ho testato una fattura con data 13/04/2019 nella giornata del 10 di aprile e la validazione, tramite questa libreria, non ha segnalato nessun errore.

Validandola ulteriormente sul sito "ControllaFatturaPa" del portale "Fatture e corrispettivi" essa, invece, è stata"scartata" con l'errore 00403 ovvero "_Codice 00403 - La data della fattura non deve essere successiva alla data di ricezione_".

![image](https://user-images.githubusercontent.com/18212043/55957015-956e5900-5c65-11e9-939f-45c7104b4ddd.png)

Stefano

**Comment by nicolaiarocci** [comment]
Ciao, grazie per il suggerimento.

secondo le specifiche la data documento viene confrontata con la data di ricezione del documento da parte di SDI, che il validatore offline non può conoscere. Nella simulazione sul sito web PA usano la data del upload per fare il confronto, che è una utile simulazione. Ma offline, potresti sottoporre una fattura con data nel futuro rispetto a quella del computer e non necessariamente sarebbe poi respinta da SDI. Per questo motivo ho deciso di non implementare questo controllo. Al limite si potrebbe pensare a un warning, ma spesso le convalide sono poi esposte agli utenti finali che facilmente andrebbero in confusione.
