### ISSUE TITLE
Segnalazione errore 00418

### ISSUE THREAD

**Issue by dimdar74** [FatturaElettronica/FatturaElettronica.NET#190]
Ciao,

In fase di validazione di un documento semplificato viene restituito l'errore 00418 "Data antecedente a data fattura rettificata" quando invece la data documento è successivo alla data del documento rettificato.

Ho risolto modificando
`return datigenerali.DatiGeneraliDocumento.Data < data;`
in 
`return datigenerali.DatiGeneraliDocumento.Data >= data;`
nella classe
`FatturaElettronica.Validators.Semplificata.DatiGeneraliValidator`

Dario

**Comment by nicolaiarocci** [comment]
Grazie per la segnalazione.
