### ISSUE TITLE
Validatore 2.1.1.5.4 <CausalePagamento> da verificare (di nuovo)

### ISSUE THREAD

**Issue by ZephirPFS47** [FatturaElettronica/FatturaElettronica.NET#191]
Buongiorno, 
il commercialista di un mio cliente mi ha fatto notare che il controllo sulle causali pagamento sembra essere sbagliato. Secondo la guida per la certificazione unica 2019 allegata alle pagine 67/68 sono riportate le causali di pagamento, che sono diverse da quelle che attualmente passano la verifica. Ho chiamato il call center dell'agenzia delle entrate e mi hanno confermato che per le causali pagamento le seguenti sono quelle corrette: 

Tipologie reddituali da indicare nel modello 730/REDDITI Persone Fisiche 2019:

B – utilizzazione economica, da parte dell’autore o dell’inventore, di opere dell’ingegno, di brevetti industriali e di processi, formule o informazioni relativi ad esperienze acquisite in campo industriale, commerciale o scientifico;
C – utili derivanti da contratti di associazione in partecipazione e da contratti di cointeressenza, quando l’apporto è costituito esclusivamente dalla prestazione di lavoro;
D – utili spettanti ai soci promotori ed ai soci fondatori delle società di capitali;
E – levata di protesti cambiari da parte dei segretari comunali;
F – indennità corrisposte ai giudici onorari di pace e ai vice procuratori onorari;
L – redditi derivanti dall’utilizzazione economica di opere dell’ingegno, di brevetti industriali e di processi, formule e informazioni relativi a esperienze acquisite in campo industriale, commerciale o scientifico, che sono percepiti dagli aventi causa a titolo gratuito (ad es. eredi e legatari dell’autore e inventore);
L1 – redditi derivanti dall’utilizzazione economica di opere dell’ingegno, di brevetti industriali e di processi, formule e informazioni relativi a esperienze acquisite in campo industriale, commerciale o scientifico, che sono percepiti da soggetti che abbiano acquistato a titolo oneroso i diritti alla loro utilizzazione;
M – prestazioni di lavoro autonomo non esercitate abitualmente;
M1 – redditi derivanti dall’assunzione di obblighi di fare, di non fare o permettere;
M2 – prestazioni di lavoro autonomo non esercitate abitualmente per le quali sussiste l’obbligo di iscrizione alla Gestione Separata ENPAPI;
N – indennità di trasferta, rimborso forfetario di spese, premi e compensi erogati:
– nell’esercizio diretto di attività sportive dilettantistiche;
– in relazione a rapporti di collaborazione coordinata e continuativa di carattere amministrativo-gestionale di natura non professionale resi a favore di società e associazioni sportive dilettantistiche e di cori, bande e filodrammatiche da parte del direttore e dei collaboratori tecnici;
O – prestazioni di lavoro autonomo non esercitate abitualmente, per le quali non sussiste l’obbligo di iscrizione alla gestione separata (Circ. INPS n. 104/2001);
O1 – redditi derivanti dall’assunzione di obblighi di fare, di non fare o permettere, per le quali non sussiste l’obbligo di iscrizione alla gestione separata (Circ. INPS n. 104/2001);
V1 – redditi derivanti da attività commerciali non esercitate abitualmente (ad esempio, provvigioni corrisposte per prestazioni occasionali ad agente o rappresentante di commercio, mediatore, procacciatore d’affari); 

Tipologie reddituali da indicare esclusivamente nel modello REDDITI Persone Fisiche 2019 in quanto assoggettate a ritenuta a titolo d’acconto ovvero tipologie reddituali da non indicare in nessun modello di dichiarazione in quanto la tassazione si è resa già definitiva:

A – prestazioni di lavoro autonomo rientranti nell’esercizio di arte o professione abituale;
G – indennità corrisposte per la cessazione di attività sportiva professionale;
H – indennità corrisposte per la cessazione dei rapporti di agenzia delle persone fisiche e delle società di persone con esclusione delle somme maturate entro il 31 dicembre 2003, già imputate per competenza e tassate come reddito d’impresa;
I – indennità corrisposte per la cessazione da funzioni notarili;
J – compensi corrisposti ai raccoglitori occasionali di tartufi non identificati ai fini dell’imposta sul valore aggiunto, in relazione alla cessione di tartufi;
K – assegni di servizio civile universale di cui all’art.16 del D.lgs. n. 40 del 6 marzo 2017;
P – compensi corrisposti a soggetti non residenti privi di stabile organizzazione per l’uso o la concessione in uso di attrezzature industriali, commerciali o scientifiche che si trovano nel territorio dello Stato ovvero a società svizzere o stabili organizzazioni di società svizzere che possiedono i requisiti di cui all’art. 15, comma 2 dell’Accordo tra la Comunità europea e la Confederazione svizzera del 26 ottobre 2004 (pubblicato in G.U.C.E. del 29 dicembre 2004 n. L385/30);
Q – provvigioni corrisposte ad agente o rappresentante di commercio monomandatario;
R – provvigioni corrisposte ad agente o rappresentante di commercio plurimandatario;
S – provvigioni corrisposte a commissionario;
T – provvigioni corrisposte a mediatore;
U – provvigioni corrisposte a procacciatore di affari;
V – provvigioni corrisposte a incaricato per le vendite a domicilio; provvigioni corrisposte a incaricato per la vendita porta a porta e per la vendita ambulante di giornali quotidiani e periodici (L. 25 febbraio 1987, n. 67);
V2 – redditi derivanti dalle prestazioni non esercitate abitualmente rese dagli incaricati alla vendita diretta a domicilio;
W – corrispettivi erogati nel 2018 per prestazioni relative a contratti d’appalto cui si sono resi applicabili le disposizioni contenute nell’art. 25-ter del D.P.R. n. 600 del 29 settembre 1973;
X – canoni corrisposti nel 2004 da società o enti residenti ovvero da stabili organizzazioni di società estere di cui all’art. 26-quater, comma 1, lett. a) e b) del D.P.R. 600 del 29 settembre 1973, a società o stabili organizzazioni di società, situate in altro stato membro dell’Unione Europea in presenza dei requisiti di cui al citato art. 26-quater,
del D.P.R. 600 del 29 settembre 1973, per i quali è stato effettuato, nell’anno 2006, il rimborso della ritenuta ai sensi dell’art. 4 del D.Lgs. 30 maggio 2005 n. 143;
Y – canoni corrisposti dal 1° gennaio 2005 al 26 luglio 2005 da società o enti residenti ovvero da stabili organizzazioni di società estere di cui all’art. 26-quater, comma 1, lett. a) e b) del D.P.R. n. 600 del 29 settembre 1973, a società o stabili organizzazioni di società, situate in altro stato membro dell’Unione Europea in presenza dei requisiti di cui al citato art. 26-quater, del D.P.R. n. 600 del 29 settembre 1973, per i quali è stato effettuato, nell’anno 2006, il rimborso della ritenuta ai sensi dell’art. 4 del D.Lgs. 30 maggio 2005 n. 143;
ZO – titolo diverso dai precedenti.

[CU_istr_2019.pdf](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/3093637/CU_istr_2019.pdf)

**Comment by sgardini** [comment]
Sì ecco le istruzioni, torna. Purtroppo ad ogni dichiarazione cambiano......
[CU_istr_2019+agg+20+02+2019.pdf](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/3106239/CU_istr_2019%2Bagg%2B20%2B02%2B2019.pdf)

**Comment by davideurbani** [comment]
ZO e' errato!

E' vero che la causale del pagamento da specifiche CU deve essere "ZO", ma nelle istruzioni della fatturazione elettronica è scritto chiaramente che per causale "ZO" nel file XML deve essere indicato "Z".
Infatti anche nello schema XSD non è previsto il valore "ZO", la cui presenza causa un errore di validazione.

riporto stralcio della fonte che sono le specifiche tecniche fatturazione elettronica (https://www.agenziaentrate.gov.it/wps/file/Nsilib/Nsi/Schede/Comunicazioni/Fatture+e+corrispettivi/Fatture+e+corrispettivi+ST/ST+invio+di+fatturazione+elettronica/ST+Fatturazione+elettronica+-+Allegato+A/Allegato+A+-+Specifiche+tecniche+vers+1.4.1.pdf): 

**CausalePagamento: codice della causale del pagamento (il codice corrisponde a quello utilizzato per la compilazione del modello CU; per il codice M2 indicare il valore M; per il codice ZO indicare il valore Z).**

**Comment by nicolaiarocci** [comment]
🤦‍♂

**Comment by nicolaiarocci** [comment]
Ho rimosso ZO e M2 in favore di Z e M:

https://github.com/FatturaElettronica/FatturaElettronica.NET/commit/7d3b4e0c47125036ff70bec7b457cecc83564dae?diff=unified

Date occhiata per favore se vi torna.

**Comment by davideurbani** [comment]
Perfetto, mi sembra corretto, lo metto in produzione... se dovessi riscontrare altri problemi li segnalerò.

grazie

**Comment by psaggiomo** [comment]
Chiedo scusa, la causale M già era presente. Forse doveva essere aggiornata solo la sua descrizione? Altrimenti ora sono presenti due causali M con descrizioni diverse.
