### ISSUE TITLE
Errori di struttura XML non rilevati in fase di validazione

### ISSUE THREAD

**Issue by davideurbani** [FatturaElettronica/FatturaElettronica.NET#195]
Ho riscontrato che la fase di validazione non intercetta diversi errori presenti all'interno dell'XML che in base allo schema XSD rendono formalmente non conforme la fattura elettronica.

> var result = validator.Validate(fattura);

Uno degli errori riscontrati ad esempio, è la mancata verifica della presenza obbligatoria dell'elemento "CodiceDestinatario", ma ce ne sono diversi, ad esempio il numero corretto di cifre decimali per i campi che hanno come type "Amount2DecimalType"

E' possibile fare in modo che la fattura sia sottoposta anche a validazione rispetto allo schema XSD rilasciato dall'Agenzia, in modo da intercettare ogni possibile errore "formale" all'interno del file xml?

Grazie
Davide

**Comment by nicolaiarocci** [comment]
Ciao, il progetto è aperto alla collaborazione di tutti. Se vuoi aggiungere validazioni mancanti, apri una pull request e sarò lieto di dargli una occhiata. Assicurati prima di essere su ultima versione del pacchetto. Per esempio il CodiceDestinatario obbligatorio è controllato già da tempo.
