### ISSUE TITLE
Dicitura assoluzione imposta di bollo virtuale

### ISSUE THREAD

**Issue by vbMizio** [FatturaElettronica/FatturaElettronica.NET#196]
Buongiorno,
se una fattura ha bisogno di una imposta di bollo, dovrei indicare, nei dati del bollo stesso, la dicitura "Imposta di bollo assolta in modo virtuale ai sensi dell’articolo 15 del d.p.r. 642/1972 e del DM 17/06/2014", nei dati relativi al bollo stesso.
Nell'oggetto di tipo FatturaElettronica.Ordinaria.FatturaElettronicaBody.DatiGenerali.DatiBollo, ho solo due campi valorizzabili, cioè l'importo del bollo e il campo "Virtuale" che deve essere valorizzato con "SI".
Come/dove posso aggiungere la dicitura prevista?

**Comment by sgardini** [comment]
Va inserito nella lista delle Causali.....vedi esempio sotto

![GreenShot 000112 2019-05-10 11_41_33](https://user-images.githubusercontent.com/2329603/57518115-9fdd4a80-7318-11e9-9fb1-6cf03f56630b.png)
