### ISSUE TITLE
Obbligatorietà unità di misura

### ISSUE THREAD

**Issue by dimdar74** [FatturaElettronica/FatturaElettronica.NET#197]
Ciao!

Volevo portare all'attenzione che in base alla documentazione Suggerimenti_Compilazione_FatturaPA_1.5.pdf l'unità di misura è obbligatoria quando è indicata la quantità ma il validator non né tiene conto.

Dario

**Comment by nicolaiarocci** [comment]
![image](https://user-images.githubusercontent.com/512968/58239271-0f0b6380-7d49-11e9-8864-24abfb971895.png)

Nel documento da te citato non pare fare riferimento a questa obbligatorietà.
