### ISSUE TITLE
Validazione errore 00423 nel caso Quantita == Null

### ISSUE THREAD

**Issue by gminutillo** [FatturaElettronica/FatturaElettronica.NET#20]
La funzione `ValidateAgainstErr00423` non gestisce correttamente il caso  in cui la proprietà `Quantita == Null`. In questo caso la validazione fallisce anche se il valore di `PrezzoTotale` è corretto.

**Comment by nicolaiarocci** [comment]
Grazie per la segnalazione. Dovrebbe essere risolto ora.
