### ISSUE TITLE
Validazione Dati Fattura Rettificata

### ISSUE THREAD

**Issue by dimdar74** [FatturaElettronica/FatturaElettronica.NET#200]
Ciao a tutti,

Segnalo che la DataFR della classe DatiFatturaRettificata deve essere nullable altrimenti la validazione di DatiFatturaRettificata fallisce perché non è mai nulla o vuota.

Dario

**Comment by nicolaiarocci** [comment]
Ciao, dalle specifiche risulta che `DataFR` sia obbligatoria quindi sembra corretto lasciarla non-nullabile. Hai qualche riferimento che dice il contrario?

**Comment by dimdar74** [comment]
Ciao!

Si hai ragione, la DataFR è obbligatoria se specifico il nodo DatiFatturaRettificata ma se non la specifico come nullabile va in errore il controllo su nodo DatiFatturaRettificata se questo non è presente nel xml.

In pratica la validazione:

            RuleFor(x => x.DatiFatturaRettificata)
                .SetValidator(new DatiFatturaRettificataValidator())​
                .When(x => x.DatiFatturaRettificata != null && !x.DatiFatturaRettificata.IsEmpty());

non funziona perché DatiFatturaRettificata è sempre diversa da null e non è vuota in quanto la DataFR è valorizzata  01/01/0001 non essendo nullable.

Spero di essermi spiegato.

Dario

________________________________
Da: Nicola Iarocci <notifications@github.com>
Inviato: giovedì 23 maggio 2019 10:39
A: FatturaElettronica/FatturaElettronica.NET
Cc: dimdar74; Author
Oggetto: Re: [FatturaElettronica/FatturaElettronica.NET] Validazione Dati Fattura Rettificata (#200)


Ciao, dalle specifiche risulta che DataFR sia obbligatoria quindi sembra corretto lasciarla non-nullabile. Hai qualche riferimento che dice il contrario?

**Comment by nicolaiarocci** [comment]
Ottimo, grazie
