### ISSUE TITLE
Codice ISO Kosovo

### ISSUE THREAD

**Issue by Kratos-95** [FatturaElettronica/FatturaElettronica.NET#201]
Salve, come devo comportarmi con il codice ISO del Kosovo? Non essendo presente nella lista dei codici accettati di:  
- FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici.IdFiscaleIVA.IdPaese
- FatturaElettronicaHeader.CessionarioCommittente.Sede.Nazione
la fattura non supera il controllo di validazione

**Comment by tanogae** [comment]
Noi abbiamo utilizzato il codice RS anche se della Serbia.
