### ISSUE TITLE
Test mancanti per Semplificata.Validators.DatiGeneraliValidator 

### ISSUE THREAD

**Issue by nicolaiarocci** [FatturaElettronica/FatturaElettronica.NET#202]
a una veloce occhiata direi che mancano anche i test dei validatori utilizzati:

- Semplificata.Validators.DatiGeneraliDocumentoValidator
- Semplificata.Validators.DatiFatturaRettificataValidator

**Comment by nicolaiarocci** [comment]
@tanogae riesci a darci una occhiata?

**Comment by dimdar74** [comment]
La fattura semplice viene validata anche mettendo un tipo documento della fattura ordinaria.
Per risolvere il problema ho:

Aggiunto in Tabelle la sottodirectory Semplificata.
Ho creato la classe TipoDocumento:

`
ss
ss
ss
`

Ho commentato i tipi documento semplificati della classe namespace FatturaElettronica.Tabelle.TipoDocumento

`
namespace FatturaElettronica.Tabelle
{
   public class TipoDocumento : Tabella
   {
       public override Tabella[] List
       {
           get
           {
               return new Tabella[]
               {
                   new TipoDocumento { Codice = "TD01", Nome = "fattura" },
                   new TipoDocumento { Codice = "TD02", Nome = "acconto/anticipo su fattura" },
                   new TipoDocumento { Codice = "TD03", Nome = "acconto/anticipo su parcella" },
                   new TipoDocumento { Codice = "TD04", Nome = "nota di credito" },
                   new TipoDocumento { Codice = "TD05", Nome = "nota di debito" },
                   new TipoDocumento { Codice = "TD06", Nome = "parcella" },
                   //new TipoDocumento { Codice = "TD07", Nome = "fattura semplificata" },
                   //new TipoDocumento { Codice = "TD08", Nome = "nota di credito semplificata" },
                   //new TipoDocumento { Codice = "TD09", Nome = "nota di debito semplificata" },
                   new TipoDocumento { Codice = "TD20", Nome = "autofattura" }
               };
           }
       }
   }
}
`
E infine ho modificato il validator di TipoDocumento in FatturaElettronica.Validators.Semplificata.DatiGeneraliDocumentoValidator
`
RuleFor(x => x.TipoDocumento)
.NotEmpty()
.SetValidator(new IsValidValidator<Tabelle.Semplificata.TipoDocumento>());
`

Stesso discorso per la Natura, ho creato

`
namespace FatturaElettronica.Tabelle.Semplificata
{
   public class Natura : Tabella
   {
       public override Tabella[] List
       {
           get
           {
               return new Tabella[] {
                   new Natura { Codice = "N1", Nome = "escluse ex art. 15" },
                   new Natura { Codice = "N2", Nome = "non soggette" },
                   new Natura { Codice = "N3", Nome = "non imponibili" },
                   new Natura { Codice = "N4", Nome = "esenti" },
                   new Natura { Codice = "N5", Nome = "regime del margine / IVA non esposta in fattura" }
               };
           }
       }
   }
}
`

E ho modificato il validator di DatiBeniServiziValidator in FatturaElettronica.Validators.Semplificata.DatiBeniServiziValidator
sostituendo using FatturaElettronica.Tabelle con using FatturaElettronica.Tabelle.Semplificata;

**Comment by nicolaiarocci** [comment]
@dimdar74 ho aperto nuovo ticket, si tratta di problema diverso da quello discusso in questo thread.
