### ISSUE TITLE
Validazione elemento AltriDatiIdentificativi in FatturaSemplificata

### ISSUE THREAD

**Issue by gminutillo** [FatturaElettronica/FatturaElettronica.NET#203]
secondo la documentazione l'elemento **CessionarioCommittente/AltriDatiIdentificativi** della FatturaSemplificata può essere completamente omesso.
Attulamente il validatore segnala come errato un file con questo elemento mancante o vuoto.

**Comment by dimdar74** [comment]
Credo che la classe **FatturaElettronica.Validators.Semplificata.CessionarioCommittenteValidator** 
debba essere così:

`
using FatturaElettronica.Semplificata.FatturaElettronicaHeader.CessionarioCommittente;
using FluentValidation;

namespace FatturaElettronica.Validators.Semplificata
{
    public class CessionarioCommittenteValidator : AbstractValidator<CessionarioCommittente>
    {
        public CessionarioCommittenteValidator()
        {
            RuleFor(x => x.IdentificativiFiscali)
               .SetValidator(new IdentificativiFiscaliValidator());
            RuleFor(x => x.IdentificativiFiscali)
                .NotEmpty().WithMessage("IdentificativiFiscali è obbligatorio");
            RuleFor(x => x.AltriDatiIdentificativi)
                .SetValidator(new AltriDatiIdentificativiValidator())
                .When(x => x.AltriDatiIdentificativi != null && !x.AltriDatiIdentificativi.IsEmpty());
        }
    }
}
`

**Comment by nicolaiarocci** [comment]
Al momento dovrebbe comportarsi proprio come dici. Questo test qui sotto passa senza problemi. Hai ispezionati gli errori per verificare che non ti dia errore su qualche altro campo, tipo Id Paese?

![image](https://user-images.githubusercontent.com/512968/58261016-d3d45900-7d77-11e9-8707-2ee0a85874d9.png)

**Comment by gminutillo** [comment]
ti allego il file valido per l'SDI ma errato se validato con la libreria:

```
<?xml version="1.0" encoding="utf-8"?>
<p:FatturaElettronicaSemplificata versione="FSM10" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 fatturaordinaria_v1.2.xsd" xmlns:p="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0">
	<FatturaElettronicaHeader>
		<DatiTrasmissione>
			<IdTrasmittente>
				<IdPaese>IT</IdPaese>
				<IdCodice>12345678903</IdCodice>
			</IdTrasmittente>
			<ProgressivoInvio>000000001</ProgressivoInvio>
			<FormatoTrasmissione>FSM10</FormatoTrasmissione>
			<CodiceDestinatario>0000000</CodiceDestinatario>
		</DatiTrasmissione>
		<CedentePrestatore>
			<IdFiscaleIVA>
				<IdPaese>IT</IdPaese>
				<IdCodice>12345678903</IdCodice>
			</IdFiscaleIVA>
			<Denominazione>Acme Inc.</Denominazione>
			<RegimeFiscale>RF01</RegimeFiscale>
			<Sede>
				<Indirizzo>Grand Canyon</Indirizzo>
				<CAP>12345</CAP>
				<Comune>Arizona</Comune>
				<Provincia>AZ</Provincia>
				<Nazione>IT</Nazione>
			</Sede>
		</CedentePrestatore>
		<CessionarioCommittente>
			<IdentificativiFiscali>
				<IdFiscaleIVA>
					<IdPaese>IT</IdPaese>
					<IdCodice>12345678903</IdCodice>
				</IdFiscaleIVA>
			</IdentificativiFiscali>
		</CessionarioCommittente>
	</FatturaElettronicaHeader>
	<FatturaElettronicaBody>
		<DatiGenerali>
			<DatiGeneraliDocumento>
				<TipoDocumento>TD07</TipoDocumento>
				<Divisa>EUR</Divisa>
				<Data>2019-01-31</Data>
				<Numero>123456789</Numero>
			</DatiGeneraliDocumento>
		</DatiGenerali>
		<DatiBeniServizi>
			<Descrizione>Corrispettivo</Descrizione>
			<Importo>1.78</Importo>
			<DatiIVA>
				<Imposta>0.32</Imposta>
				<Aliquota>22.00</Aliquota>
			</DatiIVA>
		</DatiBeniServizi>
	</FatturaElettronicaBody>
</p:FatturaElettronicaSemplificata>
```
come puoi vedere l'elemento **AltriDatiIdentificativi** è completamente assente.

**Comment by dimdar74** [comment]
Attualmente la classe CessionarioCommittenteValidator prevede queste regole:
        
            RuleFor(x => x.IdentificativiFiscali)
                .NotEmpty()
                .WithErrorCode("00431")
                .When(x => x.AltriDatiIdentificativi == null);

e non la capisco perchè la rappresentazione tabellare prevede che IdentificativiFiscali sia sempre indicata

![image](https://user-images.githubusercontent.com/28957617/58264475-3892b200-7d7e-11e9-9644-4b04a7b0d7af.png)

inoltre la regola

            RuleFor(x => x.AltriDatiIdentificativi)
                .NotEmpty()
                .WithErrorCode("00431")
                .When(x => x.IdentificativiFiscali == null);        

mi pare che non serva visto che IndentificativiFiscali non deve mancare.

AltriDatiIdentificativi dovrebbe essere controllato che se presente e non sia vuoto perché sede è obbligatorio (quindi ho sbagliato prima :) )

![image](https://user-images.githubusercontent.com/28957617/58265879-d12a3180-7d80-11e9-8d1a-9dad5d61c434.png)
