### ISSUE TITLE
Unità di misura non può essere vuota se viene indicato il nodo

### ISSUE THREAD

**Issue by dimdar74** [FatturaElettronica/FatturaElettronica.NET#204]
Ciao,

Scusa se ripropongo questo argomento ma credo di aver trovato il problema:

**L'unità di misura non è obbligatoria**, tuttavia se viene inserito il nodo vuoto questo passa i controlli ma poi viene respinto con questo errore:

> Error 1839: Element 'UnitaMisura': [facet 'pattern'] The value '' is not accepted by the pattern '(\p{IsBasicLatin}{1,10})'. Linea 1. Error 1824: Element 'UnitaMisura': '' is not a valid value of the atomic type '{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String10Type'. Linea 1.<

Credo che il validator dell'unita di misura debba essere disattivo solo quando è null e non per empty:

`            RuleFor(x => x.UnitaMisura)
                .Length(1, 10)
                .BasicLatinValidator()
                .When(x => !string.IsNullOrEmpty(x.UnitaMisura));
`

Dario

**Comment by nicolaiarocci** [comment]
Intendi dire che viene restituito errore se imposti esplictamente `UnitaMisura = String.Empty`(o `""`)?

**Comment by dimdar74** [comment]
Esatto! Il documento ci è stato scartato con l'errore che ti ho segnalato perché il nodo unita di misura è presente ma non valorizzato,

<DettaglioLinee>
<NumeroLinea>12</NumeroLinea>
<Descrizione>VALORE CONCORDATO TOTALE</Descrizione>
<Quantita>1.00</Quantita>
<UnitaMisura></UnitaMisura>
<PrezzoUnitario>800.000</PrezzoUnitario>
<PrezzoTotale>800.00</PrezzoTotale>
<AliquotaIVA>22.00</AliquotaIVA>
</DettaglioLinee>

Ovviamente è stato sufficiente verificare che l'unità di misura fosse valorizzata invece di mettere il nodo senza valore per risolvere, comunque attualmente la validazione non evidenzia il problema.

Sinceramente penso sia più un difetto di SDI che va a controllare il valore del nodo anche se questo è vuoto mentre non gli esegue se il nodo è mancante. Questo è quanto abbiamo riscontrato qui da noi.


________________________________
Da: Nicola Iarocci <notifications@github.com>
Inviato: giovedì 23 maggio 2019 15:58
A: FatturaElettronica/FatturaElettronica.NET
Cc: dimdar74; Author
Oggetto: Re: [FatturaElettronica/FatturaElettronica.NET] Unità di misura non può essere vuota se viene indicato il nodo (#204)


Intendi dire che viene restituito errore se imposti esplictamente UnitaMisura = String.Empty(o "")?

**Comment by dimdar74** [comment]
Visto che abbiamo appurato che io non uso la libreria per generare il file xml, forse è il caso di reinserire il controllo originale per l'unità di misura?

`RuleFor(x => x.UnitaMisura) .Length(1, 10) .BasicLatinValidator() .When(x => !string.IsNullOrEmpty(x.UnitaMisura));`
