### ISSUE TITLE
Validazione elemento AltriDatiIdentificativi in FatturaSemplificata (errata corrige)

### ISSUE THREAD

**Issue by dimdar74** [FatturaElettronica/FatturaElettronica.NET#206]
Mi sono accorto che regola della validazione del nodo AltriDatiIdentificativi deve essere applicata anche se il nodo è presente ma vuoto perché altrimenti non verrebbero restituiti i vari errori per nodi obbligatori omessi (che invece SDI ritornerebbe).

Quindi la classe FatturaElettronica.Validators.Semplificata.CessionarioCommittenteValidator diventerebbe:

```
using FatturaElettronica.Semplificata.FatturaElettronicaHeader.CessionarioCommittente;
using FluentValidation;

namespace FatturaElettronica.Validators.Semplificata
{
    public class CessionarioCommittenteValidator : AbstractValidator<CessionarioCommittente>
    {
        public CessionarioCommittenteValidator()
        {
            RuleFor(x => x.IdentificativiFiscali)
               .SetValidator(new IdentificativiFiscaliValidator());
            RuleFor(x => x.IdentificativiFiscali)
                .NotEmpty().WithMessage("IdentificativiFiscali è obbligatorio");
            RuleFor(x => x.AltriDatiIdentificativi)
                .SetValidator(new AltriDatiIdentificativiValidator())
               .When(x => x.AltriDatiIdentificativi != null );
        }
    }
}
```

PS
Colgo l'occasione per ringraziarti di avere condiviso il tuo ottimo lavoro.
Dario

**Comment by nicolaiarocci** [comment]
Prova a vedere se la 2.0.6 appena rilasciata risolve il problema.

**Comment by dimdar74** [comment]
No, nella 2.0.6 c'è la versione che ho postato ieri nel #203 dove è presente il bug, il problema l'ho riscontrato stamani mentre testavo alcuni file xml.

**Comment by nicolaiarocci** [comment]
![image](https://user-images.githubusercontent.com/512968/58322406-2c136580-7e21-11e9-9a18-ce53c87acb90.png)

questo è il codice della 2.0.6, mi sembra allineato con la tua proposta qui sopra (mi ero accorto della discrepanza). Fammi sapere.

**Comment by dimdar74** [comment]
Io sto dicendo che la condizione "&& !x.AltriDatiIndentificativi.IsEmpty()" va tolta:

![image](https://user-images.githubusercontent.com/28957617/58327091-fd03f080-7e2e-11e9-9075-92d19be2613f.png)

altrimenti non vengono restituiti i vari errori per i sotto-nodi obbligatori omessi nel nodo AltriDatiIdentificativi.

Il seguente nodo xml
```
    <CessionarioCommittente>
      <IdentificativiFiscali>
        <IdFiscaleIVA>
          <IdPaese>IT</IdPaese>
          <IdCodice>00318750973</IdCodice>
        </IdFiscaleIVA>
      </IdentificativiFiscali>
      <AltriDatiIdentificativi/>
    </CessionarioCommittente>
```
deve generare errore mentre con "&& !x.AltriDatiIndentificativi.IsEmpty()" la validazione viene  passata. E' lo stesso problema che avevo con l'unità di misura per capirci.

**Comment by nicolaiarocci** [comment]
Non mi torna. Con la modifica che suggerisci la fattura proposta da @gminutillo in #203 non viene convalidata correttamente, proprio perchè rileva errori su `AltriDatiIdentificativi` vuoto.

**Comment by nicolaiarocci** [comment]
PS: per default una nuova fattura ha `AltriDatiIdentificativi` valorizzato a un istanza vuota, non a null.

**Comment by nicolaiarocci** [comment]
epperò è vero che la stessa fattura con `AltriDatiIdentificativi` vuoto nel XML (come nel tuo esempio) non passa convalida SDI...

**Comment by dimdar74** [comment]
Questa è la rappresentazione tabellare:

![image](https://user-images.githubusercontent.com/28957617/58330252-ca5df600-7e36-11e9-8395-1c64669d693e.png)

Se indico il nodo `AltriDatiIdentificativi` è obbligatorio indicare anche il sotto-nodo `Sede` (né prendo uno per tutti) secondo me dovrebbe dare errore di validazione se inserisco `AltriDatiIdentificativi` vuoto ma aggiungendo la condizione non mi viene restituito perché non viene più controllata la presenza o meno del nodo `Sede`

**Comment by nicolaiarocci** [comment]
Ma come fai ad ottenere un XML con `AltriDatiIdentificativi` presente ma vuoto? FE.NET non lo genera (se oggetto vuoto non lo serializza); SDI lo rifiuta. Arriva da altra fonte?

**Comment by dimdar74** [comment]
Ho visto ora il tuo ultimo post.
E' esattamente lo stesso problema che avevo con l'unità di misura, se metti il nodo non può essere vuoto altrimenti, se non ci sono altri dati da indicare, il nodo `AltriDatiIdentificativi` non deve essere inserito.

**Comment by dimdar74** [comment]
> Ho visto ora il tuo ultimo post.
> E' esattamente lo stesso problema che avevo con l'unità di misura, se metti il nodo non può essere vuoto altrimenti, se non ci sono altri dati da indicare, il nodo `AltriDatiIdentificativi` non deve essere inserito.

Si, il gestionale genera il file xml e poi viene convalidato in fase di caricamento nel nostro portale, non uso mai direttamente la libreria per generare il file xml

**Comment by nicolaiarocci** [comment]
Il problema è che l'instanza di `AltriDatiIdentificativi` a cui si applica il validatore è Empty sia quando il tag è assente (caso del ticket 203), sia quando è presente, ma vuoto (il tuo caso). Non vedo un modo di distinguere le due situazioni in fase di convalida, e tra le due mi sembra più rilevante il caso 203 (più frequente/probabile).

**Comment by dimdar74** [comment]
Ok. Chiudiamo pure questo caso e lasciamolo come dici, per quanto mi riguarda il problema non mi si dovrebbe ripresentare perché il gestionale è stato corretto e qualora succedesse SDI mi ritornerà l'errore, mal di poco.

Mi spiace averti fatto perdere tempo.

**Comment by nicolaiarocci** [comment]
infatti stavo per consigliarti di sistemare il gestionale piuttosto :-)
