### ISSUE TITLE
Mancato controllo validazione fattura ordinaria

### ISSUE THREAD

**Issue by exolabsrl** [FatturaElettronica/FatturaElettronica.NET#208]
Buongiorno,

ho riscontrato un errore nella validazione di una fattura ordinaria. Aprendo un file xml ed eseguendo la validazione, il controllo non mi segnala l'anomalia.
Nel file "incriminato" (xml generato con altri sw), hanno erroneamente inserito la sezione Allegati (2.5) all'interno della sezione DatiPagamento (2.4) ed il validatore non rintraccia l'errore.

![image](https://user-images.githubusercontent.com/51231215/58698405-80779180-839b-11e9-962c-5dbab12c09ad.png)

Sto usando la libreria per effettuare la verifica delle fatture che ci inviano prima di mandarle direttamente allo SDI che in questo caso ha rigettato questo specifico file in quanto non conforme

![image](https://user-images.githubusercontent.com/51231215/58698772-422ea200-839c-11e9-86fe-bbb988953a67.png)

C'è modo di far controllare al Validatore anche questa casistica?
Vi ringrazio
Marco

**Comment by nicolaiarocci** [comment]
Ciao Marco,

Non ho provato, ma immagino che quando questo xml viene de-serializzato, il blocco `Allegati` in posizione errata venga ignorato. Poichè il validatore agisce sulla istanza e non sul xml, a quel punto diventa dura fargli notare il problema. A meno che il blocco in posizione sbagliata non sia anche obbligatorio: non essendo de-serializzato, allora l'errore verrà segnalato come campo obbligatorio mancante (non è questo il caso degli Allegati).

**Comment by exolabsrl** [comment]
Ciao Nicola, 

avevo capito che il funzionamento della classe è quello che mi descrivi, la mia segnalazione voleva essere un monitor di quello che potrebbe succedere.
Per il mio caso, ho risolto introducendo nel codice, una funzione che compara la struttura dell'xml con lo schema xsd pubblicato.
Se pensi possa essere un ulteriore controllo da inserire nel validatore o meglio prima di de-serializzare, fammi sapere come posso passarti il mio lavoro (non sono esperto di github!)

Grazie e complimenti questo è un ottimo progetto!

**Comment by exolabsrl** [comment]
Ciao Nicola, 

avevo capito che il funzionamento della classe è quello che mi descrivi, la mia segnalazione voleva essere un monitor di quello che potrebbe succedere.
Per il mio caso, ho risolto introducendo nel codice, una funzione che compara la struttura dell'xml con lo schema xsd pubblicato.
Se pensi possa essere un ulteriore controllo da inserire nel validatore o meglio prima di de-serializzare, fammi sapere come posso passarti il mio lavoro (non sono esperto di github!)

Grazie e complimenti questo è un ottimo progetto!
