### ISSUE TITLE
Aggiornare al formato 1.2 in vigore dal 1.1.2017

### ISSUE THREAD

**Issue by nicolaiarocci** [FatturaElettronica/FatturaElettronica.NET#21]

**Comment by sibylmichelangelotodaro** [comment]
Grazie.
Ho fatto la prova a modificare l'intestazione del file e il <FormatoTrasmissione> in FPA12 e ha funzionato.
Attendiamo rilascio.
Buon lavoro

**Comment by nicolaiarocci** [comment]
Lo sviluppo è in corso sulla branch [versione0.3](https://github.com/FatturaElettronicaPA/FatturaElettronicaPA/tree/versione0.3). Consiglio di seguirla perché ci sono importanti cambiamenti, inclusa la rottura della compatibilità col passato. Consultare il file [CHANGES](https://github.com/FatturaElettronicaPA/FatturaElettronicaPA/blob/versione0.3/CHANGES) della v0.3 per rimanere aggiornati.

**Comment by Magic73** [comment]
Grazie Mille!

**Comment by nicolaiarocci** [comment]
Ho rilasciato la [versione 0.3](https://www.nuget.org/packages/FatturaElettronica/) su NuGet. Attenzione 

- è cambiato il nome del package
- ci sono dei breaking change

Vedere il [changelog](https://github.com/FatturaElettronicaPA/FatturaElettronicaPA/blob/versione0.3/CHANGES).
