### ISSUE TITLE
Aggiunta Kosovo

### ISSUE THREAD

**Issue by NeroMancini** [FatturaElettronica/FatturaElettronica.NET#214]
Buongiorno,
in relazione agli errore di validazione: 'Id Paese' valori accettati:... e 'Nazione' valori accettati:...
sarebbe possibile aggiungere tra i paesi il Kosovo?
La sigla dovrebbe essere XK.

Grazie

**Comment by nicolaiarocci** [comment]
Ciao,

XK Kosovo non rientra nella [tabella ISO 3166-1](https://it.wikipedia.org/wiki/ISO_3166-1) come da specifiche tecniche. Hai verificato se SDi lo accetta?

**Comment by ProH4Ck** [comment]
Stesso problema. Confermo che viene accettato da SDi (prova fatta adesso forzando il valore nel file xml prodotto)

**Comment by NeroMancini** [comment]
Grazie
