### ISSUE TITLE
Controllo partita iva coerente 

### ISSUE THREAD

**Issue by brux88** [FatturaElettronica/FatturaElettronica.NET#218]
Ciao ho appena saputo che l Ade ha aggiunto un nuovo controllo vi riporto la notifica di avviso :

La ringraziamo per la segnalazione e La informiamo che proprio ieri l'AdE ha rilasciato nuovi controlli in merito e quindi dovrebbe verificare che nella generazione XML vengano riportati in maniera coerente Partita IVA e Codice Fiscale.

![Screenshot_20190731-124349_Outlook](https://user-images.githubusercontent.com/3495339/62205996-0e1e3000-b391-11e9-9029-9cd5aa107ca5.jpg)

Come si evince,in tutti i casi in cui viene indicato il CF e la PIVA del destinatario uguali si riceve lo scarto:
<IdFiscaleIVA> e 1.4.1.2 <CodiceFiscale> non coerenti

Pertanto Le consigliamo riemettere il documento inserendo i dati coerenti oppure non compilando il campo del CF.

**Comment by sgardini** [comment]
Sì ho verificato il problema stamattina pure io. Ma se ho capito bene si verifica solo se per ditte individuali si usa il codice fiscale numerico (= alla partita iva) anzichè quello alfanumerico (personale) che è nel caso quello corretto

**Comment by nicolaiarocci** [comment]
Vedi #219
