### ISSUE TITLE
Nuovi controlli v 1.5 specifiche tecniche AdE

### ISSUE THREAD

**Issue by sgardini** [FatturaElettronica/FatturaElettronica.NET#219]
![GreenShot 000261 2019-08-02 11_05_13](https://user-images.githubusercontent.com/2329603/62358882-f0c69e80-b515-11e9-8456-2f37b67a7cf8.png)

https://www.agenziaentrate.gov.it/wps/file/Nsilib/Nsi/Schede/Comunicazioni/Fatture+e+corrispettivi/Fatture+e+corrispettivi+ST/ST+invio+di+fatturazione+elettronica/ST+Fatturazione+elettronica+-+Allegato+A/Allegato+A+-+Specifiche+tecniche+vers+1.5.pdf

**Comment by nicolaiarocci** [comment]
Se non sbaglio servono modifiche in quanto i controlli sono svolti lato PA sui loro server di convalida dei CF/PIVA. Confermate?

**Comment by sgardini** [comment]
Esatto quindi a mio parere NON servono modifiche

**Comment by brux88** [comment]
si esatto
