### ISSUE TITLE
Validazione nodi che dipendono da valori di nodi padre

### ISSUE THREAD

**Issue by tavolate** [FatturaElettronica/FatturaElettronica.NET#22]
Come da specifica della fatturaPa, la validazione di alcuni nodi, dipendono dal valore di altri nodi parent. Per esempio secondo le specifiche qui sotto

http://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.pdf

Il campo 2.1.1.5 \<DatiRitenuta> segue le seguenti regole di validazione:

> Viene controllata la presenza di questo blocco in presenza di almeno un blocco 2.2.1 \<DettaglioLinee> con l'elemento
2.2.1.13 \<Ritenuta> uguale a 'SI' e/o di un blocco 2.1.1.7 <DatiCassaPrevidenziale> con l'elemento 2.1.1.7.6
<Ritenuta> uguale a 'SI'

Come vedi, questo nodo dipende da un nodo ad un livello superiore. Come questo nodo, ce ne sono altri.

Questa libreria, gestisce queste validazioni?

**Comment by nicolaiarocci** [comment]
Non ancora. Potresti fornire un elenco dei controlli di questo tipo attualmente mancanti?

**Comment by nicolaiarocci** [comment]
Dovrebbe essere risolto.

**Comment by tavolate** [comment]
Grazie mille, provo.

Come l'esempio che ho riportato, ci sono altre validazioni che dipendono da altri nodi.  A breve ti mando l'elenco.
