### ISSUE TITLE
Codice Destinatario Estero

### ISSUE THREAD

**Issue by massi16894** [FatturaElettronica/FatturaElettronica.NET#225]
Buongiorno,

il codice destinatario per una fattura estera è da valorizzare con 7 "X" ma il controllo che vine fatto dice che posso inserire al massimo 6 "X" è possibile fixare questo problema?

**Comment by sgardini** [comment]
Il controllo accetta 6 caratteri per il tipo fattura FPA12 (verso enti pubblici) mentre accetta 7 caratteri per il tipo fattura FPR12 (tra privati). Verifica di usare il tipo FPR12, in quel caso sono accettati 7 caratteri
