### ISSUE TITLE
ImponibileImporto numero decimali

### ISSUE THREAD

**Issue by ZeusZoe** [FatturaElettronica/FatturaElettronica.NET#226]
Innanzitutto un ringraziamento per l'ottimo lavoro.
In riferimento a quanto in oggetto, ho avuto dei problemi sul numero dei decimali utilizzati per il campo "ImponibileImporto".
L'agenzia delle entrate mi rifiuta la fattura segnalandomi errore di formato nel valore di ImponibileImporto che è di Euro 19.761.
Ho fatto un test impostando il valore a 19.76 e me lo ha preso regolarmente.
Naturalmente ciò contraddice le specifiche tecniche che loro stessi hanno rilasciato.

Saluti

**Comment by nicolaiarocci** [comment]
Confermo che il tipo `xs:decimal` supporta fino a 2 decimali, vedi anche il xsd di riferimento.
