### ISSUE TITLE
rootelement in fattura semplificata

### ISSUE THREAD

**Issue by lpardossi** [FatturaElettronica/FatturaElettronica.NET#230]
Salve, la fattura semplificata che viene prodotta ha come primo elemento 
<p:FatturaElettronicaSemplificata ... 
mentre dovrebbe essere <ns2:FatturaElettronicaSemplificata ... 
Creo l'istanza in questo modo:
 Dim fattura1S As FatturaSemplificata
 fattura1S = FatturaSemplificata.CreateInstance(Defaults.Instance.Semplificata)
C'è qualcosa da impostare? Oppure è effettivamente un problema?
Grazie

**Comment by nicolaiarocci** [comment]
Ciao, scusa per il ritardo. Non dovrebbe dare problemi nè in convalida PA nè altrove. Hai esperienza contraria?
