### ISSUE TITLE
Nuove Specifiche 1 Gennaio 2020 Versione 1.6

### ISSUE THREAD

**Issue by tanogae** [FatturaElettronica/FatturaElettronica.NET#231]
Buongiorno,

  non vorrei creare allarmismi ma su Forum Italia gira questa voce.

Voi ne sapete qualcosa?

Grazie

**Comment by nicolaiarocci** [comment]
al momento non sappiamo nulla di ufficiale

**Comment by tanogae** [comment]
**Novità del tracciato**
- Ritenuta diventa lista per gestire Enasarco
- Valore del bollo sparisce
- Natura iva aumentano i caratteri per gestire sotto natura
- Nuovi tipi documenti

**Tempistiche**
Specifiche entro il 31/12
Possibilità di utilizzare nuovo formato dal 01/03/2020
Obbligo di utilizzare nuovo formato dal 01/07/2020

**Comment by tanogae** [comment]
@nicolaiarocci hai già pensato come gestire il periodo di transizione tra i 2 tracciati?

**Comment by nicolaiarocci** [comment]
La v3 di FE sarà compatibile col nuovo tracciato mentre la 2 rimmarrà sul vecchio.
