### ISSUE TITLE
Versione vecchia nuget

### ISSUE THREAD

**Issue by ZephirPFS47** [FatturaElettronica/FatturaElettronica.NET#232]
Buongiorno, è normale che su nuget (https://www.nuget.org/packages/FatturaElettronica/) l'ultima versione presente sia ancora la 2.0.6? Sarebbe possibile aggiornarla alla 2.0.7, almeno come versione preliminare?

**Comment by nicolaiarocci** [comment]
la 2.0.7 è su nuget da qualche minuto.
