### ISSUE TITLE
Massimo importo fattura semplificata

### ISSUE THREAD

**Issue by ZephirPFS47** [FatturaElettronica/FatturaElettronica.NET#233]
A quanto pare nel validatore della fattura semplificata il limite per l'importo totale è impostato a 100 euro. 
Da maggio il limite è stato portato a 400 euro
https://www.informazionefiscale.it/fattura-semplificata-limite-400-100-euro-decreto-MEF

**Comment by nicolaiarocci** [comment]
Ciao, grazie. Hai già verificato che il validatore PA sia allineato?

**Comment by ZephirPFS47** [comment]
Per validatore PA intendi FatturaElettronicaBodyValidator fuori dalla cartella semplificata? Se è quello non contiene già nessun controllo sull'importo massimo

**Comment by nicolaiarocci** [comment]
no intendevo la PA proprio. Comunque è rilasciato :-)

**Comment by ZephirPFS47** [comment]
Perfetto grazie! Comunque non saprei dove si trova il validatore PA
