### ISSUE TITLE
L'elemento DatiIva della fattura semplificata è obbligatorio

### ISSUE THREAD

**Issue by gminutillo** [FatturaElettronica/FatturaElettronica.NET#238]
mentre effettuavo i controlli sulle fatture semplificate ho scoperto che la serializzazione delle fattura semplificata omette l'elemento `<DatiIva>` nel caso in cui la riga della fattura non ha una aliquota iva ma è presente il campo `<Natura>`

Questo tipo di fatture vengono scartate con questo messaggio:

> Invalid content was found starting with element 'Natura'. One of '{DatiIVA}' is expected. riga: 69 - colonna: 12 - File non conforme al formato

in pratica  l'elemento `<DatiIva>` deve essere inserito nel file anche se `Imposta` e `Aliquota` sono nulli

**Comment by nicolaiarocci** [comment]
In quel caso non dovrebbe essere presente DatiIva con Imposta o Aliquota a 0?

**Comment by gminutillo** [comment]
si, forzando **DatiIva.Imposta = 0** e **DatiIva.Aliquota = 0** la fattura viene serializzata correttamente.

Forse sarebbe meglio cambiarne il tipo da decimal? a decimal, oppure aggiungere:

```
public override bool IsEmpty()
{
     return false;
}

```
alla classe DatiIva

**Comment by nicolaiarocci** [comment]
Mi pare di capire che in realtà sia un problema di convalida, ovvero se Natura è valorizzato allora DatiIva deve esserlo (eventualmente forzando su valori a 0). Cosa ne pensi?

**Comment by nicolaiarocci** [comment]
hmm vedo ora che in realtà il validatore verifica che DatiIva non sia vuoto.

**Comment by gminutillo** [comment]
in pratica l'elemento DatiIva deve essere sempre presente nel file XML sia se Natura è valorizzato, sia (a maggior ragione) se lo sono Imposta e Aliquota. 
penso che il modo più 'indolore' per risolvere si quello di fare l'override di **IsEmpty** che a mio avviso è meglio che cambiare il tipo di dato a Imposta e Aliquota

**Comment by nicolaiarocci** [comment]
no, penso che sia giusto serializzare rispecchiando i contenuti dell'istanza. Per design, serializzare una fattura non valida è possibile. Piuttosto, la convalida per DatiIVA non funziona: è sì imposta a NotEmpty(), ma non si attiva.

**Comment by gminutillo** [comment]
> no, penso che sia giusto serializzare rispecchiando i contenuti dell'istanza. Per design, serializzare una fattura non valida è possibile

giusto. 
sono d'accordo.

**Comment by nicolaiarocci** [comment]
Dovrebbe essere sistemato.
