### ISSUE TITLE
Problema Prezzo Unitario a Zero

### ISSUE THREAD

**Issue by paolofrancioso** [FatturaElettronica/FatturaElettronica.NET#239]
Ciao,

per questo blocco di XML:

`<DettaglioLinee>
				<NumeroLinea>11</NumeroLinea>
				<TipoCessionePrestazione>AC</TipoCessionePrestazione>
				<Descrizione>Bollo</Descrizione>
				<Quantita>1.00</Quantita>
				<UnitaMisura>NR</UnitaMisura>
				<PrezzoUnitario>0</PrezzoUnitario>
				<PrezzoTotale>0</PrezzoTotale>
				<AliquotaIVA>0.00</AliquotaIVA>
				<Natura>N1</Natura>
			</DettaglioLinee>`

Il validatore sembra dire che vada tutto bene. Il sito dell'agenzia delle entrate non la pensa allo stesso modo.

**Comment by nicolaiarocci** [comment]
Credo il problema sia in realtà lo 0 singolo. Prova a mettere 0.00 sia in prezzo unitario che totale per favore, e fammi sapere se la accetta. Mi risulta che 0 (valore) sia possibile. Se è così, immagino XML non sia prodotto da FE.NET. Quando lo carica e lo convalida dice che è ok perchè il valore 0 è consentito.

**Comment by nicolaiarocci** [comment]
PS: se serializzi via FE (e mi ricordo bene!) dovrebbe serializzare con 0.00: quel file te lo accetterà.

**Comment by nicolaiarocci** [comment]
(la convalida fatta da FE è su istanza in memoria, non direttamente su XML)

**Comment by paolofrancioso** [comment]
Ciao,
la fattura XML è prodotta da SAP non da FE.NET. Io ho utilizzato le librerie del Validator per fare un programmino di controllo prima di inviare il tutto all'agenzia delle entrate.
Proveremo a caricare 0,00 invece di 0, credo sarebbe opportuno (se possibile) aggiungere questo controllo formale nel caso di esito positivo.
Grazie!
