### ISSUE TITLE
Imposta e ImportoPagamento assegnati a 0

### ISSUE THREAD

**Issue by filippoangileri** [FatturaElettronica/FatturaElettronica.NET#241]
Buonasera, ho notato che non vengono effettuati dei controlli sulla presenza dei campi in oggetto.
Esempio:
`<DatiRiepilogo>
        <AliquotaIVA>0.00</AliquotaIVA>
        <Natura>N1</Natura>
        <ImponibileImporto>33.00</ImponibileImporto>
      </DatiRiepilogo>`

`<DatiPagamento>
      <CondizioniPagamento>TP02</CondizioniPagamento>
      <DettaglioPagamento>
        <ModalitaPagamento>MP18</ModalitaPagamento>
        <DataRiferimentoTerminiPagamento>2019-12-18</DataRiferimentoTerminiPagamento>
        <DataScadenzaPagamento>2020-01-20</DataScadenzaPagamento>
      </DettaglioPagamento>
    </DatiPagamento>`
I Tag Imposta e ImportoPagamento non sono presenti ma all'interno dell'oggetto Fattura che viene instanzianto nel seguente modo:
`var fattura = new FatturaOrdinaria();`
`fattura.ReadXml(r);`
tali sono presenti e hanno valore 0
Potete effettuare una verifica?
Grazie mille

**Comment by filippoangileri** [comment]
@nicolaiarocci puoi verificare la mia segnalazione?
Grazie mille

**Comment by nicolaiarocci** [comment]
Se non sbaglio sono campi decimali non nullabili, non possono che essere a zero se non deserializzati.

**Comment by filippoangileri** [comment]
Grazie @nicolaiarocci !
Ma quindi se in una fattura da controllare tali non sono presenti vengono sempre inseriti di default a zero? Come è possibile controllare l'effettiva presenza di questi campi obbligatori?

**Comment by nicolaiarocci** [comment]
La convalida viene fatta sulla istanza deserializzata, non direttamente sul XML. Di conseguenza questo tipo di "errori" non vengono rilevati, e correttamente perchè se poi serializzi la fattura i 2 importi appaiono correttamente nel xml, quindi dal punto di vista di FE.NET è tutto a posto.
