### ISSUE TITLE
Semplificata.CessionarioCommittente.IdFiscaleIva va convalidato quando valorizzato

### ISSUE THREAD

**Issue by ZephirPFS47** [FatturaElettronica/FatturaElettronica.NET#242]
Il validatore non convalida correttamente la fattura semplificata se il committente è un privato, poichè non permette di esportare una fattura con idFiscaleIva vuoto, ma se inserisco IdFiscaleIva con IdentificativoIva pari al codice fiscale del committente il programma lo valida, ma lo SDI lo rifiuta.
![Cattura](https://user-images.githubusercontent.com/49749500/72915727-0c7e6500-3d41-11ea-8504-e10f60562f76.PNG)

Ho provato a modificare i validatori ma è  è troppo complicato per le mie conoscenze, @nicolaiarocci puoi gentilmente aiutarmi su questo?

**Comment by Balazar67** [comment]
Ho riscontrato lo stesso problema. Ci sono soluzioni previste?

**Comment by nicolaiarocci** [comment]
Vi riferite a 1.3.1.1 CessionarioCommittente.IdentificativiFiscali.IdFiscaleIVA, vero?

**Comment by nicolaiarocci** [comment]
Secondo la documentazione, IdFiscaleIVA può essere escluso se CodiceFiscale è impostato. Oppure, se presente assieme a CF i due valori devono essere coerenti.
![image](https://user-images.githubusercontent.com/512968/73752195-c4a80680-4760-11ea-98d4-45b4712f080b.png)
