### ISSUE TITLE
Nuovo tracciato Fattura Elettronica in arrivo

### ISSUE THREAD

**Issue by sgardini** [FatturaElettronica/FatturaElettronica.NET#243]
Evoluzione del tracciato xml della e-fattura con aggiunta di nuove tipologie di documento;
incremento degli specifici codici natura con maggiore dettaglio degli stessi;
introduzione di nuove tipologie di ritenute: queste le principali novità presentate nel corso dell’incontro del Forum italiano sulla fatturazione elettronica tenutosi la scorsa settimana,
completate dall’aumento sino a otto cifre della lunghezza del numero dei decimali per sconti e maggiorazioni, e dalla non obbligatorietà dell’indicazione dell’importo del bollo, eventualmente dovuto sulle fatture, in quanto di ammontare sempre pari a 2 euro.
Nello specifico, la pubblicazione del tracciato evoluto dovrebbe avvenire con provvedimento direttoriale da adottarsi probabilmente entro la fine di gennaio, con possibilità di iniziare a utilizzare facoltativamente i nuovi codici natura e le tipologie di documento dal 1° aprile 2020:
in altri termini, il Sistema di interscambio continuerà a considerare validamente formate e trasmesse,
con retrocompatibilità garantita dallo stesso SdI, le e-fatture che presentino ancora i codici natura generici N3 ed N6.
Dal 1° luglio 2020 SdI procederà invece allo scarto dei file che non dovessero presentare i codici natura N3 ed N6 in dettaglio. Al riguardo si segnala come nel corso del forum sia stata formulata la richiesta di una proroga di avvio di tale regola con decorrenza dell’obbligatorietà di utilizzo dal peri odo di imposta 2021.
Tipo documento
Ai codici sinora utilizzati per l’identificazione della tipologia di documento trasmesso al SdI, se ne aggiungono altri ai fini della corretta contabilizzazione degli stessi e della redazione della dichiarazione precompilata Iva.
Si tratta comunque di codici ad utilizzo non obbligatorio: avvalersene permette tuttavia, al di là di una più semplice rendicontazione nei sistemi gestionali, di evitare ad esempio di inviare l’esterometro per le fatture passive estere da integrare.
Più nello specifico, i nuovi codici TD13 e TD14 saranno utilizzabili per inviare a SdI i documenti di integrazione delle fatture nelle ipotesi di reverse charge intraUe ed interno. Con il TD15 ed il TD16 si potranno trasmettere le autofatture per autoconsumo e quelle per cessioni gratuite, mentre con i codici TD17 e TD18 si individueranno i documenti con cui si certifica l’estrazione dei beni da un deposito Iva con o senza versamento dell’imposta.
Infine con il TD19 si comunicheranno le cessioni di beni ammortizzabili e per passaggi interni ai sensi dell’articolo 20 del Dpr 633 del 1972.
Codice natura
L’utilizzo delle nuove codifiche per metterà di rappresentare del tracciato xml le casistiche di esenzione o non imponibilità, ad oggi non dettagliate, da utilizzare in contabilità per la successiva redazione delle dichiarazioni
compresa la precompilata Iva. L’evoluzione ha interessato il codice natura N3, che individua le operazioni non imponibili, ed il codice N6 per le inversioni contabili. Dal 1° luglio 2020, salvo proroghe - e in via sperimentale e volontaria dal 1° aprile 2020 - non potranno più essere inseriti tali codici generici ma occorrerà utilizzare quelli in dettaglio che vanno da N3.1. a N3.6 individuando, ad esempio, puntualmente le operazioni non imponibili derivanti da esportazioni o da cessioni intracomunitarie o verso San Marino. Analogamente il codice N6 dovrà essere dettagliato da N6.1 a N6.8 con sottocodici legati alle tipologie di operazioni soggette a inversione contabile quali le cessioni di rottami, di telefoni cellulari, le operazioni nel settore energetico.
Ritenute
Sono stati infine aggiunte nuove tipologie di ritenuta, con possibile ripetitività del blocco, quale il contributo Enasarco e quello Inps la cui gestione contabile è assimilabile, appunto, a quella delle ritenute, in questo modo superando di fatto i precedenti chiarimenti resi con Faq dalle Entrate.

**Comment by nicolaiarocci** [comment]
Aspettiamo la documentazione.

**Comment by nicolaiarocci** [comment]
vedi anche #231

**Comment by tanogae** [comment]
Ci siamo è arrivato il provvedimento dell' AdE

- [https://www.agenziaentrate.gov.it/portale/documents/20143/2368915/Provvedimento_28_02_2020_Fatturazione_Elettronica.pdf/d2f14943-7ac7-2c92-96d4-17f0a0988d64](url)

- [https://www.agenziaentrate.gov.it/portale/documents/20143/2368915/Allegato_Provvedimento_28_02_2020.pdf/37588a7f-cb88-2e6e-3303-442ea45ee301](url)

**Comment by sgardini** [comment]
Non trovo ancora però il file .xls con il tracciato tabellare.

**Comment by nicolaiarocci** [comment]
https://www.agenziaentrate.gov.it/portale/web/guest/specifiche-tecniche-versione-1.6

**Comment by nicolaiarocci** [comment]
ho cominciato il lavoro su branch `specifiche_v1.6`

**Comment by nicolaiarocci** [comment]
Se qualcuno rintraccia un esempio (possibilmente ufficiale) di fattura aderente alle specifiche v1.6, per favore lo posti qui.

**Comment by tanogae** [comment]
@nicolaiarocci questa nuova versione sarà in grado di deserializzare anche gli xml con versione 1.5?

**Comment by nicolaiarocci** [comment]
@tanogae i test attuali contengono i campioni 'storici' che vengono regolarmente de/serializzati, nessun problema per il momento.

**Comment by nicolaiarocci** [comment]
Rilasciata oggi la v3.0-beta.1 che offre supporto per le specifiche v1.6 pubblicate il 28 febbraio 2002 e utilizzabili a partire dal 4 maggio 2020. Il rilascio è al fine di consentirne l'uso di prova da parte di più persone possibili nel periodo (un mese e mezzo circa) che rimane fino alla entrata in vigore del nuovo formato.

Premesso che al momento non esiste un XML ufficiale di riferimento (v1.6), da evidenze tecniche e prove effettuate con fatture in versioni precedenti (serializzate con questa alpha, quindi presentate alla convalida su sito AdE), penso di poter affermare con "ragionevole" sicurezza che il nuovo formato è compatibile con i precedenti sia in serializzazione che de-serializzazione, cosa che dovrebbe facilitare la messa in prova/test/produzione di questa beta, che considero altrettanto "ragionevolmente" stabile.

Segnalare qui eventuali problemi.

**Comment by nicolaiarocci** [comment]
v3.0-beta.2 rilasciata su nuget, dovrebbe essere feature-complete.

**Comment by nicolaiarocci** [comment]
Un aggiornamento per chi sta seguendo:

1. La v3.0-beta.5 è su nuget
2. Posticipate le date di attivazione: https://www.agenziaentrate.gov.it/portale/documents/20143/2448766/Provvedimento-decorrenza-spec-tecn-provv.28.02.20.pdf/cfa70c9c-b521-c154-f4b4-56c1da361346
