### ISSUE TITLE
Validazione prezzo totale

### ISSUE THREAD

**Issue by fbua** [FatturaElettronica/FatturaElettronica.NET#25]
Nel caso di sconto o maggiorazione in cui sia inserito solo la percentuale e non l'importo la validazione causa  un'eccezione alla linea:
importo = importo.HasValue ? maggiorazione.Importo : null;
in quanto si tenta di accedere al valore  maggiorazione.Importo invece di usare l'importo calcolato in precedenza.

**Comment by nicolaiarocci** [comment]
Potresti fornire link alla linea incriminata? Grazie.

**Comment by fbua** [comment]
Vedi mio commento nella segnalazione #26
