### ISSUE TITLE
ImportoRitenuta e AliquotaRitenuta nullable

### ISSUE THREAD

**Issue by Artusoft** [FatturaElettronica/FatturaElettronica.NET#254]
Ciao, nel branch specifiche_1.6 c'è un motivo per cui hai lasciato questi due campi nullable?
Dalle specifiche del file Excel mi sembrano obbligatori nel caso ci sia il nodo.

**Comment by nicolaiarocci** [comment]
Grazie per la segnalazione. Mi sa che era un problema storico, credo fossero obbligatori anche nelle specifiche precedenti.. o ricordo male?
