### ISSUE TITLE
Calcolo importo per validazione prezzo totale da percentuale sconto maggiorazione

### ISSUE THREAD

**Issue by fbua** [FatturaElettronica/FatturaElettronica.NET#26]
Nel calcolo dell'importo a partire dalla percentuale quest'ultima non viene calcolata correttamente in quando andrebbe divisa per 100.

**Comment by nicolaiarocci** [comment]
Potresti fornire link al codice? Grazie.

**Comment by fbua** [comment]
Il metodo errato è il seguente in FatturaElettronica.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee
```C#
internal bool ValidateAgainstErr00423()
{
    decimal num3;
    decimal prezzoUnitario = this.PrezzoUnitario;
    foreach (ScontoMaggiorazione maggiorazione in this.ScontoMaggiorazione)
    {
        if (maggiorazione.Importo.HasValue || maggiorazione.Percentuale.HasValue)
        {
            decimal? importo = maggiorazione.Importo;
            num3 = new decimal();
            if (!((importo.GetValueOrDefault() > num3) ? importo.HasValue : false))
            {
                decimal num4 = prezzoUnitario;
                importo = num4 * maggiorazione.Percentuale;
                num3 = 100;
            }
            importo = importo.HasValue ? maggiorazione.Importo : null;
            decimal num2 = importo.Value;
            if (maggiorazione.Tipo == "SC")
            {
                prezzoUnitario -= num2;
            }
            else
            {
                prezzoUnitario += num2;
            }
        }
    }
    num3 = prezzoUnitario;
    decimal? quantita = this.Quantita;
    quantita = num3 * (quantita.HasValue ? this.Quantita : 1);
    return (this.PrezzoTotale == Math.Round(quantita.Value, 2));
}
```
L'errore comunque è presente con la versione disponibile su NuGet, quella scaricabile da GitHub sembra corretta.

L'unico suggerimento, sempre nello stesso metodo, in fase di confronto
```C#
PrezzoTotale == Math.Round((decimal)(prezzo * ((Quantita != null) ? Quantita : 1)), 2);
```
di arrotondare anche il campo PrezzoTotale su due cifre.

**Comment by sibylmichelangelotodaro** [comment]
Ciao, aggiungo che con la versione da NuGet ottengo questo errore:

L'oggetto nullable deve avere un valore.
System.Collections.ListDictionaryInternal

   in System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   in FatturaElettronica.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.ValidateAgainstErr00423()
   in BusinessObjects.Validators.DelegateValidator.Validate(BusinessObjectBase businessObject)
   in BusinessObjects.BusinessObjectBase.GetBrokenRules(String property)
   in BusinessObjects.BusinessObjectBase.get_Item(String propertyName)

Io sto provando ad utilizzare lo sconto indicando l'importo e non la percentuale, ovvero:

<DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <Descrizione>TUBI RITORNO GASOLIO</Descrizione>
        <Quantita>2.00</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>5.15</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Importo>-1.71</Importo>
        </ScontoMaggiorazione>
        <PrezzoTotale>6.86</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
</DettaglioLinee>


Grazie
Ciao

**Comment by nicolaiarocci** [comment]
@fbua potresti per cortesia confermarmi se il package nuget che stai usando è la v0.3.3 o una versione precedente? 

@sibylmichelangelotodaro potresti aprire un ticket diverso per favore? 

Grazie.

**Comment by fbua** [comment]
Sì ti confermo che la versione che usavo è la 0.3.3 l'ultima disponibile su NuGet

**Comment by nicolaiarocci** [comment]
è strano perché la 0.3.3 su nuget e quella su github dovrebbero essere allineate

**Comment by fbua** [comment]
Non saprei. 
Ieri per capire cosa accadeva ho decompilato tramite reflector la libreria e l'implementazione del metodo è quella che ho postato sopra.

**Comment by nicolaiarocci** [comment]
ah ecco perché non riconosco quel codice e non lo trovo nel repository :smile: Se guardi [il codice](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/FatturaElettronicaBody/DatiBeniServizi/DettaglioLinee.cs#L54) vedrai che la divisione per 100 viene fatta, ed è sempre stata fatta. 

Potresti provare la v0.3.4 attualmente su github e vedere se riscontri lo stesso problema?

**Comment by fbua** [comment]
Con la versione su github il problema sembra risolto. Purtroppo ho provato questa versione solo dopo inserito le due segnalazioni 😨.

Ora l'unica piccola correzione, come ti ho segnalato prima, è stata l'arrotondamento del campo  [PrezzoTotale](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/FatturaElettronicaBody/DatiBeniServizi/DettaglioLinee.cs#L70) perché nel mio caso c'era una problema con i decimali
