### ISSUE TITLE
Abilitare i controlli di validazione in maniera "selettiva"

### ISSUE THREAD

**Issue by santoror** [FatturaElettronica/FatturaElettronica.NET#262]
Utilizzando la versione 2.1.1 non riesco a validare alcune fatture scaricate dal cassetto fiscale.
La maggior parte degli errori che ricevo sono relativi ai cosidetti "**controlli aggiuntivi**" es:

`Percentuale e Importo non presenti a fronte di Tipo valorizzato`

Premettendo che non capisco come il cassetto fiscale possa avere al suo interno dei file (recenti) che violino le loro stesse regole, mi chiedevo se esiste attualmente un modo per "deregistrare" un eventuale validatore.

L'hack che sto utilizzando in questo preciso istante è basato sull'eliminazione dal ValidationResult degli errori relativi ai campi in oggetto es:
```
var validate = fattura.Validate().RemoveValidation()
-----

public static ValidationResult RemoveValidation(this ValidationResult result)
{
  return new ValidationResult(result.Errors.Where(failure => !failure.PropertyName == "property"));
}
```

**Comment by nicolaiarocci** [comment]
Ciao, i validatori sono disegnati come immutabili in maniera che siano thread-safe, per questo motivo la modifica a run-time non è supportata nè raccomandata (queste più o meno [le parole dell'autore](https://github.com/FluentValidation/FluentValidation/issues/713#issuecomment-370816782) di FluentValidation).

Se supportassimo i [RuleSet](https://docs.fluentvalidation.net/en/latest/rulesets.html) allora sarebbe possibile in qualche modo convalidarne solo alcuni, ma sarebbe comunque un bel po' di lavoro, sia per implementarli nella libreria che per poi usarli nell'applicativo. Al momento non penso ne valga la pena.
