### ISSUE TITLE
Gestione TD27

### ISSUE THREAD

**Issue by gabrielemilan** [FatturaElettronica/FatturaElettronica.NET#265]
Impostando il tipo documento TD27, non passa la validazione, mi da' questo errore:

{'Tipo Documento' valori accettati: TD01, TD02, TD03, TD04, TD05, TD06, TD20}

E' una feature già implementata?

**Comment by nicolaiarocci** [comment]
Sì con la versione 3.0 che era in beta ed è stata rilasciata in ver definitiva pochi minuti fa.
