### ISSUE TITLE
Evitare validazione nuovi codici di errore tracciato 1.6.1

### ISSUE THREAD

**Issue by Harl3** [FatturaElettronica/FatturaElettronica.NET#268]
come è possibile evitare di utilizzare i controlli del nuovo tracciato xml 1.6.1 fino all'entrata in vigore dello stesso? (dovrebbe essere 1 ottobre 2020).
Attualmente riceviamo errori 00444 nella validazione di un file xml, però lo SDI non effettuerà questi controlli fino appunto al 1 ottobre.

**Comment by nicolaiarocci** [comment]
Immagino siate sulla v3. Provate a tornare alla 2.x che è 'congelata' ai controlli SDI prima del 4 Maggio (poi posticipato al 1 Ottobre).

**Comment by Harl3** [comment]
è così, speravo ci fosse un modo di evitare di fare un rollback alla precedente versione
grazie mille
