### ISSUE TITLE
Validazione per errore 00444 dovrebbe tener conto dei valori null

### ISSUE THREAD

**Issue by Harl3** [FatturaElettronica/FatturaElettronica.NET#269]
https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/9b45f9e7b5ec19cd844b19f4d3ebc041f4706963/Validators/FatturaOrdinariaValidator.cs#L90
dovrebbe a mio avviso tener conto delle righe senza Natura IVA.
es:
Righe fattura
![image](https://user-images.githubusercontent.com/44983299/85535951-eec86b00-b612-11ea-848d-cc38de219580.png)
Riepilogo:
![image](https://user-images.githubusercontent.com/44983299/85536075-0dc6fd00-b613-11ea-96fd-ec054c193392.png)

a fronte di una situazione del genere, la validazione non dovrebbe dare errore in quanto il codice N1 è correttamente presente anche nel riepilogo, mentre ora restituisce false a causa dei valori null e ""

**Comment by nicolaiarocci** [comment]
Grazie, dovrebbe essere sistemato.
