### ISSUE TITLE
Errore validazione se Sconto valorizzato come Importo

### ISSUE THREAD

**Issue by sibylmichelangelotodaro** [FatturaElettronica/FatturaElettronica.NET#27]
Ciao, 

dopo aver modificato la valorizzazione dello sconto da percentuale a importo, la validazione solleva questo errore:

L'oggetto nullable deve avere un valore.
System.Collections.ListDictionaryInternal

   in System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   in FatturaElettronica.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.ValidateAgainstErr00423()
   in BusinessObjects.Validators.DelegateValidator.Validate(BusinessObjectBase businessObject)
   in BusinessObjects.BusinessObjectBase.GetBrokenRules(String property)
   in BusinessObjects.BusinessObjectBase.get_Item(String propertyName)

Un esempio di riga:

```
<DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <Descrizione>TUBI RITORNO GASOLIO</Descrizione>
        <Quantita>2.00</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>5.15</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Importo>-1.71</Importo>
        </ScontoMaggiorazione>
        <PrezzoTotale>6.86</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
</DettaglioLinee>
```

Riferimenti:

  <package id="BusinessObjects" version="0.1.5" targetFramework="net40" />
  <package id="FatturaElettronica" version="0.3.3" targetFramework="net40" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net40" />

Grazie
Ciao

**Comment by nicolaiarocci** [comment]
Risolto nella v0.3.4
