### ISSUE TITLE
Fluentvalidation v9

### ISSUE THREAD

**Issue by galloverde11** [FatturaElettronica/FatturaElettronica.NET#271]
Non so se è solo un problema mio, ma dopo aver aggiornato Fluentvalidation alla v9, alla riga 
`var validator = new FatturaOrdinariaValidator();` 

ricevo l'eccezione 

`Method not found: FluentValidation.IRuleBuilderOptions2<!!0,System.String> FluentValidation.DefaultValidatorExtensions.EmailAddress(FluentValidation.IRuleBuilder2<!!0,System.String>).` 

L'unica soluzione trovata è stata tornare a Fluentvalidation v8.6.2

**Comment by nicolaiarocci** [comment]
FluentValidation 9 ha rotto la compatibilità con la v8 ([link](https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html?highlight=DelegatingValidator#removal-of-other-deprecated-features))

**Comment by nicolaiarocci** [comment]
PS: FluentValidation 9 rilasciato solo ieri.

**Comment by galloverde11** [comment]
Ed oggi è già sistemato... Wow :)
