### ISSUE TITLE
Nuova validazione in v. 3.0.3 per numeri decimali

### ISSUE THREAD

**Issue by Elisa1508** [FatturaElettronica/FatturaElettronica.NET#277]
Ho riscontrato un problema nella validazione delle fatture con la nuova versione 3.0.3. Ad esempio con la validazione ottengo il seguente messaggio: "Importo totale documento potrebbe non avere più di 13 cifre in totale, con una tolleranza per 2 decimali. Sono stati trovate 3 cifre e 8 decimali.", ma il tag dell'importo è il seguente:

 <ImportoTotaleDocumento>549.00</ImportoTotaleDocumento>

Un messaggio analogo viene riportato per tutti gli importi, anche se questi sono nello stesso formato precedente.
Ho sbagliato qualcosa?

**Comment by nicolaiarocci** [comment]
@michaelmairegger can you please take a look at this ticket?

**Comment by michaelmairegger** [comment]
@nicolaiarocci si, certo

**Comment by michaelmairegger** [comment]
@Elisa1508 Sarebbe possibile aggiungere il file XML? Se possibile, può anche essere anonimizzato.

**Comment by Elisa1508** [comment]
[fattura.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/5266521/fattura.zip)
Allego, come richiesto il file xml a cui ho tolto i dati sensibili.

**Comment by michaelmairegger** [comment]
@Elisa1508 La creazione di uno unit test con questo file non causa errori di convalida.

    [TestMethod]
    public void Test()
    {
        var fattura = FatturaBase.CreateInstanceFromXml(File.OpenRead(@"........"));
        var validator = new FatturaOrdinariaValidator();
        var result = validator.Validate((FatturaOrdinaria)fattura);
        Assert.AreEqual(result.IsValid, true);
    }

**Comment by AlexBream** [comment]
> Ho riscontrato un problema nella validazione delle fatture con la nuova versione 3.0.3. Ad esempio con la validazione ottengo il seguente messaggio: "Importo totale documento potrebbe non avere più di 13 cifre in totale, con una tolleranza per 2 decimali. Sono stati trovate 3 cifre e 8 decimali.", ma il tag dell'importo è il seguente:
> 
> 549.00
> 
> Un messaggio analogo viene riportato per tutti gli importi, anche se questi sono nello stesso formato precedente.
> Ho sbagliato qualcosa?

Anche io ho lo stesso problema

**Comment by Elisa1508** [comment]
Il mio codice è il seguente:
FatturaOrdinaria fattura = CreaFattura(idFattura);
FluentValidation.Results.ValidationResult risultato = fattura.Validate();

**Comment by AlexBream** [comment]
Ciao a tutti, oggi ho trovato il tempo di fare qualche test con il sorgente e ho notato che nella v 3.0.3 sono state aggiunte le validazioni sui decimali, p.e. .ScalePrecision(2, 13). Attenzione che C# assegna una precisione di 4 decimali: un decimal 0,01M diventa in realtà 0,0100 di default; per risolvere è necessario forzare quando si assegna la variabile un Decmal.Round(d, 2).

per esempio: body.DatiGenerali.DatiGeneraliDocumento.ImportoTotaleDocumento = Decimal.Round(importoTotaleDocumento , 2);

Ciao e ancora complimenti per l'ottimo lavoro.

**Comment by AlexBream** [comment]
Ciao a tutti, oggi ho trovato il tempo di fare qualche test con il sorgente e ho notato che nella v 3.0.3 sono state aggiunte le validazioni sui decimali, p.e. .ScalePrecision(2, 13). Attenzione che C# assegna una precisione di 4 decimali: un decimal 0,01M diventa in realtà 0,0100 di default; per risolvere è necessario forzare quando si assegna la variabile un Decmal.Round(d, 2).

per esempio: body.DatiGenerali.DatiGeneraliDocumento.ImportoTotaleDocumento = Decimal.Round(importoTotaleDocumento , 2);

Ciao e ancora complimenti per l'ottimo lavoro.

**Comment by nicolaiarocci** [comment]
@Elisa1508 il suggerimento del buon @AlexBream (ciao!) ti è tornato utile?

**Comment by Elisa1508** [comment]
Scusate, ma ho avuto modo di fare le prove sono ora. Si, il suggerimento di @AlexBream è stato utile e ha risolto il problema.
