### ISSUE TITLE
Errore validazione se Sconto valorizzato come Percentuale

### ISSUE THREAD

**Issue by sibylmichelangelotodaro** [FatturaElettronica/FatturaElettronica.NET#28]
Ciao,

se provo a valorizzare lo sconto con la percentuale ottengo questo errore:

 in System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   in System.Nullable`1.get_Value()
   in FatturaElettronica.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.ValidateAgainstErr00423()
   in BusinessObjects.Validators.DelegateValidator.Validate(BusinessObjectBase businessObject)
   in BusinessObjects.BusinessObjectBase.GetBrokenRules(String property)
   in BusinessObjects.BusinessObjectBase.get_Item(String propertyName)
   in BusinessObjects.BusinessObjectBase.get_Error()
   in BusinessObjects.BusinessObjectBase.get_ChildrenErrors()
   in BusinessObjects.BusinessObjectBase.get_Error()
   in BusinessObjects.BusinessObjectBase.get_ChildrenErrors()
   in BusinessObjects.BusinessObjectBase.get_Error()
   in BusinessObjects.BusinessObjectBase.get_ChildrenErrors()
   in BusinessObjects.BusinessObjectBase.get_Error()
   in BusinessObjects.BusinessObjectBase.get_IsValid()

Questo problema è nato nelle ultime versioni. Sto rilevando il problema nella versione 0.3.4

Ecco un esempio di riga:

`<DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>POMPA GASOLIO REVISIONATA</Descrizione>
        <Quantita>1.00</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>650.00</PrezzoUnitario>
        <PrezzoTotale>650.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <Descrizione>TUBI RITORNO GASOLIO</Descrizione>
        <Quantita>2.00</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>5.15</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>33.42</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>6.86</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>3</NumeroLinea>
        <Descrizione>FILTRO GASOLIO</Descrizione>
        <Quantita>1.00</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>36.40</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>33.42</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>24.24</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>4</NumeroLinea>
        <Descrizione>KIT DISTRIBUZIONE</Descrizione>
        <Quantita>1.00</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>132.00</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>33.42</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>87.89</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>5</NumeroLinea>
        <Descrizione>MANODOPERA + PULIZIA SERBATOIO GASOLIO E CIRCUITO CARBURANTE</Descrizione>
        <Quantita>6.50</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>23.00</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>26.03</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>110.59</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>`

Grazie

Ciao

**Comment by nicolaiarocci** [comment]
Grazie per la segnalazione. Risolto nella 0.3.5.

**Comment by sibylmichelangelotodaro** [comment]
Grazie a te, attendo rilascio su nuget.

Ciao
