### ISSUE TITLE
Errore caricamento FluentValidation.dll in v3.0.3

### ISSUE THREAD

**Issue by LightAndrek** [FatturaElettronica/FatturaElettronica.NET#280]
Dopo l'aggiornamento alla versione 3.0.3 la nostra applicazione si blocca quando tenta di caricare l'assembly FluentValidation.
Nelle dipendenze nuget viene specificato che la versione di FluentValidation necessaria è 9.0.0 (non più presente su nuget) o maggiore (attualmente abbiamo installato la 9.2.2), ma quando tenta di caricare l'assembly in questione a runtime, la firma richiede la versione 8.0.0.
Ovviamente lato nostro potremmo risolvere modificando il file app.config inserendo dei BindingRedirect, ma la struttura della nostra applicazione non ci consente di apportare tale modifica.
Sarebbe possibile rilasciare un aggiornamento (ipotetico 3.0.4) che come dipendenza richieda l'ultima versione di FluentValidation?

**Comment by nicolaiarocci** [comment]
Ciao, grazie per la segnalazione. Verifica di non avere ancora una dipendenza da FatturaElettronica.Extensions. Ora è incorporato in FE 3.0.3.
