### ISSUE TITLE
Errore nella valdazione della Fattura Ordinaria

### ISSUE THREAD

**Issue by exolabsrl** [FatturaElettronica/FatturaElettronica.NET#281]
Il sistema di validazione non segnala l'errore 0443 per una fattura ordinaria che presenta una riga di dettaglio con natura N1 e 2 righe di riepilogo, una relativa alla natura N1 ed una senza natura con aliquota iva al 22% ed importi a 0.00.

```
[...]
<DatiBeniServizi>
<DettaglioLinee>
  <NumeroLinea>1</NumeroLinea>
  <Descrizione>SPEDIZIONI POSTA PRIORITARIA FINO A 50 GR.</Descrizione>
  <Quantita>5.00</Quantita>
  <UnitaMisura>1</UnitaMisura>
  <DataInizioPeriodo>2020-09-01</DataInizioPeriodo>
  <DataFinePeriodo>2020-09-30</DataFinePeriodo>
  <PrezzoUnitario>1.95</PrezzoUnitario>
  <PrezzoTotale>9.75</PrezzoTotale>
  <AliquotaIVA>0.00</AliquotaIVA>
  <Natura>N1</Natura>
</DettaglioLinee>
<DatiRiepilogo>
  <AliquotaIVA>22.00</AliquotaIVA>
  <ImponibileImporto>0.00</ImponibileImporto>
  <Imposta>0.00</Imposta>
</DatiRiepilogo>
<DatiRiepilogo>
  <AliquotaIVA>0.00</AliquotaIVA>
  <Natura>N1</Natura>
  <ImponibileImporto>9.75</ImponibileImporto>
  <Imposta>0.00</Imposta>
</DatiRiepilogo>
</DatiBeniServizi>
[...]
```

Inviando la fattura allo sdi, ho ricevuto l'errore 0443.

**Comment by nicolaiarocci** [comment]
@exolabsrl potrebbe essere lo stesso caso di #284 ?

**Comment by exolabsrl** [comment]
@nicolaiarocci no, si tratta di un altro caso; il #284 prevede la valorizzazione di un altro campo della fattura.
Il mio caso si riferisce al fatto che per ogni tipologia di natura o valore di aliquota Iva nelle righe di dettaglio deve avere una corrispondenza nelle righe di riepilogo.
ho effettuato la correzione su una copia del progetto ma essendo poco pratico di GitHub l'ho tenuta in locale.
Se mi dai indicazioni la condivido volentieri
grazie.

**Comment by nicolaiarocci** [comment]
Certo, dammi un link e ci penso io

**Comment by nicolaiarocci** [comment]
A una rapida occhiata mi pare che il codice di convalida ci sia ([link](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/Validators/FatturaOrdinariaValidator.cs#L31))

**Comment by nicolaiarocci** [comment]
Epperò, in effetti, il blocco linkato qui sopra fa un controllo diverso da quello che indichi tu. Qui controlliamo che tutte le aliquote delle righe di dettaglio abbiano una corrispondenza nei dati di riepilogo.  Dal tuo esempio, bisognerebbe invece controllare che tutte le righe dei dati di riepilogo siano presenti in quelle di dettaglio.

Questa sembra anche essere l'indicazione che viene da SDI:
![image](https://user-images.githubusercontent.com/512968/97319496-3c790c80-186d-11eb-9a10-528b4dbe4725.png)

**Comment by nicolaiarocci** [comment]
Interpreto che entrambi i controlli sono necessari: ogni aliquota delle righe di dettaglio deve essere in dati riepilogo; ma allo stesso tempo dati di riepilogo non deve contenere aliquote assenti nel documento (righe).

**Comment by nicolaiarocci** [comment]
Dovrebbe essere a posto. Se hai modo di controllare prima della release, mi faresti un favore.
