### ISSUE TITLE
Natura e Riferimento normativo

### ISSUE THREAD

**Issue by Elisa1508** [FatturaElettronica/FatturaElettronica.NET#284]
Se un elemento dei dati di riepilogo indica una natura di esenzione, da specifiche sarebbe obbligatorio indicare il riferimento normativo, ma la validazione non rileva il problema. 
Sarebbe possibile aggiungere questa verifica?

Ad esempio con l'elemento seguente bisognerebbe indicare che l'elemento "<riferimentonormativo>" non è presente.
<DatiRiepilogo>
  <AliquotaIVA>0.00</AliquotaIVA>
  <Natura>N1</Natura>
  <ImponibileImporto>9.75</ImponibileImporto>
  <Imposta>0.00</Imposta>
</DatiRiepilogo>

**Comment by nicolaiarocci** [comment]
Ciao Elisa, grazie per la segnalazione. Che errore di convalida viene restituito da SDI?

**Comment by nicolaiarocci** [comment]
Lo chiedo perchè nella documentazione non ne viene indicato alcuno

**Comment by nicolaiarocci** [comment]
![image](https://user-images.githubusercontent.com/512968/97204073-ec8b3e80-17b5-11eb-9c34-3776b0a7c36e.png)

o meglio, viene indicato che è obbligatorio, ma poi nell'elenco errori (che di solito recupero dal xls col tracciato) non ne viene riportato alcuno

**Comment by Elisa1508** [comment]
Non ho provato l'invio, sto aggiornando il nostro software e i nostri clienti usano piuttosto di frequente i codici natura (soprattutto i codici N6.x) quindi facendo le verifiche per l'aggiornamento ho notato la fattura viene comunque validata.

Se può essere utile, ho scaricato il progetto e ho aggiunto la regola di validazione:
File DatiRiepilogoValidator.cs: 

            RuleFor(x => x.RiferimentoNormativo)
                .Must(riferimento => string.IsNullOrEmpty(riferimento))
                .When(x => !string.IsNullOrEmpty(x.Natura))
                .WithMessage("Riferimento normativo non presente a fronte di Natura indicata");

Da prove interne con questa regola la validazione fallisce quando occorre.

**Comment by sevenmay** [comment]
E' possibile by-passare questo controllo, visto che non viene "ufficialmente" fatto dallo SDI?

Grazie.

**Comment by artmedia** [comment]
> E' possibile by-passare questo controllo, visto che non viene "ufficialmente" fatto dallo SDI?
> Grazie.

+1

**Comment by nicolaiarocci** [comment]
Se non viene fatto da SDI, allora è stat un errore (mio) includerlo. Mi confermato che SDI non convalida questo 'errore'?

**Comment by sevenmay** [comment]
Se guardi qui [https://www.fatturapa.gov.it/export/documenti/fatturapa/v1.3/Rappresentazione-tabellare-fattura-ordinaria.pdf](url), non viene specificato nessun "controllo extra schema".

E nello schema:

```
<xs:complexType name="DatiRiepilogoType">
  <xs:sequence>
    ...
    <xs:element name="RiferimentoNormativo" type="String100LatinType" minOccurs="0"/>
  </xs:sequence>
</xs:complexType>
```

Non c'è menzione neanche nei controlli dello SDI: [https://www.fatturapa.gov.it/export/documenti/Elenco-Controlli-versione-1.7.pdf](https://www.fatturapa.gov.it/export/documenti/Elenco-Controlli-versione-1.7.pdf).

In questo momento non posso provare sullo SDI, ma tutte le fatture inviate fino ad ora senza quel campo sono passate, e la nota di obbligatorietà riportata nel primo messaggio era presente anche nelle prime specifiche.

Visto che lo SDI non effettua il controllo non si possono obbligare gli utenti a valorizzarlo.

Per completezza, gli esperti di fiscalità lo vorrebbero obbligatorio: [https://www.ilsole24ore.com/art/riferimento-normativo-obbligatorio-AEebQpkG](https://www.ilsole24ore.com/art/riferimento-normativo-obbligatorio-AEebQpkG).

**Comment by stefanoricci** [comment]
> Visto che lo SDI non effettua il controllo non si possono obbligare gli utenti a valorizzarlo.

Concordo!

**Comment by nicolaiarocci** [comment]
Ok ragazzi ho rimosso questa convalida alla luce della mancata segnalazione da parte di SDI.
