### ISSUE TITLE
Fatturazione Elettronica specifiche 1.6

### ISSUE THREAD

**Issue by Kratos-95** [FatturaElettronica/FatturaElettronica.NET#285]
Salve,
ho installato la versione 3.0.3 di FatturaElettronica ed ho provato a fare un test con alcuni XML nel nuovo formato. Se provo ad utilizzare qualche nuovo codice ministeriale (tipo TD24; N3.1, ecc...) la validazione non fa passare la fattura. La cosa strana è che il messaggio di errore restituito non contempla nei valori accettati ANCHE i nuovi codici (ad esempio le nature iva possibili sono rimaste N1,....,N7).
Se può servire ho aggiornato dalla versione 2.1.1 alla 3.0.3, senza però aver modificato il codice che si occupa di validare la fattura.

Grazie mille

**Comment by nicolaiarocci** [comment]
Ciao. Se stai usando la versione 3.x dovresti avere tutte le nuove convalide. Verifica di non avere ancora v2.x nei riferimenti al progetto. Per completezza, v3 ha incorportato Extensions quindi se l'hai, va tolto.

**Comment by Kratos-95** [comment]
Credo fosse un problema di Visual Studio, risolto, Grazie
