### ISSUE TITLE
Errore validazione caratteri speciali IsBasicLatin e IsLatin-1Supplement

### ISSUE THREAD

**Issue by fabiocalvigioni** [FatturaElettronica/FatturaElettronica.NET#29]
Come da specifiche XSD FatturaPa 1.2, non vengono validati i tipi string che richiedono una validazione del set di caratteri UNICODE `IsBasicLatin` (per esempio `String60Type`del campo `NumeroIscrizioneAlbo`) e `IsLatin-1Supplement` (per esempio `String80LatinType` del campo `Anagrafica.Denominazione`).

Per esempio, una Denominazione contenente il carattere `›` risulta valida ma viene rifiutata dal Sistema di Interscambio.

Cfr MSDN Classi di caratteri nelle espressioni regolari
https://msdn.microsoft.com/it-it/library/20bw873z(v=vs.110).aspx#Blocchi denominati supportati

**Comment by fabiocalvigioni** [comment]
Ho abbozzato una soluzione aggiungendo un `FCharsetValidator.cs`:

```
using BusinessObjects.Validators;

namespace FatturaElettronicaPA.Validators
{
    /// <summary>
    /// Validates that a string conforms to a specified Unicode characters set.
    /// </summary>
    public class FCharsetValidator : RegexValidator
    {
        private static string _brokenDescription = "Stringa contenente caratteri non validi";
        public enum Charsets { BasicLatin, Latin1Supplement };
        
        /// <summary>
        /// Constructor.
        /// </summary>
        public FCharsetValidator(string propertyName, Charsets charset) : base(propertyName, _brokenDescription, null)
        {
            switch (charset)
            {
                case Charsets.BasicLatin:
                    Regex = @"^[\p{IsBasicLatin}]+$";
                    _brokenDescription += " (Unicode Basic Latin)";
                    break;

                case Charsets.Latin1Supplement:
                    Regex = @"^[\p{IsBasicLatin}\p{IsLatin-1Supplement}]+$";
                    _brokenDescription += " (Unicode Latin-1 Supplement)";
                    break;
            }
        }
    }
}
```

che poi va aggiunto a tutte le stringhe da validare, ad esempio per la Denominazione:
```
Add(new FLengthValidator("Denominazione", 1, 80));
Add(new FCharsetValidator("Denominazione", FCharsetValidator.Charsets.Latin1Supplement));
```

Miglioramenti o suggerimenti sono benvenuti :)

**Comment by nicolaiarocci** [comment]
Niente male. Come forse saprai sto lavorando a un completo rewrite/refactoring delle convalide. Ti chiederei di aspettarne il completamento per poi proporre una PR che risolva questo ticket (o potrò farlo io eventualmente). Puoi seguire il lavoro sulla branch [nuovi pattern di convalida](https://github.com/FatturaElettronica/FatturaElettronica.NET/tree/nuovo_pattern_di_convalida). Manca ancora la documentazione e c'è sia codice nuovo che quello ormai obsoleto... quindi è un po' un cantiere aperto. Oltre 300 test sono già presenti comunque, e non sono lontano dalle rifiniture che potranno avvenire se tutto va bene tra una o due settimane.

**Comment by nicolaiarocci** [comment]
La v0.4 è stata rilasciata con il nuovo sistema di convalida. Se vuoi proporre una PR è il momento giusto :)

**Comment by fabiocalvigioni** [comment]
Ci avevo dato un'occhiata ma purtroppo in ufficio siamo fermi al framework 4.0 (Visual Studio 2010) e quindi al momento non possiamo passare alla nuova release :(
Non so quando riusciremo a fare l'upgrade al 4.5!
