### ISSUE TITLE
Errore convalida 00444 nel caso di fatture con iva pari a zero

### ISSUE THREAD

**Issue by scuderip** [FatturaElettronica/FatturaElettronica.NET#292]
Nel caso di fatture che contengono un totale imponibile minore o uguale a 2 centesimi, per il quale il totale IVA al 22% è pari a zero, la convalida restituisce il suddetto errore, anche se non è indicata nessuna natura di esenzione (in quanto l'imponibile è assoggettato al 22%).
In realtà, con le versioni precedenti questo errore non veniva segnalato e la fattura viene regolarmente accettada da SDI
Versione testata la 3.0.4

**Comment by nicolaiarocci** [comment]
Grazie per la segnalazione. Attualmente nella convalida 00444 non vengono presi in considerazione i valori iva nè tantomeno gli imponibili. Potresti fornirmi un esempio di fattura che genera il problema così posso approfondire?

**Comment by scuderip** [comment]
Ho verificato meglio e in effetti il problema è nel momento in cui nella sezione DatiRiepilogo la natura è impostata a blank.
Impostando la natura a nothing  (o null in c#) la convalida passa regolarmente.

Se genero il file XML e poi carico il file XML il problema non si presenta, in quanto, nel caso in cui il campo Natura è blank nell'XML viene omesso e nella successiva importazione viene automaticamente impostato a null

**Comment by nicolaiarocci** [comment]
Possiamo chiudere questo ticket?

**Comment by scuderip** [comment]
Certo, grazie
