### ISSUE TITLE
Errore SistemaEmittente aggiunto in serializzazione come Nodo XML (oltre che come attributo)

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#294]
Con la versione attualmente in commit l'attributo SistemaEmittente, oltre ad essere serializzato (correttamente) nel nodo Root ... viene anche serializzato come Nodo XML facendo fallire la validazione tramite XSD (Specifiche 1.6).
Riporto di seguito il frammento di codice per riprodurre l'errore:

`FatturaElettronica.Ordinaria.FatturaOrdinaria f = FatturaElettronica.Ordinaria.FatturaOrdinaria.CreateInstance(FatturaElettronica.Defaults.Instance.Privati);
            f.FatturaElettronicaBody.Add(new FatturaElettronica.Ordinaria.FatturaElettronicaBody.FatturaElettronicaBody());
            f.FatturaElettronicaBody[0].DatiGenerali.DatiGeneraliDocumento.TipoDocumento = "TD20";
            f.SistemaEmittente = "SE";
            f.WriteXml("d:\\fattura1.xml");`

L'xml generato risulta:
`<?xml version="1.0" encoding="utf-8"?>
<p:FatturaElettronica versione="FPR12" SistemaEmittente="SE" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 https://www.fatturapa.gov.it/export/documenti/fatturapa/v1.2.1/Schema_del_file_xml_FatturaPA_versione_1.2.1a.xsd" xmlns:p="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2">
  <FatturaElettronicaHeader>
    <DatiTrasmissione>
      <FormatoTrasmissione>FPR12</FormatoTrasmissione>
      <CodiceDestinatario>0000000</CodiceDestinatario>
    </DatiTrasmissione>
  </FatturaElettronicaHeader>
  <FatturaElettronicaBody>
    <DatiGenerali>
      <DatiGeneraliDocumento>
        <TipoDocumento>TD20</TipoDocumento>
        <Data>0001-01-01</Data>
      </DatiGeneraliDocumento>
    </DatiGenerali>
  </FatturaElettronicaBody>
 <SistemaEmittente>SE</SistemaEmittente>
</p:FatturaElettronica>`

Grazie in anticipo.

**Comment by nicolaiarocci** [comment]
Ciao, grazie per la segnalazione. 

Ora dovrebbe essere risolto. Se ti è possiible, per cortesia verifica direttamente dalla versione su master.

**Comment by aferende** [comment]
Buonasera Nicola, confermo la risoluzione del bug (grazie per l'intervento tempestivo).
Hai già in programma (e se si quando) un rilascio della nuova 3.0.5 su NuGet?

PS: Vado per un attimo off-topic per portare alla tua attenzione (ma sicuramente lo saprai) che FluentValidation dalla ver.9.0.0.0 in su non supporta più ASP.NET MVC.
Per adesso sto resistendo con un wrapper FluentValidation for MVC ma il quale anch'esso si è definitivamente fermato alla ver 9.0.0.0. Morale ... ulteriori aggiornamenti in FatturaElettronica.NET del componente FluentValidation renderanno di fatto impossibile utilizzare Fattura Elettronica .NET in qualunque progetto ASP.NET MVC (purtroppo ancora non siamo nelle condizione di poter passare a .NET Core).
Ogni suggerimento è ben accetto.
Ancora grazie,
Andrea.

**Comment by nicolaiarocci** [comment]
Ciao Adrea, FE supporta FluentValidation 9 dalla 3.0.2. Per quanto riguarda MVC5, era deprecato già dalla v8. C'è poco da fare mi sa. Il wrapper è una buona idea finchè non potete fare transizione a NET5, eventualmente anche custom made. Buona fortuna.

**Comment by aferende** [comment]
Ti ringrazio Nicola

**Comment by nicolaiarocci** [comment]
v3.0.5 è su nuget, in attesa di indicizzazione (dagli qualche minuto)
