### ISSUE TITLE
Problema errore 00444 con fattura semplicissima sola IVA 22%

### ISSUE THREAD

**Issue by MarcelloBiglioli** [FatturaElettronica/FatturaElettronica.NET#296]
Buongiorno.
Ho usato il progetto di fattura elettronica per sviluppare l'emissione fatture in XML e recentemente ho aggiornato all'ultima versione.
Va tutto benissimo in caso di fatture con natura anche "nuova", ma mi da un errore in caso tutte le righe della fattura siano imponibili (22%).
Allego un esempio di file generato (con in testa l'errore raccolto dal programma)
Grazie per l'attenzione.

[FT51754.ERR.txt](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/5603662/FT51754.ERR.txt)

**Comment by nicolaiarocci** [comment]
Ciao, hai già dato occhiata al ticket #292? Mi sembra simile.

**Comment by MarcelloBiglioli** [comment]
Grazie.
Avevo visto quel ticket, ma mi pare completamente diverso, o non ho capito io! In nessuna parte del file xml è presente il tag <Natura>, per cui il controllo mi pare sia assolutamente errato (dovrebbe scattare solo in caso di righe senza imposta, o sbaglio?).
Non ho ancora provato a togliere la parte di errore, e ad inoltrare lo stesso il file, perché vorrei comunque risolvere il problema altrimenti continuerà a presentarsi anche in seguito! 
Allego un file più semplice, una sola riga e senza allegati, che mostra esattamente lo stesso problema.
[FT45178.ERR.txt](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/5606872/FT45178.ERR.txt)

**Comment by nicolaiarocci** [comment]
Perfetto grazie.

**Comment by nicolaiarocci** [comment]
Ciao, questo test passa senza problemi prendendo i dati dal tuo XML:

```cs
        [TestMethod]
        public void Issue296()
        {
            var body = new FatturaElettronicaBody();
            body.DatiBeniServizi.DettaglioLinee.Add(new DettaglioLinee
            {
                PrezzoUnitario = 2000.0m, Quantita = 1, AliquotaIVA = 22.0m
            });
            body.DatiBeniServizi.DatiRiepilogo.Add(new DatiRiepilogo
            {
                ImponibileImporto = 2000.0m, AliquotaIVA = 22.0m
            });
            Challenge.FatturaElettronicaBody.Add(body);

            var result = Validator.Validate(Challenge);

            Assert.IsNull(result.Errors.FirstOrDefault(x => x.ErrorCode == "00444"));
```

Sicuro che in `DatiRiepilogo` o in `DettaglioLinee` non ci sia una `Natura` impostata a `string.Empty()`, come segnalato in #292?

**Comment by nicolaiarocci** [comment]
PS: si può migliorare la convalida per gestire anche il caso di impostazione a stringa vuota (come probabilmente era anche prima dell'ultima versione - ma non aveva influenza); ma vorrei prima avere conferma che questo sia il problema.

**Comment by MarcelloBiglioli** [comment]
Intendi negli oggetti della FE da cui poi serializzo?
Provo a controllare (probabilmente lunedì mattina) e ti dico.
Intanto GRAZIE!

**Comment by MarcelloBiglioli** [comment]
Esatto, era proprio quello.
Nelle versioni precedenti non capitava (nonostante io mettessi comunque blank la natura) ed ora si.
Secondo me se modifichi il controllo per escludere anche questo caso è meglio, ma per i miei scopi ora va bene.
Grazie e scusa per l'aggravio di lavoro.
