### ISSUE TITLE
Validazione Mancante per Codice Destinatario

### ISSUE THREAD

**Issue by Balrog994** [FatturaElettronica/FatturaElettronica.NET#300]
Salve,

durante l'utilizzo della libreria abbiamo notato (a causa di un bug nel nostro software) che manca una validazione per il codice destinatario.

La condizione è la seguente:
- Se il codice paese dell'IdFiscaleIva del Cessionario Committente è "IT"
- Non deve essere possibile valorizzare il Codice Destinatario a XXXXXXX (perchè quel valore è destinato soltanto ai clienti esteri)

Grazie

**Comment by nicolaiarocci** [comment]
Ciao, grazie per la segnalazione. In effetti gli errori 3xx la libreria non li convalida. La scelta a suo è stata fatta perchè le convalide erano difficile da fare offline (esempio: Partita IVA esistente in anagrafe partite IVA). Nel frattempo hanno aggiunti alcuni controlli risolvibili anche localmente, tra cui il 00313. Da valutare se vale la pena aggiungerli alla libreria. Opinioni?

**Comment by nicolaiarocci** [comment]
PS: il problema è che non si riuscirà mai a coprire tutta la serie. Al momento per esempio sono probabilmente implementabili offline solo 313 e 330 (e quest'ultimo è praticamente impossibile da allineare a quello PA non sapendo come convalidano l'indirizzo mail: regex? quale?). Sono orientato a lasciare la serie 300 scoperta.
