### ISSUE TITLE
Errata serializzazione DatiTrasmittente

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#301]
Buonasera Nicola,
segnalo un errato ordine di serializzazione dei nodi all'interno della sezione <DatiTrasmittente>.

In particolare, se vengono valorizzati i campi del Nodo ContattiTrasmittente e PECDestinatario, fattura elettronica.net produce un risultato simile a quello qui di seguito e facendo fallire la validazione secondo lo schema XSD dello SDI.

<DatiTrasmissione>
  <IdTrasmittente>
	<IdPaese>IT</IdPaese>
	<IdCodice>12345678901</IdCodice>
  </IdTrasmittente>
  <ProgressivoInvio>1</ProgressivoInvio>
  <FormatoTrasmissione>FPR12</FormatoTrasmissione>
  <CodiceDestinatario>0000000</CodiceDestinatario>
  <ContattiTrasmittente>
	<Telefono>12345677</Telefono>
	<Email>email@email.it</Email>
  </ContattiTrasmittente>
  <PECDestinatario>pec@pec.it</PECDestinatario>
</DatiTrasmissione>

Stando alle specifiche SDI i ContattiTrasmittente, se presenti, devono essere inseriti come ultimo nodo. In questo caso invece sono prima del nodo PECDestinatario.

Grazie in anticipo per il tuo lavoro.
Andrea.

**Comment by nicolaiarocci** [comment]
Ciao Andrea, a un rapido controllo direi che ContattiTrasmittente viene prima di PECDestinatario:

![image](https://user-images.githubusercontent.com/512968/101809518-f1af0d80-3b17-11eb-8fba-b110eeac0d2b.png)

e anche:

![image](https://user-images.githubusercontent.com/512968/101809583-04c1dd80-3b18-11eb-82ac-e1017b0a6dc7.png)

**Comment by aferende** [comment]
Buonasera Nicola,
grazie per la pronta risposta.
Hai perfettamente ragione, l'errore era mio. Chiudo il bug.
Grazie ancora.
