### ISSUE TITLE
Versioni

### ISSUE THREAD

**Issue by ds-genux** [FatturaElettronica/FatturaElettronica.NET#302]
Nel xml risultante il ramo "FormatoTrasmissione" e l'attributo "versione" del ramo "FatturaElettronica" restano valorizzati a FPR12 anche se siamo alla versione 1.6? 
Così anche per gli attributi "xsi:schemaLocation" e "xmlns:p" resta nell'url il riferimento alla versione "v1.2" anche se siamo alla 1.6?
Grazie

**Comment by username77** [comment]
usa questo:
https://github.com/username77/FatturaElettronica.NET/blob/master/Defaults.cs

e lo chiami prima di salvare l'xml:

      RootElement.Prefix = "ns3";

                    RootElement.ExtraAttributes = new RootElement.XmlAttributeString[]
                    {
                    new XmlAttributeString { Prefix="xmlns", LocalName="ns2", ns=null, value="http://www.w3.org/2000/09/xmldsig#"},
                    new XmlAttributeString { Prefix="xmlns", LocalName="ns3", ns=null, value="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2"}
                    };

                    

                    using (var w = XmlWriter.Create(xmlName, writerSettings))
                    {
                        fattura.WriteXml(w);
                    }

**Comment by nicolaiarocci** [comment]
FormatoTrasmissioni deve essere 1.2 da specifiche tecniche, anche quelle più recenti. Vedi anche https://www.agenziaentrate.gov.it/portale/documents/20143/2931841/Schema_VFPR12.xsd/1b8bf833-ff5c-7670-7e33-684a014d3cce
