### ISSUE TITLE
lettura dinamica versione xml in json

### ISSUE THREAD

**Issue by dinf** [FatturaElettronica/FatturaElettronica.NET#308]
Ciao, utilizzo la tua libreria per la lettura delle fatture in xml. 
Adesso ho un errore durante la serializzazione in json del file xml perchè dopo l'aggiornamento della libreria si aspetta sempre il nuovo formato (con una lista di DatiRitenuta) mentre il file xml mantiene ancora la vecchia versione( singolo oggetto DatiRitenuta).
Ti volevo chiedere se è possibile discriminare la serializzazione in json secondo un parametro o se sbaglio io la procedura.
Complimenti per il lavoro fatto

**Comment by nicolaiarocci** [comment]
Se mi puoi fornire un esempio di fattura che non ti viene serializzata (dati fittizzi), posso guardarci.

**Comment by reiterasrls** [comment]
Succede che abbiamo da importare dei file xml vecchio formato ossia con oggetto singolo DatiRitenuta.
Ho 2 casi di cui uno sono certo e l'altro lo chiedo a te.
1 CASO
- Se lancio il read sulla nuova classe FatturaOrdinaria la deserializzazione andrà in errore o metterà l'oggetto DatiRitenuta come primo elemento dell'array del nuovo formato?
2 CASO
Ho serializzato il tuo oggetto FatturaOrdinaria vecchia versione dentro un database. Adesso avendo aggioranto la libreria la deserializzazione mi va giustamente in errore.
Ci sarebbe la possibilità dentro la libreria di mantene i 2 formati e tramite provider con discrimintatore automatizzare la deserializzazione?
Esempio...classe FatturaOrdinariaV1 FatturaOrdinariaV2 e tramite FatturaOrdinariaFactory.Read(versione) leggere un formato anzichè l'altro con l'obiettivo finale di poterlo fare automaticamente leggendo da xml.

**Comment by nicolaiarocci** [comment]
Ma quale versione di FE stai usando? I test deserializzano correttamente XML con un solo elemento (in XML non esiste concetto di 'array', semplicemente ripeti più volte lo stesso elemento)

![image](https://user-images.githubusercontent.com/512968/103905522-0246a980-50ff-11eb-9eba-676136f5c9a0.png)

**Comment by reiterasrls** [comment]
scusami mi sono spiegato male.
Ho scaricato un fattura xml con la vecchia libreria e serializzato su db l'oogetto FatturaOrdinaria che contente l'oggetto DatiRitenuta.
dopo aver aggiornato la libreria la classe   FatturaOrdinaria ha un array di DatiRitenuta quindi non posso più recuperarla dal db perchè va in errore.
Da qui la mia domanda...sarebbe possibile mantenere nella libreria la classe vecchio modello e la classe nuovo modello in modo tale da decidere se leggere da una createinstrance o quello che sia 2 formati differenti?
spero di essere stato chiaro

**Comment by nicolaiarocci** [comment]
quindi hai serializzato su db non un JSON o XML creato dalla libreria?

**Comment by reiterasrls** [comment]
esatto. letto xml dalla tua libreria e creato l'oggetto fatturaordinaria..serializzato su db nosql mongodb

**Comment by nicolaiarocci** [comment]
non è previsto di supportare entrambe le versioni delle specifiche in FE 3.x mi dispiace.
