### ISSUE TITLE
Validazione CAP

### ISSUE THREAD

**Issue by AlexBream** [FatturaElettronica/FatturaElettronica.NET#310]
Ciao,
oggi ho ricevuto uno scarto per un CAP non valido (fattura estera): non è il caso di inserire un validator per il CAP che controlli che siano solo valori numerici?

    <ListaErrori>
        <Errore>
            <Codice>00200</Codice>
            <Descrizione>File non conforme al formato : The value 'G782J' of element 'CAP' is not valid.
riga: 1 - colonna: 1654</Descrizione>
            <Suggerimento>Verificare che i campi contenuti nel file inviato rispettino caratteristiche formali e ordine di rappresentazione previsti dal tracciato fattura</Suggerimento>
        </Errore>
    </ListaErrori>

**Comment by nicolaiarocci** [comment]
Ciao Alessandro, il `CAPType` ufficiale non riporta una regola 'soli valori numerici':

```
  <xs:simpleType name="CAPType">
    <xs:restriction base="xs:normalizedString">
      <xs:pattern value="(\p{IsBasicLatin}{1,5})" />
    </xs:restriction>
  </xs:simpleType>
```

Nella documentazione ufficiale non trovo altri riferimenti.

**Comment by AlexBream** [comment]
Ciao Nicola, nello schema rilasciato a novembre https://www.agenziaentrate.gov.it/portale/documents/20143/2931841/Schema_VFPR12.xsd
è

  <xs:simpleType name="CAPType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9][0-9][0-9][0-9][0-9]" />
    </xs:restriction>
  </xs:simpleType>

**Comment by nicolaiarocci** [comment]
I stand corrected ;-)
