### ISSUE TITLE
Errore di validazione: Unita Misura deve essere lungo tra i 1 e 10 caratteri

### ISSUE THREAD

**Issue by albertocolombo73** [FatturaElettronica/FatturaElettronica.NET#311]
Ciao Nicola,

innanzitutto grazie per aver condiviso il tuo lavoro. Utilizzo la tua libreria ver. 3.1.0 rilasciata il 30/12/2020 per l'esportazione/importazione in xml da e verso nostro DB.
Perdonami se magari ripropongo un vecchio quesito ma ho notato (forse) un'anomalia nella validazione del file xml in particolare del tag unità di misura.

Come da specifiche l'unità di misura (ID nodo 2.2.1.6) non è obbligatoria, purtuttavia quando valido il file xml senza completare il tag <UnitaMisura> mi viene generato l'errore seguente:
'Unita Misura' deve essere lungo tra i 1 e 10 caratteri.

Questo è il dettaglio della linea dove risulta evidente la mancanza del tag `<UnitaMisura>`:

`
<DettaglioLinee>
<NumeroLinea>10</NumeroLinea>
<Descrizione>Commento</Descrizione>
<Quantita>0.00</Quantita>
<PrezzoUnitario>0.00</PrezzoUnitario>
<PrezzoTotale>0.00</PrezzoTotale>
<AliquotaIVA>22.00</AliquotaIVA>
</DettaglioLinee>
`

Ovviamente ho fatto anche un controllo formale del documento xml su altro sito e risulta corretto. Sbaglio qualcosa ? Grazie mille per l'aiuto.

Alberto

Allego file XML di esempio -> 
[IT09876543210_00454.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/5789527/IT09876543210_00454.zip)

**Comment by nicolaiarocci** [comment]
Ciao Alberto,

Ho scaricato la fattura di esempio che hai allegato e l'ho convalidata col codice seguente (preso dai test):

```cs
            var f = FatturaOrdinaria.CreateInstance(Instance.Privati);
            using (var r = XmlReader.Create(fileName, new XmlReaderSettings {IgnoreWhitespace = true}))
            {
                f.ReadXml(r);
            }
           Assert.IsTrue(f.Validate().IsValid);
 ```

Che restituisce `true`. Sembrerebbe tutto a posto.

**Comment by albertocolombo73** [comment]
Ciao Nicola e grazie per la risposta immediata,

Esattamente! Se si convalida DOPO la scrittura del file XML la fattura è corretta. Il problema nasce sulla Validate effettuata PRIMA della WriteXml (subito dopo avere caricato con i dati la classe). Non so se mi sono spiegato bene...

Utilizzo VS 2019 e VB.Net (Framework 4.7.2) questi i passaggi:

1- Istanzio la classe FatturaOrdinaria nel mio caso tipizzata Instance.Privati
2 - Aggiungo gli elementi alla classe fattura (Header, Body...)
3 - Valido la fattura (è qui che vengono generati i due errori formali 'Unita Misura' e 00444):
`                   Dim validator = New FatturaOrdinariaValidator()
                    Dim result = validator.Validate(fattura)`
4 - Scrivo il file XML:
`                            Using w = System.Xml.XmlWriter.Create(
                                pbPercorsoDOC & "\FatEsportate\" & nomeFile,
                                New System.Xml.XmlWriterSettings With {
                                    .Indent = True,
                                    .Encoding = System.Text.Encoding.UTF8})
                                fattura.WriteXml(w)
                            End Using`

Nota: se metto un carattere (ad es. un puntino) nell'unità di misura la Validate torna True.
`      <DettaglioLinee>
        <NumeroLinea>20</NumeroLinea>
        <Descrizione>COMMENTO</Descrizione>
        <Quantita>0.00</Quantita>
        <UnitaMisura>.</UnitaMisura>
        <PrezzoUnitario>0.00</PrezzoUnitario>
        <PrezzoTotale>0.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>` 

Utilizzo la tua classe da anni e NON HO MAI AVUTO UN PROBLEMA. Non capisco...

Alberto

**Comment by Dex166** [comment]
@albertocolombo73  forse la stringa che inserisci come unità di misura è una stringa vuota "" invece dovrebbe essere null .
Era successa una cosa simile a me tempo fa sempre lavorando in VB.net

**Comment by albertocolombo73** [comment]
Grazie Dex166,
mi hai preceduto... avrei postato la soluzione dopo averla testata a fondo ma è proprio così: è necessario valorizzare a Nothing la proprietà UnitaMisura. Se la si imposta a stringa vuota ("") il metodo Validate torna False riportando le seguenti anomalie:

- Unita Misura' deve essere lungo tra i 1 e 10 caratteri. Hai inserito 0 caratteri.
- Tutti i valori di natura dell’operazione presenti nelle linee di dettaglio di una fattura o nei dati di cassa previdenziale devono essere presenti anche nei dati di riepilogo

Nessun problema rilevato nel caso di scrittura dell'XML: in entrambi i casi (sia con UnitaMisura = "" che con UnitaMisura = Nothing) il file prodotto è formalmente corretto.
 
Grazie a tutti per l'aiuto.
