### ISSUE TITLE
Nuovo valore "DPU" in TipoResa (al posto di DAT)

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#313]
Buongiorno Nicola,
stando alle novità 2020 Incoterms pare ci sia un nuovo Tipo Resa "DPU" (Dati Trasporto) che va a sostituire l'obsoleto "DAT", qui il dettaglio:
https://www.sacesimest.it/education/dettaglio/incoterms-2020-cosa-sono-e-quali-sono-le-novit%C3%A0 

In questo caso ovviamente la validazione del componente fallisce.
Grazie in anticipo,
Andrea.

**Comment by nicolaiarocci** [comment]
Grazie @aferende
