### ISSUE TITLE
Irlanda del Nord

### ISSUE THREAD

**Issue by magisystem** [FatturaElettronica/FatturaElettronica.NET#314]
Salve,

a seguito degli accordi di dicembre tra UK e UE pare che ora per l'Irlanda del Nord vada usato il codice paese XI e non GB per l'emissione di fatture. Questo per quanto riguarda il campo IdPaese della partita iva e codice fiscale. Mentre per quanto riguarda la parte degli indirizzi dovrà restare GB. Mi domandavo se farete un update a breve.

**Comment by nicolaiarocci** [comment]
Quando questa novità verrà recepita dalle specifiche tecniche SDI, senz'alltro. Tengo aperto questo ticket così possiamo tracciare i progressi: se qualcuno rileva un aggiornamento faccia sapere.

**Comment by magisystem** [comment]
Perfetto! Grazie mille del chiarimento

**Comment by sgardini** [comment]
Confermato e recepito di concerto tra Agenzia Dogane, Agenzia Entrate e Istituto nazionale di statistica

https://www.fiscoetasse.com/rassegna-stampa/30095-irlanda-del-nord-attivato-il-nuovo-prefisso-intrastat-per-le-operazioni-iva.html?smclient=71b590b6-88ca-410f-a133-fedf1926405c&utm_campaign=RS&utm_medium=email_mn_fet&utm_source=Rassegna+quotidiana+&utm_content=RS+2021-02-19

**Comment by sgardini** [comment]
Questo il documento ufficiale datato 15/02/2021

[provvedimento-dogane-46832-iva-irlandanord.pdf](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/6009179/provvedimento-dogane-46832-iva-irlandanord.pdf)

**Comment by nicolaiarocci** [comment]
Aspettiamo conferma che SDI convalidi questo nuovo codice paese.

**Comment by AlexBream** [comment]
Vi segnalo che, se non sbaglio, il campo 1.2.3.6 e 1.4.2.6 Nazione, viene validato con la tabella IdPaese ma le specifiche indicano che quel campo deve essere un valore compreso nella ISO 3166-1 a due caratteri (https://it.wikipedia.org/wiki/ISO_3166-1_alpha-2) dove non è presente l'Irlanda del Nord. Quindi è probabilmente necessario creare una seconda tabella o in alternativa, visto che è una tabella soggetta a manutenzione, indicare se è un IdPaese valido solo ai fini IVA.

**Comment by tanogae** [comment]
Ci sono evoluzioni in merito?

**Comment by nicolaiarocci** [comment]
Ho provato a convalidare una fattura con XI in IdFiscaleIva e viene accettata. Direi che possiamo considerarla acquisita.

**Comment by gminutillo** [comment]
credo che il nuovo codice sia **XI** non **IX**

**Comment by nicolaiarocci** [comment]
🤦

**Comment by nicolaiarocci** [comment]
Ho rilasciato fix
