### ISSUE TITLE
Specifiche tecniche versione 1.6.2 (aggiornate il 23 nov 2020)

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#317]
Buongiorno Nicola,
il componente Fattura Elettronica.NET è stato adeguato alle specifiche 1.6.2 (modificate il 23 novembre 2020)?
Di seguito il link:
https://www.agenziaentrate.gov.it/portale/specifiche-tecniche-versione-1.6.1

Da una rapida analisi risulta qualche disallineamento su questi nodi:
- **Causale Pagamento (Dati Ritenuta)**
- Nuovo tipo **EmailContattiType** definito nello Schema XSD 1.2.1
- **Descrizioni adeguate** (ad es Tipo Documento TD20, articoli e commi di legge)

Grazie in anticipo per il tuo prezioso lavoro.
Andrea.

**Comment by nicolaiarocci** [comment]
Direi di sì https://fatturaelettronicaopensource.org/docs/changelog.html

**Comment by aferende** [comment]
Grazie per il rapido riscontro Nicola.
Tuttavia, facendo un confronto tra XSD 1.2.1 ed alcune descrizione risulta qualche differenza:

Ad esempio nella classe TipoDocumento, per il tipo TD20 la descrizione ad oggi codificata è:

`new TipoDocumento { Codice = "TD20", Nome = "autofattura per regolarizzazione e integrazione delle fatture (**ex art.6 c.8 d.lgs. 471/97**  o  art.46 c.5 D.L. 331/93)" },`

Nello schema XSD 1.2.1 riporta invece:


```
<xs:enumeration value="TD20"> |   | 500 | <xs:enumeration value="TD20">
-- | -- | -- | --
  | 504 | <xs:annotation> |   | 501 | <xs:annotation>
  | 505 | <xs:documentation>Autofattura per regolarizzazione e integrazione delle fatture (**ex art.6 c.8 e 9-bis d.lgs.471/97** o art.46 c.5 D.L. 331/93</xs:documentation> |   | 502 | <xs:documentation>Autofattura per regolarizzazione e integrazione delle fatture (ex art.6 c.8 d.lgs.471/97 o art.46 c.5 D.L. 331/93</xs:documentation>
  | 506 | </xs:annotation> |   | 503 | </xs:annotation>
  | 507 | </xs:enumeration>
```

Nelle causali di pagamento inoltre dovrebbero essere rimossi i seguenti tipi (in quanto non più validi dal 01.01.2021 ed essendo terminato il periodo transitorio):

```
new CausalePagamento{ Codice = "J", Nome = "compensi corrisposti ai raccoglitori occasionali di tartufi non identificati ai fini dell’imposta sul valore aggiunto, in relazione alla cessione di tartufi"},
                    new CausalePagamento{ Codice = "K", Nome = "assegni di servizio civile universale di cui all’art.16 del D.lgs. n. 40 del 6 marzo 2017"},
                    new CausalePagamento{ Codice = "V2", Nome = "redditi derivanti dalle prestazioni non esercitate abitualmente rese dagli incaricati alla vendita diretta a domicilio"},
                    
```

Grazie in anticipo.
A.

**Comment by nicolaiarocci** [comment]
Mi risulta che anche causale Z andrebbe rimossa, confermi?

**Comment by nicolaiarocci** [comment]
Un altro problema è che credo sia sempre possibile registrare una  fattura con data antecedente il 1/1/2001, e in quel caso la convalida accetti ancora gli obsoleti. Qualcuno può confermare?

**Comment by aferende** [comment]
> Mi risulta che anche causale Z andrebbe rimossa, confermi?

Confermo. Z andrebbe rimosso

**Comment by nicolaiarocci** [comment]
@sgardini mi confermi questo:

> credo sia sempre possibile registrare una fattura con data antecedente il 1/1/2021, e in quel caso la convalida AgEntrate accetta ancora i valori obsoleti.

**Comment by sgardini** [comment]
@nicolaiarocci al momento direi proprio sia così. Il fatto che la fattura sia sanzionabile per decorrenza del termine di 12 giorni non vieta di poterlo fare assumendosi il rischio.
