### ISSUE TITLE
Segnalazione errore 00423

### ISSUE THREAD

**Issue by sibylmichelangelotodaro** [FatturaElettronica/FatturaElettronica.NET#32]
Ciao,

ti allego le linee di un documento che stranamente non viene validato completamente con il seguente errore:

**FatturaElettronicaBody[0].DatiBeniServizi.DettaglioLinee[2].PrezzoTotale: 00423: il valore del campo PrezzoTotale non risulta calcolato secondo le regole definite nelle specifiche tecniche**

Riesci a dirmi il motivo?
>    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>Codice Altro Fornitore</CodiceTipo>
          <CodiceValore>14145020</CodiceValore>
        </CodiceArticolo>
        <Descrizione>Lampada  proiettore abbagliante</Descrizione>
        <Quantita>2.00</Quantita>
        <UnitaMisura>Pezzi</UnitaMisura>
        <PrezzoUnitario>15.30</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>25.00</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>22.95</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>Codice Altro Fornitore</CodiceTipo>
          <CodiceValore>14151095</CodiceValore>
        </CodiceArticolo>
        <Descrizione>Lampada  proiettore abbagliante</Descrizione>
        <Quantita>2.00</Quantita>
        <UnitaMisura>Pezzi</UnitaMisura>
        <PrezzoUnitario>5.94</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>25.00</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>8.91</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>3</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>Codice Originale</CodiceTipo>
          <CodiceValore>10835492</CodiceValore>
        </CodiceArticolo>
        <Descrizione>Lampada posizione ant.</Descrizione>
        <Quantita>2.00</Quantita>
        <UnitaMisura>Pezzi</UnitaMisura>
        <PrezzoUnitario>6.95</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>25.00</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>10.43</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>4</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>Codice Originale</CodiceTipo>
          <CodiceValore>14148094</CodiceValore>
        </CodiceArticolo>
        <Descrizione>Lampada direzione ant.</Descrizione>
        <Quantita>2.00</Quantita>
        <UnitaMisura>Pezzi</UnitaMisura>
        <PrezzoUnitario>17.28</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>25.00</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>25.92</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>5</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>Codice Articolo</CodiceTipo>
          <CodiceValore>449240</CodiceValore>
        </CodiceArticolo>
        <Descrizione>Proiettore</Descrizione>
        <Quantita>1.00</Quantita>
        <UnitaMisura>Pezzi</UnitaMisura>
        <PrezzoUnitario>213.89</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>15.00</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>181.81</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>6</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>Codice Articolo</CodiceTipo>
          <CodiceValore>449239</CodiceValore>
        </CodiceArticolo>
        <Descrizione>Proiettore</Descrizione>
        <Quantita>1.00</Quantita>
        <UnitaMisura>Pezzi</UnitaMisura>
        <PrezzoUnitario>213.89</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>15.00</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>181.81</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>7</NumeroLinea>
        <Descrizione>S.r Proiettore ant. dx</Descrizione>
        <Quantita>0.55</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>26.00</PrezzoUnitario>
        <PrezzoTotale>14.30</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>8</NumeroLinea>
        <Descrizione>S.r Proiettore ant. sx</Descrizione>
        <Quantita>0.55</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>26.00</PrezzoUnitario>
        <PrezzoTotale>14.30</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>9</NumeroLinea>
        <Descrizione>S.r Paraurti ant.</Descrizione>
        <Quantita>0.45</Quantita>
        <UnitaMisura>Pezzo</UnitaMisura>
        <PrezzoUnitario>26.00</PrezzoUnitario>
        <PrezzoTotale>11.70</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DatiRiepilogo>
        <AliquotaIVA>22.00</AliquotaIVA>
        <Arrotondamento>0.00</Arrotondamento>
        <ImponibileImporto>472.13</ImponibileImporto>
        <Imposta>103.87</Imposta>
        <EsigibilitaIVA>S</EsigibilitaIVA>
        <RiferimentoNormativo>Iva versata dal committente art. 17-ter D.P.R. 633/72</RiferimentoNormativo>
      </DatiRiepilogo>
    </DatiBeniServizi>

**Comment by nicolaiarocci** [comment]
Se mandi xml alla PA lo accetta?

**Comment by sibylmichelangelotodaro** [comment]
Si, ho provato a validarla sul sito fatturapagov.it e viene accettata senza errori.

[link](http://sdi.fatturapa.gov.it/SdI2FatturaPAWeb/AccediAlServizioAction.do?pagina=controlla_fattura)

**Comment by nicolaiarocci** [comment]
Che versione del package stai usando? Con la 0.3.6 non mi da l'errore riportato.

**Comment by sibylmichelangelotodaro** [comment]
Con nuget non riesco più ad aggiornare.
Hai impostato target framework 4.5 come requisito.
Puoi riportarlo al 4.0 ?

**Comment by nicolaiarocci** [comment]
Purtroppo no.

**Comment by sibylmichelangelotodaro** [comment]
Secondo te, se scarico l'ultima versione da Git riesco poi a compilarla con il framework 4.0 ?

Noi non possiamo cambiare il framework.

**Comment by nicolaiarocci** [comment]
Se non ricordo male sulla master branch c'è ancora il codice compatibile col .NET4 quindi potrebbe funzionare (ma non te lo assicuro).

**Comment by nicolaiarocci** [comment]
PS: sulla branch `nuovo_pattern_di_convalida`, che presto verrà portata su master, il codice è incompatibile con 4.0. Quindi tenete presente che in ogni caso per i prossimi aggiornamenti sarà dura.
