### ISSUE TITLE
Errore in validazione campo RiferimentoTesto

### ISSUE THREAD

**Issue by gptucci** [FatturaElettronica/FatturaElettronica.NET#33]
Ciao
Grande lavoro !!
Becco il seguente errore
FatturaElettronicaBody[0].DatiBeniServizi.DettaglioLinee[1].AltriDatiGestionali[0].RiferimentoTesto: La lunghezza deve essere tra 1 e 35
In effetti i campi sono da più di 65 caratteri, ma la specifica ne permette sino a 80.

Grazie

**Comment by nicolaiarocci** [comment]
Ciao. Intendi 1..60 vero?

**Comment by gptucci** [comment]
Si giusto
60 caratteri
Mi sono sbagliata a leggere la specifica
