### ISSUE TITLE
Problema FatturaBase.CreateInstanceFromXml

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#333]
Ciao Nicola,
per la fattura in allegato 
[Fattura.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/6239896/Fattura.zip)
si presenta un bug durante la chiamata al metodo `FatturaBase.CreateInstanceFromXml`.

Questo l'errore:
`System.FormatException  The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.      at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)     at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)     at System.Convert.FromBase64String(String s)     at FatturaElettronica.FatturaBase.CreateInstanceFromXmlSignedBase64(Stream stream, Boolean validateSignature)     at FatturaElettronica.FatturaBase.CreateInstanceFromXmlSigned(Stream stream, Boolean validateSignature)     at FatturaElettronica.FatturaBase.CreateInstanceFromXml(Stream stream, Boolean validateSignature)`

Premetto che questa fattura ha una moltitudine di stranezze e chi l'ha prodotta andrebbe messo a pane ed acqua per 1 settimana ma è arrivata così (passiva) da SDI ... segno che per loro è ok (ho cambiato ovviamente i dati sensibili all'interno).

Grazie in anticipo.
Andrea

**Comment by nicolaiarocci** [comment]
Ciao, scusa per il ritardo. È un problema interessante. Credo sia il padding alla fine di ogni riga a creare il problema. Anche usando `IgnoreWhitespace=true` non si riesce a leggerla. Ovviamente puoi risolvere pre-processando il file, cosa che immagino tu abbia già fatto. Sarebbe interessante incorporare una soluzione. Se ho tempo settimana prossima approfondisco (suggerimenti e pull-request sono benvenuti/e).

**Comment by aferende** [comment]
Ciao Nicola,
tranquillo immagino.
Si ovviamente ripulendo prima la fattura viene letta correttamente ma
bisognerebbe dove la deserializzazione si incavola.
Nel weekend sicuro mi ci metto e ti do una mano.

PS: Questa fattura è arrivata da SDI come passiva ... quindi dal loro punta
di vista è corretto (loro sono su Java/Linux e quindi chissà che combinano).
Ti faccio sapere.
Grazie,
A.

Il giorno ven 28 mag 2021 alle ore 16:58 Nicola Iarocci <
***@***.***> ha scritto:

**Comment by aferende** [comment]
Ciao Nicola,
nel weekend ho provato a fare un po' di debug.

Il problema sembra essere insito alla classe Stream.
Se invece si utilizza uno StreamReader non c'è alcun problema.
Di seguito il frammento di codice utilizzato e che NON da problemi con
quella fattura:

var reader = new StreamReader(file);
            XmlReader rdr = XmlReader.Create(reader);
            while (rdr.Read())
            {
               Console.WriteLine(rdr.Value);
            }

Sinceramente non riesco a capire perchè utilizzando Stream si blocchi;
ipotizzo un bug congenito di .NET a questo punto.
Un'idea potrebbe essere quella di innestare una lettura tramite
StreamReader ma ovviamente bisognerebbe fare un po' di regression test
perchè andremmo a toccare il "cuore" di FatturaElettronica.NET
Fammi sapere cosa ne pensi.
Se serve, sono a disposizione.
Andrea.

Il giorno ven 28 mag 2021 alle ore 16:58 Nicola Iarocci <
***@***.***> ha scritto:

**Comment by tanogae** [comment]
Ciao Nicola ,

questo issue è ancora in piedi, putroppo abbiamo ricevuto fatture con questo problema e mi chiedevo come gestirle.

Grazie

Ciao

**Comment by username77** [comment]
Confermo, capita anche a me questo errore ma parliamo di casi veramente rari dal lato mio 10 casi nel 2023 su decine di migliaia di fatture. Io ho dovuto gestirle manualmente ma al prossimo caso vedro' di farci caso a cosa e' dovuto

**Comment by username77** [comment]
nel mio caso ho trovato il problema nella parte del encoding dove mi e' bastato cambiare:
<?xml version="1.0" encoding="windows-1252"?>
con questo
<?xml version="1.0" encoding="UTF-8"?>

Da notare cmq che nelle fatture anomale io ho come fine riga "CrLf" invece di "Lf". Cambiando in UTF-8 il fine riga viene letto bene in entrambi i casi.

**Comment by nicolaiarocci** [comment]
Vedi anche #421 che offre una ottima soluzione, soprattutto per NET8+.
