### ISSUE TITLE
FluentValidation error using FluentValidation 10.0.0

### ISSUE THREAD

**Issue by neoDD69** [FatturaElettronica/FatturaElettronica.NET#337]
Usando la 3.1.4 con FluentValidation 10.0.0 il `Validate<FatturaOrdinaria>()` genera una exception:

`MissingMethodException: Impossibile trovare il metodo 'FluentValidation.IRuleBuilderOptions'2<!0,!1> FluentValidation.IRuleBuilder'2.SetValidator(FluentValidation.Validators.IPropertyValidator)'.
`
ho risolto portando FluentValidation indietro alla 9.5.1.

PS: ne aprofitto per ringraziare Nicola Iarocci per questa grande libreria!!

**Comment by nicolaiarocci** [comment]
vedi anche https://github.com/FatturaElettronica/FatturaElettronica.NET/pull/338

**Comment by neoDD69** [comment]
sì avevo visto ma sinceramente non avevo capito molto ;)
Scusami non so ancora come muovermi bene nel segnalare i problemi ;) ... normalmente li risolvo o li creo :D

**Comment by nicolaiarocci** [comment]
no va bene, quella è una PR automatica fatta da dependant-bot e conferma la tua segnalazione: i test falliscono quando si passa a FE 10

**Comment by nicolaiarocci** [comment]
Rimanendo su FluentValidation 9 tutto funziona regolarmente. 

Ad una occhiata rapida mi pare ci sia un po' di lavoro da fare dato che v10 rompe diverse cose (vedi https://docs.fluentvalidation.net/en/latest/upgrading-to-10.html). Se qualcuno ha voglia di cimentarsi è il benvenuto/a; io al momento sono impegnato.

**Comment by neoDD69** [comment]
Confermo che con la 9 non mi hanno segnalato problemi.
Anch'io sono incasinato, ma se ti va posso trovare il tempo di darci un occhiata in settimana, anche se non ho mai usato FluentValidation.

**Comment by nicolaiarocci** [comment]
Certo, vai pure.

**Comment by Letippi** [comment]
Anche io ho avuto lo stesso problema, con la versione 9.5.1 di FluentValidation funziona. Grazie per il suggerimento!

**Comment by neoDD69** [comment]
Io mi ero ripromesso di cercare di debuggare il problema ... ma sono  stato travolto dal lavoro ;( speriamo di riuscirci prima della fine del 2021.
Cmq ti confermo che io lo uso senza problemi con la 9.5.4.

**Comment by neoDD69** [comment]
grazie @nicolaiarocci per aver sistemato e pubblicato update.
Non so serva, ma ti confermo che funziona bene con FluentValidation ultima versione 10.xx
