### ISSUE TITLE
Problema con .NET Core

### ISSUE THREAD

**Issue by sid80210** [FatturaElettronica/FatturaElettronica.NET#345]
Ciao,

sto passando un progetto che contiene FatturaElettronica da .NET Framework a .NET Core 5
Ottengo un errore di compilazione su fattura.ReadXmlSigned(memory, false) ovvero una sezione nella quale provo a leggere da uno stream in memoria la fattura.
Su .NET Framework funziona tutto correttamente mentre qui mi da il messaggio nello screenshot allegato.

Ovviamente sto usando ultima versione del package...come posso risolvere?

![image](https://user-images.githubusercontent.com/25952561/118676797-00eb6300-b7fc-11eb-9b0a-1c1be7fb1a0c.png)

**Comment by nicolaiarocci** [comment]
Possibile tu abbia un riferimento a `FatturaElettronica.Extensions` package, ora obsoleto?

**Comment by sid80210** [comment]
Ho rimosso il package ma ora mi dice 

![image](https://user-images.githubusercontent.com/25952561/118960911-0cf23480-b964-11eb-93cf-6a10f5be618f.png)

**Comment by sid80210** [comment]
Qualche idea?

**Comment by nicolaiarocci** [comment]
Ciao, ho provato a creare un progetto NET5 e usare `ReadXmlSigned` e non ho avuto problemi:

Contenuto di `Test.csproj`:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FatturaElettronica" Version="3.1.5" />
  </ItemGroup>

</Project>
```

Contenuto di `Program.cs`:

```cs
using System;
using FatturaElettronica.Extensions;
using FatturaElettronica.Ordinaria;

namespace test
{
    class Program
    {
        static void Main()
        {
            var fattura = new FatturaOrdinaria();
            fattura.ReadXmlSigned("IT01234567890.xml.p7m");

            Console.WriteLine(fattura.FatturaElettronicaBody[0].DatiGenerali.DatiGeneraliDocumento.Numero);
        }
    }
}
```
