### ISSUE TITLE
Manca is "set" nella 3.1.5

### ISSUE THREAD

**Issue by username77** [FatturaElettronica/FatturaElettronica.NET#346]
Come mai e' stato tolto il set e lasciato solo il get nel ultima versione 3.1.5?

_Originally posted by @username77 in https://github.com/FatturaElettronica/FatturaElettronica.NET/issues/303#issuecomment-845914518_

e' stata tolta qui
https://github.com/FatturaElettronica/FatturaElettronica.NET/commit/e86a0753e2d26ade5148d7ca211063f44efb5422#diff-67724d5f44972efb0bdc141efda0184888e7e4a560179777988b34f871f0674f

**Comment by nicolaiarocci** [comment]
probabilmente un refactoring un po' troppo aggressivo...
