### ISSUE TITLE
Adeguamento nuove specifiche 1 luglio 2021

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#354]
Buongiorno Nicola,
hai una roadmap circa l'adeguamento alle nuove specifiche previste per il 1 luglio 2021?
https://www.agendadigitale.eu/documenti/fatturazione-elettronica/fattura-elettronica-le-nuove-regole-tecniche-dal-primo-luglio-che-cambia/

Grazie al solito,
Andrea.

**Comment by aferende** [comment]
È ipotizzabile (o magari già esistente) un "convertitore" tra fattura PA e fattura Europea in UBL?
Questo potrebbe aiutare molto...

**Comment by username77** [comment]
su questo link c'e' una versione Turca dello standard europeo che non so se puo' servire a qualcosa
https://github.com/hkutluay/UblTr

Di regola lo standard sara' unico per tutti i paesi europei o no?

**Comment by SilentRage47** [comment]
Buonasera, ci sono novità anche per le modifiche alla fatturazione elettronica 1.7 ?
