### ISSUE TITLE
Validazione campo email

### ISSUE THREAD

**Issue by magisystem** [FatturaElettronica/FatturaElettronica.NET#358]
Salve, è corretto che la validazione mi scarti gli xml per via di mail concatenate nel campo email? Perchè da specifiche della fattura elettronica sembra che non vi siano controlli, quantomeno non ve ne siano più.

Grazie

**Comment by nicolaiarocci** [comment]
Ciao, la libreria usa `FluentValidation.EmailAddress` come regola di validazione. L'ultima volta che ci ho guardato questa convalida supporta due modalità: quella di default che in pratica controlla solo la presenza del carattere @ (mi pare) ed è quindi molto "lasca", e la modalità "Net4Regex" che è considerata obsoleta da FluentValidation ma che si avvicina di più a quella definita nelle specifiche:

![image](https://user-images.githubusercontent.com/512968/132033489-904d488d-0194-4348-944e-5114805fd303.png)

La libreria usa la modalità Net4Regex al momento, dopo lunghe discussioni su quale fosse da adoperare. È molto probabile che le due, quella delle specifiche e quella di FluentValidation non siano al 100% compatibili. Convertire la regex delle specifiche tecnica in una regex .NET è possibile, andando poi ad applicare una regola regex personalizzata ai campi mail. In alternativa si potrebbe 1) rimuovere la convalida delle mail del tutto o 2) usare la regola di convalida predefinta (che mi par di ricordare aveva dato problemi a qualche utente). Se qualcuno ha tempo per implementarla e proporre una PR sarò ben lieto di considerarla.

**Comment by nicolaiarocci** [comment]
PS: occorrerebbe anche verificare che la regex che ho incollato qui sopra sia ancora quella nell'ultima versione delle specifiche.
