### ISSUE TITLE
[Serialization] La funzione ToJson() non nomina le proprietà come dovrebbero essere nell'xml

### ISSUE THREAD

**Issue by LuigiElleBalotta** [FatturaElettronica/FatturaElettronica.NET#359]
Mi spiego meglio:
Nell'xml e precisamente nell'header ci dovrebbe essere il nodo "RappresentanteFiscale".
Nella vostra libreria invece "RappresentanteFiscale" è scritto come valore della proprietà ElementName dell'attributo XmlElement

![immagine](https://user-images.githubusercontent.com/16773213/143256370-0a254720-b11f-4a31-8420-8f81cfea740c.png)

Di conseguenza quando si chiama il metodo ToJson() la proprietà viene chiamata **Rappresentante** e non **RappresentanteFiscale**. 
Non so se esiste questa problematica anche per altri campi, me ne sono accorto solo con questo..

Inoltre, sempre nel json, vengono generate anche proprietà che non contengono nulla e che quindi o dovrebbero essere valorizzate a NULL o non messe proprio, come da screenshot: 

![Schermata 2021-11-24 alle 15 28 37](https://user-images.githubusercontent.com/16773213/143256818-37b0aa4d-4da5-4f27-bf74-a8fe3cc803f7.png)

**Comment by LuigiElleBalotta** [comment]
Forse dovrebbe bastare mettere anche questo attributo (?):
`[JsonPropertyName("RappresentanteFiscale")]`

**Comment by nicolaiarocci** [comment]
Ciao, grazie per la segnalazione. 

Ho implementato la serializzazione corretta di `RappresentanteFiscale`. Per le object property la questione è più delicata. Con un custom contract resolver si potrebbe risolvere, credo, ma non vorrei rompere compatibilità per chi usa la libreria da tempo. Se è un problema insormontabile per voi apri per favore un ticket separato, grazie.

**Comment by LuigiElleBalotta** [comment]
Perfetto, non dovrebbe essere un problema insormontabile credo.. Invece altra domanda:

Mi è capitato di avere nei DatiRiepilogo l'AliquotaIVA e Imposta a 0 oppure nel dettaglio linea AliquotaIva = 0. Quando faccio ToJson() se quelle proprietà hanno appunto come valore "0" non vengono serializzate.

Fondamentalmente noi stiamo facendo un serverino in NestJS per la verifica a partire dal json che ritorna l'xml.
Avendo questo problema di proprietà non serializzate oppure proprietà vuote, il server in NestJS si incazza perchè non vengono superati i controlli delle regex.

So che la tua libreria ha già la funzione per validare tutto, solo che abbiamo appunto questo server in NestJS perchè non tutte le nostre applicazioni sono in .NET ma anzi stiamo portando tutto su TypeScript e volevamo avere un server unico per validare le fatture dalle varie applicazioni che programmiamo.

**Comment by nicolaiarocci** [comment]
Ciò credo sia dovuto a [questa linea](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/f6d2238989d56a349653c64ec65a697abee4a514/Core/BaseClassSerializable.cs#L288) che serve a evitare di compattare il json, evitando di serializzare proprietà che hanno valori corrispondenti ai default per il tipo. Siccome abbiamo già una classe `JsonOptions` non dovrebbe essere difficile rendere questo comportamento personalizzabile.

**Comment by nicolaiarocci** [comment]
PS: visto che `ToJson` è una `public virtual` potreste per il momento farne l'override in una vostra subclass, qualcosa tipo:

```cs
public class MyFatturaOrdinaria : FatturaOrdinaria
    {
        public override string ToJson(JsonOptions options)
        {
            var json = JsonConvert.SerializeObject(
                this, options == JsonOptions.Indented ? Formatting.Indented : Formatting.None,
                new JsonSerializerSettings
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                    // Include invece che Ignore
                    DefaultValueHandling = DefaultValueHandling.Include
                });
            return json;
        }
    }
```

**Comment by LuigiElleBalotta** [comment]
@nicolaiarocci Grazie per il suggerimento e la modifica :)
