### ISSUE TITLE
Doppio Campo Causale XML

### ISSUE THREAD

**Issue by next100years** [FatturaElettronica/FatturaElettronica.NET#363]
Buongiorno,
dovrei generare sul file XML di scambio una doppia riga di causale (su ARUBA fatturazione elettronica viene importata correttamente)

Il risultato dovrebbe essere questo con doppio campo CAUSALE
`
-<DatiGenerali>
-<DatiGeneraliDocumento>
.....
<Causale>Descrizione Causale 1</Causale>
<Causale>Descrizione Causale 2</Causale>
</DatiGeneraliDocumento>
</DatiGenerali>
`

Tramite il codice però è fattibile?
`
                List<string> causale = new List<string>();
                causale.Add(DescrizioneFattura);
                body.DatiGenerali.DatiGeneraliDocumento.Causale                 = causale; // Max: 200
`
Grazie

**Comment by nicolaiarocci** [comment]
si certo, `DatiGeneraliDocumento.Causale` è definito come una `List<string>` e verrà serializzata come tale nel XML.
