### ISSUE TITLE
Adeguamento specifiche tecniche 1.7

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#364]
Buongiorno Nicola,
pensi sia necessario qualche adeguamento del componente per la ver. 1.7 delle specifiche? (fatture estere/esterometro)
https://www.agenziaentrate.gov.it/portale/web/guest/specifiche-tecniche-versione-1.7

Potrebbe essere inoltre utile inserire una funzionalità di generazione del QR Code di fatturazione nel componente.
Grazie,
A.

**Comment by nicolaiarocci** [comment]
La versione 3.2 rilasciata lo scorso 25 Movembre dovrebbe essere allilneata alla specifiche v1.7. [Qui](https://fatturaelettronicaopensource.org/docs/changelog.html#v-320) trovi il changelog.
