### ISSUE TITLE
System.Text.Json

### ISSUE THREAD

**Issue by MaxPlap** [FatturaElettronica/FatturaElettronica.NET#366]
Sarebbe preferibile supportare System.text.json in quanto è una dipendenza comune molto diffusa da .net core 3 in avanti rispetto newtonsoftJson.
Avviene il contrario per chi usa .net framework 4. 

Merita di investigare la fattibilità?

**Comment by nicolaiarocci** [comment]
Già abbiamo fatto la transizione, vedi #360 e [cronologia](https://fatturaelettronicaopensource.org/docs/changelog.html). Non è ancora stato rilasciato.
