### ISSUE TITLE
CodiceArticlo is LatinExt according documentation

### ISSUE THREAD

**Issue by michaelmairegger** [FatturaElettronica/FatturaElettronica.NET#368]
According the govenments XSD file https://www.fatturapa.gov.it/export/documenti/fatturapa/v1.2.1/Schema_del_file_xml_FatturaPA_versione_1.2.1.xsd the validation rule for CodiceArticloType.CodiceValore is String35LatinExtType. According this the only limitation is xs:normalizedString

    <xs:simpleType name="String35LatinExtType">
      <xs:restriction base="xs:normalizedString">
        <xs:minLength value="1"/>
        <xs:maxLength value="35"/>
      </xs:restriction>
    </xs:simpleType>

I will provide a PR for this issue.

**Comment by nicolaiarocci** [comment]
Thanks, Michael.
