### ISSUE TITLE
Autofattura td17 con fornitore residente a Campione d'Italia

### ISSUE THREAD

**Issue by DBOutlink** [FatturaElettronica/FatturaElettronica.NET#370]
Salve, qual è la procedura corretta per creare un documento con tipo TD17 per un fornitore residente a Campione d'Italia o Livigno? Da più parti si dice di utilizzare OO nel campo idPaese del cedentePrestatore ma non è tra quelli accettati (credo giustamente) mentre se si imposta IT non passa la validazione con il seguente errore:
"i valori TD17, TD18 e TD19 del tipo documento non ammettono l’indicazione in fattura di un cedente italiano"
Grazie per il supporto

**Comment by aferende** [comment]
Seguo. Stessa domanda
Per info, a seguito di apertura ticket a SDI, vi segnalo la risposta di SDI:

_Gentile utente,
Tra le FAQ all'AdE può certamente ritrovare le modalità di compilazione della fattura verso Livigno
https://www.agenziaentrate.gov.it/portale/Schede/Comunicazioni/Fatture+e+corrispettivi/FAQ+fe/Risposte+alle+domande+piu+frequenti+categoria/Fatture+verso+e+da+soggetti+stranieri+transfrontaliere/

Cordiali saluti
Assistenza fatture e corrispettivi_ 

A quanto pare quindi OO va considerato.

**Comment by nicolaiarocci** [comment]
@sgardini la tua opinione in proposito?

**Comment by aferende** [comment]
Ad ulteriore conferma, ho aperto altro ticket esplicito a SDI.

Questa la risposta:
```

Gentile utente, le confermiamo che da Febbraio 2021 è stato esteso l’utilizzo di ‘OO’ come identificativo paese laddove il Cessionario Committente decida di trasmettere un TD17 e TD19 in cui il Cedente Prestatore è un soggetto residente nel comune di Livigno o Campione d’Italia.
In tutti gli altri casi di utilizzo di ‘OO’ e tipo documento diverso da TD17 e TD19 i file vengono scartati. 

Grazie,
Andrea.
```

**Comment by aferende** [comment]
@nicolaiarocci @Artusoft 
direi che questo chiarisce i dubbi:

https://assistenza.agenziaentrate.gov.it/FatturazioneUIKIT/KanaFattElettr.asp?St=422,E=0000000000276145823,K=3107,Sxi=0,Case=Obj(2918),ts=Fatturazione,t=Faq,VARSET_Idcaso=2918

Fatemi sapere se è possibile aggiungere "OO" all'elenco codici Paese.
Al solito grazie per il Vs. lavoro.
Andrea.
