### ISSUE TITLE
Codice Paese Grecia

### ISSUE THREAD

**Issue by ragePolpette** [FatturaElettronica/FatturaElettronica.NET#374]
Ciao, il codice paese EL per la Grecia non è presente nella lista, è pero un codice valido accettato dall'SDI

**Comment by nicolaiarocci** [comment]
Ciao, il codice per la Grecia secondo ISO 3166-1 alpha 2 è GR, ed è [supportato](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/Tabelle/IdPaese.cs#L95).

**Comment by brux88** [comment]
salve ho avuto lo stesso problema mi è stato richiesto codice el ma non passai controlli della libreria

**Comment by nicolaiarocci** [comment]
potrebbe un altro caso Irlanda del Nord (vedi #314). Mi confermate che SDI convalida correttamente EL?

**Comment by ragePolpette** [comment]
Ciao,  io alla fine ho fatto un manino per farle partire lo stesso e l sdi ce le ha accettate

**Comment by code2learnit** [comment]
ciao, 
non ho ancora trovato un documento AE, ma SDI accetta tanto GR (il codice ISO) quanto EL (https://publications.europa.eu/code/it/it-370100.htm)

Sarebbe molto utile (per evitare modifiche a mano) che anche EL fosse accettato dal validatore

**Comment by code2learnit** [comment]
grande!!
grazie mille
