### ISSUE TITLE
Controllo su CAP sempre a 5

### ISSUE THREAD

**Issue by lunatrik** [FatturaElettronica/FatturaElettronica.NET#375]
Salve
Sto riscontrando delle problematiche dopo aver generato una fattura per la nazione Belgio. 
Praticamente quando viene passata al validatore della località, viene sempre effettuato un controllo sul cap. Di seguito l'errore 
Errore in validazione XSD: cvc-pattern-valid: Value '4040' is not facet-valid with respect to pattern '[0-9][0-9][0-9][0-9][0-9]' for type 'CAPType'. Linea:43 Colonna:24 - b4011d38b9c54b30b4e48033e595ef07

come devo comportarmi sotto questo punto di vista? Ho notato anche che nella documentazione ufficiale della fatturazione elettronica, impongono 5 come lunghezza.

**Comment by username77** [comment]
Usa cinque zeri per fuori italia "00000"
