### ISSUE TITLE
Adeguamento a specifiche 1.7.1 (dal 01 ottobre 2022)

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#376]
Salve Nicola,
ci sono all'orizzonte alcune novità introdotte nelle **specifiche 1.7.1 operative dal 01 ottobre 2022**.

Come contributo alla causa, riporto di seguito i link utili ed una sintesi delle novità che saranno introdotte, al solito ringraziando per il prezioso lavoro a questo progetto.

**Comunicato:** 
https://www.agid.gov.it/it/agenzia/stampa-e-comunicazione/notizie/2022/08/02/fatturazione-elettronica-pubblicate-nuove-specifiche-tecniche-utilizzabili-dal-1deg
**Link:** 
https://www.agenziaentrate.gov.it/portale/web/guest/specifiche-tecniche-versione-1.7.1
**Specifiche Tecniche:** https://www.agenziaentrate.gov.it/portale/documents/20143/4056792/Variazioni+alle+specifiche+tecniche+fatture+elettroniche2022-08-01+%281%29.pdf/5bfad4fa-75ad-a85c-fd57-497a0f3cd637

Sintesi dei cambiamenti
![Sintesi](https://user-images.githubusercontent.com/13355101/183665070-c5b77903-ea1d-48ef-8c26-b610b967f91e.jpg)

**Comment by nicolaiarocci** [comment]
ciao @aferende grazie per l'ottimo ticket, completo di tutte le necessarie informazioni. WIP.

**Comment by aferende** [comment]
Ciao @nicolaiarocci e grazie per l'aggiornamento.
In particolare cosa non ti convince del TD28 ed errore 00476?

**Comment by aferende** [comment]
Comunque i test che ho fatto hanno dato esito positivo.
Secondo me si può rilasciare in stable @nicolaiarocci
