### ISSUE TITLE
Controlli 00401 e 00430

### ISSUE THREAD

**Issue by tanogae** [FatturaElettronica/FatturaElettronica.NET#382]
Per entrambi i controlli è stata modificata la descrizione

Natura presente a fronte di Aliquota IVA diversa da zero  **(l’indicazione di un’aliquota IVA diversa da zero qualifica i dati di riepilogo come dati riferiti ad operazioni imponibili e quindi non è ammessa la presenza dell’elemento Natura, ad eccezione del caso in cui l’elemento TipoDocumento assume valore TD16)**

ma sembra che il controllo non preveda l'esclusione dei documenti TD16.

**Comment by tanogae** [comment]
Ancora no

**Comment by tanogae** [comment]
Vedo se riesco a fare qualcosa nel weekend

**Comment by aferende** [comment]
Ciao @nicolaiarocci @tanogae,
credo ci sia un  bug qui.
Ho aperto issue 384

https://github.com/FatturaElettronica/FatturaElettronica.NET/issues/384
