### ISSUE TITLE
Errore di Validazione in ver 3.4.3

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#384]
Buongiorno Nicola,
con la versione 3.4.3, rilasciata pochi minuti fa su NuGet, si verifica un errore di validazione su una fattura elettronica abbastanza "canonica".
Questo l'errore:

"Natura presente a fronte di Aliquota IVA diversa da zero (l’indicazione di un’aliquota IVA diversa da zero qualifica l’operazione come imponibile e quindi non è ammessa la presenza dell’elemento Natura, ad eccezione del caso in cui l’elemento TipoDocumento assume valore TD16)"

Può dipendere dall'ultimo controllo di validazione introdotto? (Controllo 00471)

Allego la fattura di test utilizzata per la validazione.
Grazie in anticipo.
Andrea.
[Fattura Test.txt](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/9689792/Fattura.Test.txt)

**Comment by nicolaiarocci** [comment]
@aferende puoi confermarmi se la fix che ho pubblicato risolve il problema?

**Comment by aferende** [comment]
Ciao @nicolaiarocci confermo che la fix risolve il problema.
Grazie

**Comment by aferende** [comment]
@nicolaiarocci rilasci su NuGet appena possibile?

**Comment by nicolaiarocci** [comment]
a minuti

**Comment by tanogae** [comment]
Sorry !

**Comment by nicolaiarocci** [comment]
@tanogae va tutto bene. Grazie per aver riportato il problema e suggerito la giusta direzione. La lezione qui è che la fretta è cattiva consigliera, soprattutto per il maintainer :-)

**Comment by tanogae** [comment]
@nicolaiarocci mi sorge un dubbio ... con i controlli così implementati ... per i documenti TD16 è garantito che con Aliquota = 0 la Natura debba essere compilata ?

**Comment by nicolaiarocci** [comment]
a memoria, probabilmente no. Ora non riesco a guardarci.

**Comment by nicolaiarocci** [comment]
Direi che siamo coperti [qui](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/Validators/DettaglioLineeValidator.cs#L37) e [qui](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/Validators/DatiRiepilogoValidator.cs#L16).
