### ISSUE TITLE
Controllo 00476

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#386]
Buongiorno,
a seguito di ticket a SDI credo ci sia da fare un approfondimento sulla correttezza del controllo 00476.
(Gli elementi IdPaese e IdPaese non possono essere entrambi valorizzati con codice diverso da IT).

Nel caso della fattura allegata, il Cedente ha una PIVA estera (VA) ed un Cessionario con solo Codice Fiscale.
SDI afferma che in questi casi la fattura va considerata come valida (mentre Fattura Elettronica .NET non la fa passare)

Allego fattura di riferimento per i dovuti test.
Grazie in anticipo,
Andrea.

[fattura.xml.txt](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/9745108/fattura.xml.txt)

**Comment by nicolaiarocci** [comment]
per cortesia, puoi verificare se la fix risolve il problema? attualmente su `master`.

**Comment by aferende** [comment]
Ottimo @nicolaiarocci 
Confermo che con la versione master ora la validazione passa.
Confermo inoltre che SDI così ha accettato correttamente la fattura (senza scarto) - canale di test
Attendo rilascio su NuGet.
Grazie al solito.
