### ISSUE TITLE
Controllo 00471

### ISSUE THREAD

**Issue by exolabsrl** [FatturaElettronica/FatturaElettronica.NET#387]
Buongiorno,

il controllo 00471 fallisce nel caso in cui il cedente ha sia IdFiscaleIVA che CodiceFiscale ed emette fattura a se stesso specificando solo i dati di IdFiscaleIVA nel cessionario.
E' sufficiente controllare la diversità di IdFiscaleIVA tra cedente e cessionario così come fa lo SDI durante i propri controlli.

Allego un documento sui controlli che esegue lo SDI (fonte: https://www.fatturapa.gov.it/export/documenti/Elenco-Controlli-versione-1.8.pdf)

[Elenco-Controlli-versione-1.8.pdf](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/9757526/Elenco-Controlli-versione-1.8.pdf)

Grazie mille

**Comment by tanogae** [comment]
Buongiorno,

ne stavamo parlando appunto ieri nel nostro team.
Il documento citato riporta anche :
`Nei casi in cui in fattura sia presente il solo IDCessionarioCF per il cessionario, si risale all’ IDCessionarioPIVA attraverso interrogazione di Anagrafe Tributaria.`

Di conseguenza eravamo arrivati a dire che fare il controllo preventivamente poteva evitare degli scarti da parte dello SdI.
Ai nostri clienti abbiamo suggerito di fare dei TD27 indicando anche la p iva.
Cosa ne pensate ?

**Comment by exolabsrl** [comment]
Buongiorno @tanogae,

per quanto mi riguarda, in assenza del IDCessionarioPIVA rimando il controllo allo SDI che eventualmente scarta la fattura (è pressoché impossibile controllare preventivamente in Anagrafe Tributaria); obbiettivamente, emettere una fattura specificando solo il codice fiscale del cessionario, presuppone che questo sia una persona fisica quindi il tuo suggerimento mi sembra più che corretto.

**Comment by tanogae** [comment]
Rimane aperto il dubbio su come gestire il caso dell'autoconsumo tra titolare di partita iva e privato. 
Non possibile con TD01 per il controllo 00471 e nemmeno con TD27 per il controllo 00472.
