### ISSUE TITLE
Controllo 00472

### ISSUE THREAD

**Issue by tanogae** [FatturaElettronica/FatturaElettronica.NET#388]
Ciao ,

abbiamo riscontrato la seguente esigenza da parte dei nostri utenti: _inviare una fattura a se stesso come privato. 
Es. ditta individuale che si fattura un prodotto._ 

Prima della versione 1.7.1 ciò era possibile facendo un semplice TD01 ora invece abbiamo consigliato a tutti di fare un TD27.
Il TD27 però ha un controllo che impone che cedente e cessionario siano uguali.

Abbiamo verificato con il software dell'agenzia e questo permette l'invio del TD27 indicando CF e PIVA per il cedente e solo CF per il cessionario. Apparentemente il controllo sembra violato, ma in realtà in assenza della PIVA del cessionario lo SdI accede all'anagrafe tributaria per reperire il dato e verificare la validità della regola.
Inviando la fattura in questo modo questa viene recapitata al cessionario come privato e non come azienda, questa è la reale esigenza dell'utente.

Pertanto credo che il controllo 00472 dovrebbe essere modificato solo per il TD27 verificando la sola uguaglianza del CF.

@nicolaiarocci sei d'accordo ?

**Comment by nicolaiarocci** [comment]
Sì: confermato, implementato e rilasciato. Grazie.
