### ISSUE TITLE
NullReferenceException sul validatore 00471 quando il CessionarioCommittente non ha partita IVA

### ISSUE THREAD

**Issue by marcominerva** [FatturaElettronica/FatturaElettronica.NET#389]
L'eccezione viene generata qui: https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/v3.4.6/Validators/FatturaOrdinariaValidator.cs#L119

**Comment by nicolaiarocci** [comment]
Ciao Marco :-) Stai preparando una PR?

**Comment by marcominerva** [comment]
Se posso contribuire al progetto, volentieri 😀 Anche il CedentePrestatore potrebbe non avere la partita Iva? Chiedo perché, nel caso in cui non la abbia né il Prestatore né il committente, la validazione deve passare oppure no?

**Comment by nicolaiarocci** [comment]
A memoria il CedentePrestatore ha IdFiscaleIva obbligatorio. Direi che basta saltare il controllo 471 se CessionarioCommittente non ha IdFiscaleIva.

**Comment by uomofocaccina** [comment]
Ciao, il dato è obbligatorio. Personalmente quando ho dei dubbi consulto le "sacre tavole"..  https://www.fatturapa.gov.it/export/documenti/fatturapa/v1.2.2/RappresentazioneTabellareFattOrdinaria_v1.2.2.xlsx

**Comment by marcominerva** [comment]
Grazie ad entrambi, mando una Pull Request al più presto.

**Comment by nicolaiarocci** [comment]
Vedi# 391
