### ISSUE TITLE
Definire le proprietà come "get only"

### ISSUE THREAD

**Issue by marcominerva** [FatturaElettronica/FatturaElettronica.NET#391]
Nel modello ad oggetti, esistono numerose proprietà che sono oggetti complessi e che tipicamente vengono istanziate nei vari costruttori, ad esempio nel caso del **CedentePrestatore**: https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/Ordinaria/FatturaElettronicaHeader/CedentePrestatore/CedentePrestatore.cs#L17-L21.

Queste proprietà, tuttavia, sono di tipo get/set, quindi teoricamente possono essere impostate a **null** via codice, cosa che scatena errori di tipo **NullReferenceException** durante la validazione. Mi chiedo se è possibile modificarle in modo da renderle **get only**, perché se comunque si lasciano vuote, ci sono poi i validatori che si occuperanno di segnalare il problema.

**Comment by nicolaiarocci** [comment]
Il motivo per cui esistono i setter è che a suo tempo ho ritenuto interessante che si potesse eventualmente creare una istanza, poniamo, di `CedentePrestatore` a sè stante, compilarla, convalidarla, ed eventualmente in seguito assegnarla ad una `FatturaOrdinaria`. Il mio workflow non lo richiedeva (come il 99% di noi alla fine finisco per de/serializzare fatture esistenti), ma mi piaceva lasciare aperta questa opzione.

Tutto ciò lascia aperto il varco, ovviamente, ad errori come quello da te segnalato in #389. In effetti, la PR risolve solo apparentemente il problema: se davvero viene lasciato `IdFiscaleIVA` a null, poi altri validatori impazziscono (prova ad aggiungere il caso al test sul 00471 e vedrai). Mi sembra però un caso molto raro/improbabile, considerando che, come noti, in effetti le proprietà *sono* valorizzate di default: perchè qualcuno dovrebbe volerle forzare a null?

La soluzione che proponi chiuderebbe il cerchio ma impedirebbe il workflow a cui accennavo. Opinioni?

**Comment by aferende** [comment]
Concordo con Nicola.
Tra l'altro la modifica metterebbe a rischio la compatibilità con software
già in essere e che fanno set di queste proprietà.
Io lascerei così com'è.

Il giorno mar 29 nov 2022 alle ore 09:18 Nicola Iarocci <
***@***.***> ha scritto:

**Comment by marcominerva** [comment]
Certo, capisco benissimo le motivazioni. La mia era solo una considerazione dal punto di vista della "robustezza" del codice, che tra l'altro risponde proprio ad una frase di @nicolaiarocci:

> Mi sembra però un caso molto raro/improbabile, considerando che, come noti, in effetti le proprietà sono valorizzate di default: perchè qualcuno dovrebbe volerle forzare a null?

Non avendo effettivamente senso che le proprietà siano valorizzate a `null`, tipicamente si adottano due soluzioni:

1. Si elimina il setter della proprietà;
2. Si aggiunge un controllo nel setter della proprietà, per cui se si tenta di impostare a `null`, si ottiene una eccezione parlante, che dice chiaramente che la proprietà non può essere impostata a `null`.

La soluzione 1 sarebbe sicuramente la più robusta, ma impedirebbe gli scenari di cui parlava @nicolaiarocci e introdurrebbe delle breaking changes, come evidenziato da @aferende. Quindi probabilmente si potrebbe pensare di adottare la seconda soluzione. Ovviamente il lavoro non è poco, qui va valutato.

**Comment by nicolaiarocci** [comment]
Tutto considerato, penso sia meglio lasciare le cose come stanno. Almeno per il momento. Chiudo sia questo ticket che i collegati. Siamo sempre in tempo a intervenire in futuro, dovesse rivelarsi  un problema più importante di quel che pensiamo.
