### ISSUE TITLE
Org.BouncyCastle.Cms.CmsException: 'Malformed content.'

### ISSUE THREAD

**Issue by SergioRonchi** [FatturaElettronica/FatturaElettronica.NET#392]
Salve,
Sto usando il sorgente del codice per un progetto. Probabilmente non l'ultimissima versione.
Per quanto riguarda le fatture firmate su alcune fatture, non tutte, ottengo questo errore.
Org.BouncyCastle.Cms.CmsException: 'Malformed content.'

Che penso siano dovute al componente usato.
Allego una fattura che da errore
[IT01336610587_0MXtw.xml.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/10434470/IT01336610587_0MXtw.xml.zip)

**Comment by SergioRonchi** [comment]
Ho aggiornato la versione della libreria.
Il problema che il progetto è .Net Framework e non .Net Standard.

Da sempre lo stesso errore sullo stesso tipo di fattura.
In realtà ieri ha funzionato inzialmente, ma poi c'erano delle incompatibilità sulle versioni delle dipendenze, ora che sembrano a posto le dipendenze mi da come errore
'unknown object in factory: Org.BouncyCastle.Asn1.DerApplicationSpecific'

Probabilmente mi serve una versione per .Net Framework

**Comment by aferende** [comment]
Io il test l'ho fatto da una console application in .NET Framework 4.7.2,
con in riferimento il package Fattura elettronica.NET che .net Standard (e
qui non ci sono problemi di compatibilità).
Che framework stai utilizzando nell'applicazione host?

Il mer 18 gen 2023, 17:43 Sergio Ronchi ***@***.***> ha
scritto:

**Comment by SergioRonchi** [comment]
ottengo sempre lo stesso errore nel metodo
ReadXmlSigned la versione che accetta cole parametro il nome del file.

Non ho provato la versione che accetta lo Stream

**Comment by SergioRonchi** [comment]
Forse devo usare la ReadXmlSignedBase64 ?

**Comment by SergioRonchi** [comment]
Ok ho capito il problema.

Io ho N fatture dentro uno zip.
La mia applicazione estrae dallo zip i vari file ma come stream, non li salva su file.
Alcuni dei file contenuti nello zip sono semplici xml, altri sono .p7m in chiaro e altri ancora .p7m codificati in base64.
Avendo degli stream non posso usare ReadXmlSignedBase64 che accetta solo il path del file.
Comunque penso di poter risolvere in qualche modo convertendo da base prima.

Grazie per la disponibilità
