### ISSUE TITLE
System.Text.Json

### ISSUE THREAD

**Issue by VincenzoBijoux** [FatturaElettronica/FatturaElettronica.NET#393]
Salve,
sto utilizzando la libreria FatturaElettronica in un progetto VS19 per pre-validare le fatture prima di inviarle.
Utilizzavo la versione 3.0.1. Adesso cercando di aggiornarla all'ultima release 3.4.6 ricevo l'errore:

"System.IO.FileNotFoundException: 'Non è stato possibile caricare il file o l'assembly 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' o una delle relative dipendenze. Impossibile trovare il file specificato.'"

La compilazione della soluzione salva la libreria sia nella cartella debug che nella release, non capisco perchè la "Version=6.0.0.0" ?

Ho istallato gli aggiornamenti dalla Ui di visual studio 2019 con la gestione dei packages NuGet e mi sono assicurato che tutti i pacchetti richiesti dalla versione della dll fossero aggiornati, tra cui anche la System.Text.Json che risulta alla versione 7.0.2.

La mia applicazione che utilizza FatturaElettronica.ddl è sviluppata in vb19 con .net framework 4.7.2 e la sto testando su Windows11 (
ho provato a farla girare anche nella Sandbox ma con lo stesso errore).

Pensando che fosse un problema della mia applicazione ho generato una nuova soluzione con un progetto "libreria di classi (.Net Framework), ho semplicemente importato i packages NuGet e scritto alcune righe di codice in C# che richiamassero la libreria FatturaElettronica.dll, ma ricevo lo stesso errore.

Facendo il downgrade alla versione 3.2.0, l'ultima senza la libreria incriminata, il test funziona.

Dove sto sbagliando ?
Vi ringrazio anticipatamente per l'aiuto, buon we.

In allegato:

App.config
[App.Config.txt](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/10949014/App.Config.txt)
Output del debug del test con msg errore
[Debug.txt](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/10948979/Debug.txt)
Screenshot riferimenti progetto
![Riferimenti](https://user-images.githubusercontent.com/127615705/224502615-62a13e6d-7981-4548-933d-354fbbc2a62d.JPG)
Screenshot packages incorporati
![Packages](https://user-images.githubusercontent.com/127615705/224502636-bbbc09b0-5fc6-492f-8173-765966955ede.JPG)

**Comment by nicolaiarocci** [comment]
Hai provato a portare System.Text.Json alla ver 6.0.x?

**Comment by ludev** [comment]
ho avuto lo stesso proble con framework 4.8 e ho risoloto aggiungendo in app.config

<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.7" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
