### ISSUE TITLE
<PrezzoTotale> in presenza di uno sconto percentuale

### ISSUE THREAD

**Issue by TheRealBoiler** [FatturaElettronica/FatturaElettronica.NET#394]
Il cacolo del PrezzoTotale, per i controlli dell'Agenzia delle Entrate, ha una tolleranza in presenza di uno sconto di 0,01.
Per la precisione questo calcolo:
(PrezzoUnitario ± ScontoMaggiorazione) * Quantita

Nel metodo Validate della classe FatturaOrdinariaValidator questa tolleranza non è considerata.
Risulterebbe quindi errata una fattura che in realtà l'Agenzia accetterebbe.

**Comment by nicolaiarocci** [comment]
Ciao, grazie per la segnalazione. Ad una rapida occhiata mi pare la tolleranza sia contemplata [qui](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/Validators/DettaglioLineeValidator.cs#L56), mentre non trovo una convalida del PrezzoTotale in FatturaOrdinariaValidator. Potresti indicarmi con precisione dove pensi non funzioni bene? Oppure fare una pull request con un test che fallisce, sarebbe ancora meglio. Grazie.

**Comment by TheRealBoiler** [comment]
Salve, grazie per la velocissima risposta !

 

Posso fornirle un xml che fallisce il test (ho rimosso i dati sensibili inserendo partite iva di società di pubblico dominio).

In realtà la cosa è abbastanza strana perché da un controllo più approfondito sembrerebbe fallire il controllo solo sulla riga15 quando in realtà questo problema (0,01 di differenza) è presente sulle righe: 7-8-15-19-20 e 21.

Sinceramente non ci vedo alcuna differenza se non che la 15 otterrebbe come prezzo scontato una cifra molto molto piccola rispetto alle altre.

In ogni modo di nuovo grazie per l’interessamento !

 

 

Da: Nicola Iarocci ***@***.***> 
Inviato: lunedì 3 aprile 2023 17:26
A: FatturaElettronica/FatturaElettronica.NET ***@***.***>
Cc: Andrea ***@***.***>; Author ***@***.***>
Oggetto: Re: [FatturaElettronica/FatturaElettronica.NET] <PrezzoTotale> in presenza di uno sconto percentuale (Issue #394)

 

Ciao, grazie per la segnalazione. Ad una rapida occhiata mi pare la tolleranza sia contemplata qui <https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/Validators/DettaglioLineeValidator.cs#L56> , mentre non trovo una convalida del PrezzoTotale in FatturaOrdinariaValidator. Potresti indicarmi con precisione dove pensi non funzioni bene? Oppure fare una pull request con un test che fallisce, sarebbe ancora meglio. Grazie.

**Comment by nicolaiarocci** [comment]
Va bene l'xml, puoi postarlo direttamente qui.

**Comment by TheRealBoiler** [comment]
Ecccolo qua
[IT12429590966_103JD.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/11146304/IT12429590966_103JD.zip)

**Comment by nicolaiarocci** [comment]
Interessante. Per la linea 15 il delta è superiore a 1 centesimo (0,012) eppure viene accettata da SDI.

**Comment by TheRealBoiler** [comment]
Io temo che i nostri amici dell'Agenzia abbiano un arrotondamento sulla tolleranza... 0,012 = 0,01 - 0,014 = 0,01 - 0,015 = 0,02 ...
Pensando male a volte ci si azzecca 😄

**Comment by sgardini** [comment]
Non è pensare male. Funziona esattamente così.

**Comment by sgardini** [comment]
Ricordiamo anche che sui totali la tolleranza è 'ampia'
somma dei prezziTotali iva + cassa previdenziale ± arrotondamenti deve essere uguale al totaleImponibile con uno scarto di ±1 euro
