### ISSUE TITLE
Nuove specifiche tecniche - imposta di bollo - marzo 2023

### ISSUE THREAD

**Issue by aferende** [FatturaElettronica/FatturaElettronica.NET#395]
https://www.agenziaentrate.gov.it/portale/imposta-di-bollo-sulle-fatture-elettroniche

Qui il PDF di dettaglio: https://www.agenziaentrate.gov.it/portale/documents/20143/3394067/Guida_Bollo_sulle_fatture_elettroniche.pdf/4aacfaa2-5ada-e8d5-8f1c-6b61f25923a8

@nicolaiarocci sono previsti aggiornamenti sul componente in tal senso?

**Comment by nicolaiarocci** [comment]
Ciao, ad una rapida occhiata non mi pare ci sia nulla da fare.
