### ISSUE TITLE
Validazione dati anagrafici per TD21 & TD27

### ISSUE THREAD

**Issue by TheRealBoiler** [FatturaElettronica/FatturaElettronica.NET#396]
Perdono ma non sono molto pratico con le pull requests (prometto di studiarmi la cosa) 😄 

Nel file FatturaOrdinariaValidator.cs
Il metodo:
 private static bool FatturaValidateAgainstError00472(FatturaOrdinaria fatturaOrdinaria)

dovrebbe essere così:

    private static bool FatturaValidateAgainstError00472(FatturaOrdinaria fatturaOrdinaria)
        {
            var bodies =
                fatturaOrdinaria.FatturaElettronicaBody.Where(x =>
                    x.DatiGenerali.DatiGeneraliDocumento.TipoDocumento is "TD21" or "TD27");

            if (!bodies.Any())
                return true;

            var cedente = fatturaOrdinaria.FatturaElettronicaHeader.CedentePrestatore.DatiAnagrafici;
            var cessionario =
                fatturaOrdinaria.FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici;

            if (cessionario.IdFiscaleIVA.IsEmpty() && cessionario.CodiceFiscale == cedente.CodiceFiscale)
                // Vedi https://github.com/FatturaElettronica/FatturaElettronica.NET/issues/388
                return true;

            if (cessionario.CodiceFiscale.IsEmpty() && cessionario.IdFiscaleIVA.ToString() == cedente.IdFiscaleIva.ToString())
                return true;
            
            return cedente.IdFiscaleIVA?.ToString() == cessionario.IdFiscaleIVA?.ToString() &&
                   cedente.CodiceFiscale == cessionario.CodiceFiscale;
        }

L'agenzia passa una fattura di tipo TD21 o TD27 dove l'id fiscale corrisponde anche se sul cessionario è assente il codice fiscale mentre sul cedente è presente. Non sono sicuro del contrario (codice fiscale fiscale presente sul cessionario ma assente sul cedente).

Allego file di esempio per verificare la situazione.
[IT02078160997_15TYF.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/11297972/IT02078160997_15TYF.zip)

**Comment by nicolaiarocci** [comment]
Grazie per la segnalazione.
