### ISSUE TITLE
Scarto Fattura se presenta uno sconto a 3 cifre decimali 

### ISSUE THREAD

**Issue by FrancescoMiconi** [FatturaElettronica/FatturaElettronica.NET#401]
Buongiorno, 
ho ricevuto uno scarto da parte dell'ADE su una fattura che ho inviato con uno sconto a percentuale sulla riga, a 3 cifre decimali.
Il Validator di riga invece non segnala anomalie.
Suppongo che il modo più semplice per aggirare l'errore sia effettuare lo sconto a Importo? Proverò a breve.. 
Se qualcuno ha dei suggerimenti sono ben accetti.

Grazie Mille

Errore 00200 : file non conforme al formato : the value '14.286' of element 'percentuale' is not valid.
riga: 96 - colonna: 54
Suggerimento verificare che i campi contenuti nel file inviato rispettino caratteristiche formali e ordine di rappresentazione previsti dal tracciato fattura

**Comment by nicolaiarocci** [comment]
grazie per la segnalazione. La v3.4.10 (su nuget tra qualche minuto) dovrebbe intercettare questo problema.
