### ISSUE TITLE
firma del xml

### ISSUE THREAD

**Issue by tecnonik01** [FatturaElettronica/FatturaElettronica.NET#402]
Buongiorno, all'interno della libreria esiste un metodo per firmare xml con certificato PEM?

**Comment by nicolaiarocci** [comment]
Dai una occhiata al namespace `FatturaElettronica.Extensions`, vedi la [API Reference](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/08bd06931029d102267f7b380efbc55be2e13e84/Extensions/SignedFileExtensions.cs/#L80).
