### ISSUE TITLE
 dettaglioLinee.NumeroLinea a 0 Errore

### ISSUE THREAD

**Issue by FrancescoMiconi** [FatturaElettronica/FatturaElettronica.NET#403]
Provando ad inserire 0 come numero linea lo SDI scarta la fattura.

Report SDI

file non conforme al formato : value '0' is not facet-valid with respect to mininclusive '1' for type 'numerolineatype'.
riga: 76 - colonna: 45
Suggerimento verificare che i campi contenuti nel file inviato rispettino caratteristiche formali e ordine di rappresentazione previsti dal tracciato fattura
Errore 00200 : file non conforme al formato : the value '0' of element 'numerolinea' is not valid.
riga: 76 - colonna: 45
Suggerimento verificare che i campi contenuti nel file inviato rispettino caratteristiche formali e ordine di rappresentazione previsti dal tracciato fattura

**Comment by nicolaiarocci** [comment]
Grazie. Verificando le specifiche pare che i valori consentiti per `NumeroLinea` siano 1-9999
