### ISSUE TITLE
file di test rilasciato con pacchetto nuget (.github\workflows\test.yml)

### ISSUE THREAD

**Issue by Lukino2000** [FatturaElettronica/FatturaElettronica.NET#404]
ciao,
ho notato che c'è, credo, un file di troppo rilasciato... infatti nel csproj hai lasciato:

```
<ItemGroup>
  <Content Include=".github\workflows\test.yml" />
</ItemGroup>
```

era tua intenzione o è una svista?

**Comment by nicolaiarocci** [comment]
ciao @Lukino2000 direi al 99,9999% una svista :-)

**Comment by nicolaiarocci** [comment]
ah mi serve per avere il file caricato col progetto in Rider... approfondisco.

**Comment by michaelmairegger** [comment]
Sarebbe possibile importare il file come contenuto di una cartella della soluzione
![image](https://github.com/FatturaElettronica/FatturaElettronica.NET/assets/4341039/c189747b-0f11-44bf-8449-f9b79e3a30ed)
