### ISSUE TITLE
Come si può leggere il codice valore.

### ISSUE THREAD

**Issue by pagurooperoso** [FatturaElettronica/FatturaElettronica.NET#406]
Buonasera, Complimenti per il progetto

Con questa classe non riesco a leggere il valore CodiceValore, come posso fare??

Qui sotto un breve esempio.

<DatiBeniServizi>
<DettaglioLinee>
<NumeroLinea>1</NumeroLinea>
<CodiceArticolo>
<CodiceTipo>Codice Art. fornitore</CodiceTipo>
<CodiceValore>CodArt</CodiceValore>
</CodiceArticolo

**Comment by nicolaiarocci** [comment]
`fatturaOrdinaria.FatturaElettronicaBody[0].DatiBeniServizi.DettaglioLinee[0].CodiceArticolo[0].CodiceValore`
