### ISSUE TITLE
Specifiche tecniche v1.8

### ISSUE THREAD

**Issue by nicolaiarocci** [FatturaElettronica/FatturaElettronica.NET#407]
In vigore dal 1 Febbraio 2024, vedi: https://www.agenziaentrate.gov.it/portale/web/guest/specifiche-tecniche-versione-1.8

**Comment by uomofocaccina** [comment]
- Introdotta nuova codifica per il blocco AltriDatiGestionali per produttori agricoli in regime speciale
- Introdotto controllo per lo scarto di fatture con dichiarazione d'intento invalidata 00477
- Aggiornate le indicazioni per l’utilizzo del TD28 per operazioni verso e da soggetti non stabiliti in Italia
- Integrata la descrizione dell’IdPaese nei DatiAnagrafici del CedentePrestatore

**Comment by aferende** [comment]
Grazie Nicola.
Aggiungo anche questo link che descrive in modo semplice i cambiamenti in
arrivo:

https://www.fiscoetasse.com/rassegna-stampa/34917-fatture-elettroniche-nuove-specifiche-tecniche-dal-1-febbraio-2024.html


Il mar 19 dic 2023, 11:09 Nicola Iarocci ***@***.***> ha
scritto:

**Comment by nicolaiarocci** [comment]
a una rapida occhiata non mi è chiaro cosa ci sia da fare:

- Il controllo 00477  mi sembra lato server ("dichiarazione di intento invalidata") e fa riferimento, di fatto, alla prima voce dell'elenco novità ("nuova codifica per il blocco AltrDatiGestionali");
- TD28 mi pare che abbiano documentato meglio quando/come usarlo, ma nulla da fare in convalida?
- Per idPaese, non capisco cosa abbiano fatto esattamente ma dal burocratese mi par di capire che anche qui hanno migliorato la documentazione.

Nulla da fare in FE.net dunque?

**Comment by aferende** [comment]
Anche secondo me c'è poco e niente da modificare.

Come contributo alla causa, ho utilizzato questo tool online per fare un confronto tra le 2 specifiche in formato PDF:
https://draftable.com/compare/KSzErJNjfyWB 

Ho evidenziato le differenze in questo PDF riassuntivo che allego al thread

[Confronto specifiche SDI 1.7.1 - 1.8.0.pdf](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/13727124/Confronto.specifiche.SDI.1.7.1.-.1.8.0.pdf)

**Comment by uomofocaccina** [comment]
Da una prima occhiata, secondo me c'è da cambiare [questo](https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/6d6dfcb9041d9748e3772064c45ca9405c0e3223/Validators/FatturaOrdinariaValidator.cs#L78). 
Altro non mi sembra.

**Comment by nicolaiarocci** [comment]
@uomofocaccina ti va di proporre una pull request?
