### ISSUE TITLE
Tipo TD27 non convalida caso di ditta individuale che trasferisce al titolare persona fisica

### ISSUE THREAD

**Issue by sgardini** [FatturaElettronica/FatturaElettronica.NET#409]
Se devo fare un tipo TD27 da ditta individuale a persona fisica titolare, caso tipico la vendita dei cespiti a fine attività, la convalida di ditta individuale con partita iva e codice fiscale non viene considerata uguale a persona fisica col medesimo codice fiscale.
Situazione reale testata con invio a SDI andato a buon fine.
Quindi andrebbe migliorato il controllo, se il cessionario/committente ha solo il codice fiscale il controllo di equivalenza va fatto sul solo codice fiscale e non va coinvolta la partita iva. Se invece il cessionario/committente ha la partita iva il controllo può essere fatto anche solo sulla stessa, come ora. Questo l'esito della convalida

Proprietà, Codice, Messaggio
00472, I valori TD21 e TD27 del tipo documento non ammettono l’indicazione in fattura di un cedente diverso dal cessionario

**Comment by uomofocaccina** [comment]
Per esempio un TD27 con:
CedentePrestatore
`<DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>IT</IdPaese>
          <IdCodice>57432780054</IdCodice>
        </IdFiscaleIVA>
        <CodiceFiscale>CRRMTT77M21G999U</CodiceFiscale>
        <Anagrafica>
          <Denominazione>Ditta individuale test</Denominazione>
        </Anagrafica>
        <RegimeFiscale>RF01</RegimeFiscale>
      </DatiAnagrafici>`

e CessionarioCommittente
`<DatiAnagrafici>
        <CodiceFiscale>CRRMTT77M21G999U</CodiceFiscale>
        <Anagrafica>
          <Denominazione>persona fisica test</Denominazione>
        </Anagrafica>
      </DatiAnagrafici>`
      
Giusto?

**Comment by sgardini** [comment]
Esattamente. Caso infrequente ma a noi è capitato.

**Comment by uomofocaccina** [comment]
Ciao,
Ho fatto una prova scrivendo un test e mi sembra già a posto.. 

        public void TestTd27_Issue_409()
        {
            var cedente = Challenge.FatturaElettronicaHeader.CedentePrestatore.DatiAnagrafici;
            var cessionario = Challenge.FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici;

            var body = new FatturaElettronicaBody();
            body.DatiGenerali.DatiGeneraliDocumento.TipoDocumento = "TD27";
            Challenge.FatturaElettronicaBody.Add(body);

            cedente.IdFiscaleIVA = new IdFiscaleIVA { IdPaese = "IT", IdCodice = "345" };
            cedente.CodiceFiscale = "123";
            cessionario.CodiceFiscale = "123";
            Assert.IsNull(Challenge.Validate().Errors.FirstOrDefault(x => x.ErrorCode == "00472"));

        }

**Comment by nicolaiarocci** [comment]
Probabilmente risolto con #396

**Comment by sgardini** [comment]
Confermo che #396 risolve il problema, il mio problema si era evidenziato su versione precedente

**Comment by nicolaiarocci** [comment]
grazie @uomofocaccina per il triage.
