### ISSUE TITLE
FluentValidation signed packages are deprecated and no longer updated

### ISSUE THREAD

**Issue by devalot76** [FatturaElettronica/FatturaElettronica.NET#41]
Perché è stata utilizzata questa versione se non viene più aggiornata?

**Comment by nicolaiarocci** [comment]
Perché occorreva una versione signed per questo progetto (che è signed a sua volta)

**Comment by nicolaiarocci** [comment]
Ora FatturaElettronica non è più signed. Tuttavia per poter targettare NET Standard (e quindi il package FluentValidation non-signed) è necessario attendere la v2.0 del Net Standard che supporterà anche System.Xml.
