### ISSUE TITLE
Ordine dei tag

### ISSUE THREAD

**Issue by MarcoBottini72** [FatturaElettronica/FatturaElettronica.NET#412]
Buongiorno,
abbiamo notato che la validazione dell'XML non tiene in considerazione il fatto che lo SDI esige che l'ordine dei tag sia come da documentazione.
Alcuni XML risultano validi, mentre, una volta inviati allo SDI, vengono rifiutati.
Un esempio è legato alla Quantità nel Dettaglio Linee, che se non è nella posizione corretta, lo SDI rifiuta l'XML.
Grazie.

**Comment by nicolaiarocci** [comment]
La libreria attualmente convalida l'istanza risultante dalla deserializzazione del XML. Immagino che XSD contenga regola di convalida dell'ordinamento. Per ottenere il risultato in FE.NET occorrerebbe un layer di validazione XML basato sullo schema XSD, vedi https://learn.microsoft.com/en-us/dotnet/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset.

**Comment by nicolaiarocci** [comment]
Ecco un adattamento dell'esempio linkato qui sopra che funziona con una fattura elettronica (riporta correttamente errore se Quantità non è nella posizione corretta):

```cs
using System.Xml;
using System.Xml.Schema;

class XmlSchemaSetExample
{
    static void Main()
    {
        var readerSettings = new XmlReaderSettings();
        // xmldsig-core-schema.xsd va scaricato da https://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd
        readerSettings.Schemas.Add("http://www.w3.org/2000/09/xmldsig#",
            XmlReader.Create("xmldsig-core-schema.xsd", new() { DtdProcessing = DtdProcessing.Ignore }));
        readerSettings.Schemas.Add("http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2",
            "Schema_VFPR12 v1.8.xsd");
        readerSettings.ValidationType = ValidationType.Schema;
        readerSettings.ValidationEventHandler += SettingsValidationEventHandler;

        XmlReader books = XmlReader.Create("IT01234567890_FPR02.xml", readerSettings);

        while (books.Read())
        {
        }
    }

    static void SettingsValidationEventHandler(object sender, ValidationEventArgs e)
    {
        if (e.Severity == XmlSeverityType.Warning)
        {
            Console.Write("WARNING: ");
            Console.WriteLine(e.Message);
        }
        else if (e.Severity == XmlSeverityType.Error)
        {
            Console.Write("ERROR: ");
            Console.WriteLine(e.Message);
        }
    }
}
```

Per il momento non ritengo valga la pena inserire questo fase di pre-flight nella libreria, anche perchè avrebbe senso solo per alcuni extension method.
