### ISSUE TITLE
Remove Portable.BouncyCastle dependency from the lib

### ISSUE THREAD

**Issue by tapaolo** [FatturaElettronica/FatturaElettronica.NET#414]
Hi,

Great job with the lib! We would like to use it in our project, but we encountered a potential blocker: the Portable.BouncyCastle dependency.

While Portable.BouncyCastle is an excellent library, it feels somewhat complex for this simple lib, and it adds over 3MB to our deployment (it’s even larger than EF Core!).

We noticed that Portable.BouncyCastle is primarily used to parse and validate the signature of a signed XML e-invoice file.

In light of that, I tried to achieve this without relying on BouncyCastle.

 I ended up with the following code:

```
        public static MemoryStream ParseSignature(Stream stream, bool validateSignature)
        {
            static byte[] ReadAllBytes(Stream stream)
            {
                if (stream is MemoryStream mem)
                    return mem.ToArray();

                using MemoryStream ms = new MemoryStream();
                byte[] buffer = new byte[8192];
                int bytesRead;

                while ((bytesRead = stream.Read(buffer, 0, buffer.Length)) > 0)
                    ms.Write(buffer, 0, bytesRead);

                return ms.ToArray();
            }

            var fileContent = ReadAllBytes(stream);
            ContentInfo content = new ContentInfo(fileContent);
            var signedFile = new SignedCms(SubjectIdentifierType.IssuerAndSerialNumber, content, false);
            signedFile.Decode(fileContent);

            if (validateSignature)
            {
                try
                {
                    signedFile.CheckSignature(true);
                }
                catch (CryptographicException ce)
                {
                    throw new SignatureException(Resources.ErrorMessages.SignatureException, ce);
                }
            }

            MemoryStream memoryStream = new MemoryStream();
            memoryStream.Write(signedFile.ContentInfo.Content, 0, signedFile.ContentInfo.Content.Length);
            return memoryStream;
        }
```

The ten unit tests turn green, but apart from this, I don't have any other reliable way to test the implementation. 
Is this enough to submit a PR or do I need to perform more tests (suggestion appreciated!) ?

**Comment by nicolaiarocci** [comment]
Looks good to me. Please submit a PR, I'll be happy to assist moving it forward.

**Comment by tapaolo** [comment]
Submitted as #415

**Comment by tapaolo** [comment]
Hi @nicolaiarocci ,
When do you think you will release this on NuGet?

**Comment by nicolaiarocci** [comment]
Hey, thanks. It's out now.
