### ISSUE TITLE
Signature Validation behavior change 3.4.15 to 3.4.16

### ISSUE THREAD

**Issue by Delta-38** [FatturaElettronica/FatturaElettronica.NET#418]
Hi I am in the process of updating a project that uses FatturaElettronica.NET to 3.4.16. 
I noticed that one of my tests started failing after updating. 

Repro: 
Feeding an xml.p7m invoice with a signature issue, with the validation enabled to 
**SignedFileExtensions.ParseSignature(path, true);**
Expected behavior: 
SignatureException thrown by SignedFileExtensions.ParseSignature with message: "Una firma non corrisponde al certificato contenuto nel file" 
Actual behavior:
The new version doesn't throw any error and returns the invoice contents.

Notes:
I'd mostly like to know if Signature Validation is now more permissive, if I'm dealing with a flaky test file or otherwise before I go forwards.

I can provide the file if needed for investigating.

Thanks in advance,
Paolo Manili

**Comment by nicolaiarocci** [comment]
Id' say a conseguence of #414. @tapaolo would you be willing to chime in?

**Comment by tapaolo** [comment]
Hi folks,

The main difference between the current implementation and the BouncyCastle one is that the latter used to always verify both the digital signatures of the XML file and the signers' certificates (including, perhaps, the purposes of the certificates). Now, it only checks the digital signature of the xml file.

I chose this approach mainly for two reasons:

1. I didn't have a valid certificate to ensure all tests passed successfully.
2. I thought that, while the new implementation is technically more permissive, I wasn’t sure if it made sense, for the purposes of this library, to validate the entire certificate chain.

Nevertheless, with a valid certificate, I think it should be straightforward to restore the previous - more restrictive - behavior by simply passing false to the SignedCms.CheckSignature method in Extensions/SignedFileExtensions.cs.

**Comment by nicolaiarocci** [comment]
Thanks @tapaolo.
