### ISSUE TITLE
Ricevo errore nella lettura di alcune FE con estensione p7m

### ISSUE THREAD

**Issue by FrancescoMiconi** [FatturaElettronica/FatturaElettronica.NET#421]
Con vecchie versioni del framework 4.7 non ho mai avuto questo problema, adesso che ho migrato a net 8 sto riscontrando questo errore nel momento in cui eseguo la lettura della fattura:

fattura = FatturaElettronica.Ordinaria.FatturaOrdinaria.CreateInstance(Instance.Privati);
 
 fattura.ReadXmlSigned(pathFileP7m, false);

L'errore che mi viene generato è:

System does not support 'windows-1252' encoding. Line 1, position 31.

Al momento ho installato l'ultima versione  3.5.1, ma ho provato anche con la 3.4.10 che avevo prima, ma con l'ambiente attuale ( net 8) ottengo ugualmente errore.

Grazie per il supporto

**Comment by FrancescoMiconi** [comment]
sembra che ho risolto impostando nella parte iniziale del programma questo codice
 
// Register the code pages provider to support 'windows-1252' and other code pages
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

questo sembrerebbe il motivo

The error you're encountering occurs because .NET 8 no longer supports the default use of some older encodings, like windows-1252. To handle these encodings in .NET 8, you need to register a code page provider using the System.Text.Encoding.CodePages library.

**Comment by nicolaiarocci** [comment]
Grazie, era un problema che era capitato [in passato](#333). La tua soluzione mi sembra la migliore, tanto che probabilmente andrebbe messa nelle FAQ.
