### ISSUE TITLE
Errore Prezzo non calcolato secondo le specifiche

### ISSUE THREAD

**Issue by gptucci** [FatturaElettronica/FatturaElettronica.NET#45]
Ciao
Grande lavoro ! Posso contribuire in qualche modo ???
Usando la libreria per alcune fatture (Ve ne allego una) ho un'errore che non comprendo
Prezzo non calcolato secondo le specifiche tecniche.
E' un errore ??

Grazie e bravissimi

**Comment by gptucci** [comment]
Allegato
[it05262890014_1mrdv.zip](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/1000797/it05262890014_1mrdv.zip)

**Comment by gptucci** [comment]
Ciao
Forse ho trovato il problema, ma potrei sbagliarmi. Mi permetto di sottoporre un tentativo di soluzione
Il problema è negli arrotondamenti in DettaglioLineeValidator
Modifica applicata in PrezzoTotaleValidateAgainstError00423
...
 return Math.Round(challenge.PrezzoTotale,2, MidpointRounding.AwayFromZero) == Math.Round((decimal)(prezzo * (challenge.Quantita ?? 1)), 2, MidpointRounding.AwayFromZero);
....
Grazie

**Comment by nicolaiarocci** [comment]
Ciao, che versione di FatturaElettronica.NET state usando?

**Comment by gptucci** [comment]
Ciao
L’ultimo grido: 0.6.1
Ma ti ho mandato un mio tentativo di correzione

Grazie ancora e complimenti


Giampaolo Ing. TUCCI
Trilogik Soluzioni Informatiche s.r.l.
C.so De Stefanis 6/1 Sc. A - 16139 Genova
Tel. 010 88.49.21 - Fax. 010 89.87.879
g.tucci@trilogik.it<mailto:g.tucci@trilogik.it%0d>
www.trilogik.it<http://www.trilogik.it/>

Ai sensi del D.Lgs.196/2003 si precisa che le informazioni contenute nel presente messaggio sono riservate e ad uso esclusivo del destinatario.
Qualora il messaggio in parola Le fosse pervenuto per errore, La invitiamo ad eliminarlo senza copiarlo e a non inoltrarlo a terzi, dandocene gentilmente comunicazione.
Per qualsiasi informazione si prega di contattare info@trilogik.it<mailto:info@trilogik.it>. Grazie

**Comment by nicolaiarocci** [comment]
Strano che consentano più di due decimali nel `PrezzoTotale`. In ogni caso ora dovrebbe essere sistemato, grazie.

**Comment by gptucci** [comment]
Grazie e complimenti per il progetto
