### ISSUE TITLE
Errore in ContoMaggiorazione

### ISSUE THREAD

**Issue by gptucci** [FatturaElettronica/FatturaElettronica.NET#46]
Ciao
complimenti per il fantastico lavoro
Stanno arrivando svariate fatture che hanno il seguente campo scontomaggiornazione
.....
```
<FatturaElettronicaBody>
		<DatiGenerali>
			<DatiGeneraliDocumento>
				<TipoDocumento>TD01</TipoDocumento>
				<Divisa>EUR</Divisa>
				<Data>2017-04-30</Data>
				<Numero>XXXXX</Numero>
				<ScontoMaggiorazione>
					<Tipo>SC</Tipo>
				</ScontoMaggiorazione>
```
.....
Ottengo un errore Percentuale e Importo non presenti a fronte di Tipo valorizzato
Però guardando il tracciato è corretto, infatti sia i campi Percentuale che importo, che dovrebbero essere presenti nello stesso nodo ScontoMaggiorazione, in realtà sono marcati come <0.1> e quindi facoltativi.
Anche se è insensato il tracciato è corretto.
Grazie

**Comment by nicolaiarocci** [comment]
Tuttavia se leggi il formato tabellare vedrai la nota in 2.1.1.8.1 <Tipo>:

> Se valorizzato, viene controllato che esista almeno uno dei due elementi 2.1.1.8.2 <Percentuale> e 2.1.1.8.3 <Importo>

L'errore che dovrebbe essere riportato in questo caso (come puoi vedere dal tebellare):

> 00437: 2.1.1.8.2 <Percentuale> e 2.1.1.8.3 <Importo> non presenti a fronte di 2.1.1.8.1 <Tipo> valorizzato

Quindi direi che al momento la convalida è corretta.
