### ISSUE TITLE
Errore in caso di presenza di commenti all'interno dell'XML

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.NET#47]
Ciao, innanzitutto ottimo lavoro.
Volevo segnalare che in caso di caricamento di di fatture contenenti nel codice xml dei commenti il metodo ReadXml() genera un eccezione.
Il problema si risolve andando ad eliminare preventivamente i commenti aggiungendo il paramentro "IgnoreComments =  true" negli XmlReaderSettings.

Sarebbe utile gestire la situazione internamente, oppure aggiornare i tutorial modificando la riga

using (var r = XmlReader.Create(BkpFilePath, new XmlReaderSettings { IgnoreWhitespace = true}))

in 

using (var r = XmlReader.Create(BkpFilePath, new XmlReaderSettings { IgnoreWhitespace = true, IgnoreComments =  true}))

Grazie mille, ciao

**Comment by nicolaiarocci** [comment]
Grazie per la segnalazione. Per ora ho aggiornato il README. In futuro, se e quando riusciremo a integrare #39, allora verrà gestito direttamente.
