### ISSUE TITLE
New logo for FatturaElettronica

### ISSUE THREAD

**Issue by reallinfo** [FatturaElettronica/FatturaElettronica.NET#50]
I wanted to contribute to FatturaElettronica and I designed a logo for FatturaElettronica. If you like it, you can use it.
![fattura](https://user-images.githubusercontent.com/36298335/37846228-abf40436-2ed5-11e8-80cb-49f2bd50b60d.png)
![fattura2](https://user-images.githubusercontent.com/36298335/37846229-ac1c6534-2ed5-11e8-91c2-9442b98adf9c.jpg)

**Comment by nicolaiarocci** [comment]
See my comment on #51
