### ISSUE TITLE
Nuove Rettifiche nel Controllo

### ISSUE THREAD

**Issue by brux88** [FatturaElettronica/FatturaElettronica.NET#52]
ciao, complimenti per il lavoro fatto , è stato utilissimo.
stavo verificando che se non sbaglio adesso l'agenzia dell'entrate ha specificato che  è possibile mettere codice destinatario 000000 e omettere l'email, invece la convalida del file mi dice che al fronte del codice destinatario 0000000 ci deve essere la pec valorizzata. vi risulta? in caso affermativo è possibile sistemare il validatore?

**Comment by nicolaiarocci** [comment]
Ciao, puoi darmi un link a cui viene spiegata questa modifica. Ho controllato sulle specifiche tecniche e mi pare tutto invariato (vedi immagine)
![screen shot 2018-06-07 at 15 37 08](https://user-images.githubusercontent.com/512968/41103137-b4211b2a-6a68-11e8-8fc2-196d08996db6.png)

**Comment by brux88** [comment]
ho allegato lo screenshot dove viene descritto il caso in cui non ho la pec e devo inserire 000000, ho allegato anche l'intera circolare del 30/04/02018

![2018-06-07_1744](https://user-images.githubusercontent.com/3495339/41110794-8973631c-6a7a-11e8-8caf-6658029322a4.png)
[_89757 _DEL_30_04_18_Provvedimento_30042018+.pdf](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/2081130/_89757._DEL_30_04_18_Provvedimento_30042018.pdf)

**Comment by nicolaiarocci** [comment]
Sì la circolare menziona questa novità, ma ad un controllo effettivo non risulta ancora operativa:

- le specifiche non sono state aggiornate;
- se mandi una fattura al sistema SDI viene respinta (vedi img)

Per ora lasciamo questo ticket in stand-by. Quando le specifiche tecniche recepiranno la circolare, fammelo sapere per cortesia che aggiorniamo la libreria.

![screenhunter_700 jun 08 09 47](https://user-images.githubusercontent.com/512968/41145764-691c1b4a-6b01-11e8-8c71-c36d3665129d.jpg)

**Comment by brux88** [comment]
si certo infatti avevo notato che ancora i controlli non sono stati aggiornati, vedremo appena rilasceranno qualche aggiornamento, ancora complimenti per questa libreria ;)

**Comment by tanogae** [comment]
Ciao, mi aggrego ai complimenti per il lavoro svolto.
Volevo sottolineare che le modifiche introdotte dalla circolare 8/E e relative specifiche tecniche del 30 Aprile saranno effettive dal 01 Luglio.

**Comment by nicolaiarocci** [comment]
Ad un esame del nuovo tracciato mi pare che le modifiche significative siano:
- Nuovo valore TD20 (autofattura) per tabella TipoDocumento
- Rimozione dei controlli sul contenuto del campo PECDestinatario

**Comment by brux88** [comment]
si esatto, ma gia sono stati aggiornati i controlli sul sito oppure dal 01/07/2018 verranno aggiornati?

**Comment by nicolaiarocci** [comment]
Non sono stati aggiornati e non ci sono notizie in proposito.

**Comment by nicolaiarocci** [comment]
Ho aggiornato la `master` branch, pronta per il rilascio quando (e se) questi controlli diverranno effettivi lato PA.

**Comment by tanogae** [comment]
Ecco quanto riporta il sito delle fatturazione elettronica verso la PA:

> Gentile contribuente,
a partire dalle ore 19 del giorno 29 giugno 2018 il Sistema di Interscambio non sarà disponibile e non sarà possibile l’invio di fatture elettroniche.
L'indisponibilità si rende necessaria per adeguare il sistema alle novità introdotte dalla Legge 205/2017 e regolamentate con Provvedimento AE 30 aprile 2018 in materia di fatturazione elettronica via SdI verso privati.
Il sistema sarà nuovamente disponibile dal primo luglio 2018. Ci scusiamo per gli eventuali disagi che tale interruzione dovesse comportare.

Di conseguenza le modifiche in oggetto saranno disponibili dal 01 luglio.

**Comment by nicolaiarocci** [comment]
FatturaElettronica v0.8 è disponibile sul feed nuget.org
