### ISSUE TITLE
nuovo allegato A ver. 1.1 del 5 giugno

### ISSUE THREAD

**Issue by Dex166** [FatturaElettronica/FatturaElettronica.NET#56]
ciao,
hai visto il nuovo allegato A ?
con le nuove specifiche soprattutto x le fatture verso estero..

[Allegato+A+-+Specifiche+tecniche+vers+1.1.pdf](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/2105021/Allegato.A.-.Specifiche.tecniche.vers.1.1.pdf)

**Comment by nicolaiarocci** [comment]
Duplicato di #52
