### ISSUE TITLE
errore lunghezza PEC destinatario in v. 0.8

### ISSUE THREAD

**Issue by Dex166** [FatturaElettronica/FatturaElettronica.NET#58]
ciao, ho aggiornato alla 0.8 e in validazione mi da errore sulla lunghezza della pec quando il campo pec  è vuoto con codice destinatario 0000000.

**Comment by nicolaiarocci** [comment]
PECDestinatario è null oppure stringa vuota? Se è null non dovrebbe dare errore. Se è stringa vuota subentra il controllo della lunghezza tra 7 e 256 caratteri.

**Comment by Dex166** [comment]
infatti stringa vuota...

**Comment by nicolaiarocci** [comment]
ok allora direi che va bene così

**Comment by nicolaiarocci** [comment]
e invece no, proviamo a gestire anche la stringa vuota
