### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by Artusoft** [FatturaElettronica/FatturaElettronica.NET#59]
Buongiorno, sarebbe possibile avere una versione su nuget firmata con uno strong name?

**Comment by nicolaiarocci** [comment]
Purtroppo in un progetto open source gestire lo strong naming è una specie di incubo, si veda per esempio https://stackoverflow.com/questions/11656520/signing-binaries-of-open-source-projects

Per questo motivo al momento non riteniamo di rilasciare una versione open source strong-named.

**Comment by nicolaiarocci** [comment]
Potrei essere stato troppo precipitoso: ci sono molti progetti FOSS che rilasciano le chiavi (vedi anche Jon Skeet qui: https://stackoverflow.com/questions/396143/net-opensource-projects-and-strong-named-assemblies).

Riapro e ci penso su con calma.

**Comment by Artusoft** [comment]
Ciao, grazie per la risposta. In realtà a me basterebbe solo che il progetto pubblicato in NuGet fosse firmato. La chiave potresti anche non pubblicarla su GitHub.
Comunque per ora ho clonato il progetto e ricompilato con una chiave mia per poterla aggiungere al mio progetto. 
Grazie mille e complimenti per il lavoro.

**Comment by nicolaiarocci** [comment]
Ottimo, consideriamola risolta allora.
