### ISSUE TITLE
Filename

### ISSUE THREAD

**Issue by andreatosato** [FatturaElettronica/FatturaElettronica.NET#60]
Ciao @nicolaiarocci, non è previsto nessun metodo per la generazione "automatica" del filename.
Come da [documentazione](http://www.fatturapa.gov.it/export/fatturazione/it/c-11.htm), l'unica cosa che non è presente tra i dati del tracciato è l'identificativo univoco.
Pensi che sia corretto aggiungere un metodo alla classe fattura con la gestione del nome del file?
Come da [documentazione](http://www.fatturapa.gov.it/export/fatturazione/sdi/Specifiche_tecniche_SdI_v1.2.pdf) (pagina 8), il progressivo univoco del file è rappresentato da una stringa alfanumerica di
lunghezza massima di 5 caratteri e con valori ammessi **[a-z], [A-Z], [0-9]**.

Penserei a una cosa simile:
```csharp
string fileName = Fattura.GetNextFilename(long lastNumber);
```
Cosa ne pensi?

**Comment by nicolaiarocci** [comment]
Andrea ho visto la PR quando l'hai aggiornata. Prometto di guardarci verso fine Agosto 😄

**Comment by andreatosato** [comment]
Ho rivisto il codice perché lo avevo fatto di fretta. 😅
Ora è completo 😊.
Grazie per il lavoro svolto
