### ISSUE TITLE
Errore utilizzando il codice destinatario 'XXXXXXX' per trasmettere le fatture estere

### ISSUE THREAD

**Issue by Cacobil** [FatturaElettronica/FatturaElettronica.NET#62]
Usando il codice destinatario 'XXXXXXX' richiede necessariamente il codice fiscale o la partita IVA che per un interlocutore extracee non ha evidentemente significato.
Dato che l'Agenzia delle Entrate ha ammesso questa modalità (ovviamente NON trasmette le fatture, le considera comunicate  a loro) è possibile in qualche modo disattivare le regole o devo agire da servizio che utilizza la libreria?
Scusa se ho sbagliato modalità.
Grazie

**Comment by andreatosato** [comment]
Ciao @Cacobil, non concordo con quanto segnalato.
Il controllo dell'agenzia delle entrate è il seguente:
```
Viene controllata la validità del codice che deve essere presente in IPA (se di 6 caratteri), oppure nell'anagrafica del Sistema di Interscambio (se di 7 caratteri e diverso da "0000000").
Se valorizzato a "0000000" viene controllato che sia valorizzato l'elemento informativo 1.1.6 <PECDestinatario>.
Quando è riferito ad una PA (6 caratteri) ed è valorizzato come ufficio 'centrale' (UF....) o come codice di default (999999), viene controllata l'esistenza delle condizioni che giustificano tale valorizzazione.
```
Il CodiceDestinatario non è strettamente legato al CodiceFiscale o PartitaIva. E' obbligatorio per tracciato quindi il codice mi sembra corretto.

Puoi controllare [qui](http://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.xls) il tracciato

**Comment by Cacobil** [comment]
Grazie mille per la risposta.

Quello a cui mi riferivo era generato da questo paragrafo dell'allegato A
Specifiche tecniche, pagina 32:
"PECDestinatario: indirizzo di Posta Elettronica Certificata al quale, se
valorizzato, viene recapitata la fattura nei casi in cui il valore di
CodiceDestinatario sia uguale a ‘0000000’ e non risulti registrato alcun
canale telematico associato alla partita IVA del cessionario/committente."
Io l'ho interpretato (forse erroneamente) come: se c'è un canale telematico
associato alla partita IVA del cessionario/committente non occorre indicare
la PECDestinatario.
Anche perché concorderebbe con quanto scritto sul sito Agenzia Entrate,
alla pagina
https://www.agenziaentrate.gov.it/wps/content/nsilib/nsi/agenzia/agenzia+comunica/comunicati+stampa/tutti+i+comunicati+del+2018/cs+aprile+2018/cs+30042018+provvedimento+e-fatture+con+app

" *Recapito “semplificato” per consumatori finali e piccole partite Iva* -
Se la fattura elettronica è destinata a un consumatore finale, un soggetto
Iva che rientra nei regimi agevolati di vantaggio o forfettario o
dell’agricoltura, l’emittente potrà valorizzare solo il campo “Codice
Destinatario” con un codice convenzionale e la fattura sarà recapitata al
destinatario attraverso la messa a disposizione del file in un’apposita
area web riservata dell’Agenzia delle Entrate. "

In ogni caso grazie per l'ottimo lavoro, prezioso per non dover partire da
zero!

Buona estate!


Il mer 8 ago 2018, 20:13 Andrea Tosato <notifications@github.com> ha
scritto:
