### ISSUE TITLE
DettaglioRigheValidators: Codice: 00423

### ISSUE THREAD

**Issue by marcotessitore** [FatturaElettronica/FatturaElettronica.NET#66]
Buongiorno, 
abbiamo una fattura che viene validata correttamente dall'SDI ma non dai validatori presenti qui.
All'interno delle specifiche tecniche Allegato A, è riportato per il calcolo del Prezzo Totale la dicitura: "è ammessa la tolleranza di ±1 centesimo di euro" 
Abbiamo esattamente questa differenza tra quanto calcolato e quanto presente in fattura.
Proporrei una modifica per prendere in considerazione anche questo scostamento e ritornare la riga valida se lo scostamento è di solo 1 centesimo sia in più, sia in meno.

Grazie e buona giornata,
Marco

**Comment by nicolaiarocci** [comment]
Grazie. La v0.8.3 sarà disponibile tra qualche minuto su nuget, con la tolleranza a 1 centesimo.
