### ISSUE TITLE
Dopo Bump FluentValidation dependency to v8.0.100 

### ISSUE THREAD

**Issue by flauteps** [FatturaElettronica/FatturaElettronica.NET#67]
Prima di tutto ottimo lavoro.
Dopo l'aggiornamento in oggetto quando si richiama il metodo
 var validator = new FatturaValidator();

Viene generato la seguente eccezione 
Ivar validator = new FatturaValidator();
Impossibile trovare il metodo 'FluentValidation.IRuleBuilderOptions`2<!0,!1> FluentValidation.IRuleBuilder`2.SetValidator(FluentValidation.IValidator`1<!1>)'.

In allegato l'eccezione nei dettagli
![immagine](https://user-images.githubusercontent.com/29484748/46422341-6c0fc600-c734-11e8-9a80-fd09de54c362.jpg)

**Comment by flauteps** [comment]
Come suggerito ho fatto il downgrade fino alla versione 7.1.1 passando per le varie versioni
Ho provato anche il downgrade di FatturaElettronica fino alla versione 0.7
Ma in entrambi i casi non va...

**Comment by nicolaiarocci** [comment]
Sì, la versione di FluentValidation da usare con FE 0.8.3 e precedenti è la 7.1.1. Un altro utente ha risolto così. Potresti postare il codice che usi per invocare la validazione?

**Comment by flauteps** [comment]
Da premettere che sto interfacciando il componente FatturaElettronica in una DLL con framework di destinazione .Net Standard ver 2

 public virtual bool Validate(string fileXML)
        {
            try
            {
                var fattura = Fattura.CreateInstance(Tipo);

                // Lettura da file XML compatibile con formato SDI 1.2.1.
                using (var r = XmlReader.Create(fileXML, new XmlReaderSettings { IgnoreWhitespace = true, IgnoreComments = true }))
                {
                    fattura.ReadXml(r);
                }
                var validator = new FatturaValidator(); // -----------> ERRORE <-----------
                var result = validator.Validate(fattura);

                if (!result.IsValid)
                {
                    Errori = result.Errors;
                    return false;
                }
                FECorrente = fattura;
                return true;
            }
            catch (Exception ex)
            {
                ErroriGenerici = ex;
                return false;
            }
        }

**Comment by nicolaiarocci** [comment]
Ho creato una nuova console app NetCore/NetStandard, ho installato FE 0.8.3 e ho potuto instanziare `FatturaValidator` senza errori. Poi ho fatto upgrade di FluentValidation da 7.1.1 a 8.0.100. Al lancio del programma di test ho ottenuto il tuo stesso errore:

![image](https://user-images.githubusercontent.com/512968/46460344-eafc1180-c7bb-11e8-86b1-e0ac47aa62ec.png)

Sono sceso di nuovo alla versione 7.1.1:
![image](https://user-images.githubusercontent.com/512968/46460459-51812f80-c7bc-11e8-8c4c-42b0d11966f0.png)

 e il programma ha ripreso a funzionare. Verifica che per qualche motivo (nuget cache?) tu non stia ancora usando la versione 8 di Fluent Validation nella tua applicazione. Devi avere qualcosa di simile:

![image](https://user-images.githubusercontent.com/512968/46460511-6eb5fe00-c7bc-11e8-8373-8dc49c26df39.png)

**Comment by nicolaiarocci** [comment]
Ad ogni buon conto ho pubblicato FatturaElettronica 0.8.4 su nuget, dovrebbe essere indicizzato e disponibile tra qualche minuto.

**Comment by flauteps** [comment]
Grazie e ancora complimenti per la qualità del codice
