### ISSUE TITLE
Aggiornamento ADE 3 ottobre 2018

### ISSUE THREAD

**Issue by andreatosato** [FatturaElettronica/FatturaElettronica.NET#68]
Ciao @nicolaiarocci, 
Ho visto che il 3 ottobre sono state aggiornate tutte le [specifiche tecniche](https://www.agenziaentrate.gov.it/wps/content/nsilib/nsi/schede/comunicazioni/fatture+e+corrispettivi/fatture+e+corrispettivi+st/st+invio+di+fatturazione+elettronica) della fattura elettronica.
E' prevista una roadmap per l'introduzione della fattura semplificata?
Grazie

**Comment by nicolaiarocci** [comment]
Sì è previsto di aggiungere anche il supporto per la semplificata, entro qualche mese al massimo.

**Comment by nicolaiarocci** [comment]
Chiudo per il momento, in ogni caso sarà creato un nuovo repository  in https://github.com/FatturaElettronica.
