### ISSUE TITLE
Inserimento specifiche AssoSoftware

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.NET#69]
Ciao,
Sarebbe molto utile prevedere la gestione dello standard AssoSoftware, che da quel che ho capito  estende il tracciato standard della PA con alcuni tag e codifiche.
Probabilmente in futuro potrebbero uscirne altre di estensioni alla PA tipo quella di AssoSoftware, quindi sarebbe utile gestire la cosa con l' implementazione di una nuova classe che, ereditando dallo standard PA, ne implementi le caratteristiche in ottica AssoSoftware.

[StandardAssosoftwareFE_CampiTracciato-103.xlsx](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/2456339/StandardAssosoftwareFE_CampiTracciato-103.xlsx)
[StandardAssosoftwareFE_Codifiche-103.xlsx](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/2456340/StandardAssosoftwareFE_Codifiche-103.xlsx)
[StandardAssosoftwareFE_Specifiche-103.docx](https://github.com/FatturaElettronica/FatturaElettronica.NET/files/2456341/StandardAssosoftwareFE_Specifiche-103.docx)

Grazie mille

**Comment by nicolaiarocci** [comment]
Ciao, grazie per il suggerimento ma al momento preferisco rimanere sullo standard ufficiale.
