### ISSUE TITLE
Problema su salvataggio MongoDB

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.NET#73]
Ciao, sto tentando di salvare un oggetto di tipo FatturaElettronica.Fattura su MongoDB, ma quando lancio la funzione di inserimento "InsertOne"
...
Fattura oFattura = Fattura.CreateInstance(Instance.Privati);
oFattura.ReadXml(oXmlReader);
IMongoCollection<Fattura> FatturaList = MongoDatabase.GetCollection<Fattura>("Test01");
FatturaList.InsertOne(oFattura);

Info oInfo = new Info() {NumeroFattura = "pippo",DataProtocollo = DateTime.Now.ToString("yyyyMMdd"), ID = 1};
IMongoCollection<Info> InfoList = MongoDatabase.GetCollection<Info>("Test01");
InfoList.InsertOne(oInfo);
...

Quando vado a verificare i dati inseriti però trovo che non è stato memorizzato nulla se non questo:

{
    "_id" : ObjectId("5bc4a080246b2f99268b911e"),
    "XmlOptions" : {
        "DateTimeFormat" : "yyyy-MM-dd",
        "DecimalFormat" : "0.00###",
        "SerializeNullValues" : false,
        "SerializeEmptyBusinessObjects" : false,
        "SerializeEmptyStrings" : false
    }
}

Andando a controllare invece i dati inseriti associati all'oggetto di tipo Info tutto sembra corretto

{
    "_id" : ObjectId("5bc4a080246b2f99268b9120"),
    "Esito" : null,
    "message" : null,
    "ID" : 1,
    "IDArchivium" : null,
    "NomeFileSDI" : null,
    "NumeroFattura" : "pippo",
    "DataFattura" : Date(-62135596800000),
    "TipoFattura" : null,
    "UltimaNotifica" : null,
    "NumeroProtocollo" : null,
    "DataProtocollo" : "20181015",
    "Notifiche" : []
}

è come se non fosse possibile accedere alle proprietà dell'oggetto Fattura.

Grazie mille, per l'aiuto

**Comment by nicolaiarocci** [comment]
Ciao, hai provato a salvare `Fattura.ToJson()`? Per quanto riguarda `XmlOptions` non dovrebbe venire serializzato, dal prossimo aggiornamento verrà escluso.

**Comment by nicolaiarocci** [comment]
PS il lavoro di miglioramento della serializzazione JSON è in corso sul repository Core, vedi https://github.com/FatturaElettronica/FatturaElettronica.Core/issues/2

**Comment by ardennext99** [comment]
Per ora ho risolto così, serializzando in jSon e deserializzando in BsonDocument:

  Fattura oFattura = Fattura.CreateInstance(Instance.Privati);
  oFattura.ReadXml(oXmlReader);
  BsonDocument oBsonDocument = BsonSerializer.Deserialize<BsonDocument>(oFattura.ToJson());
  IMongoCollection<BsonDocument> FatturaList = MongoDatabase.GetCollection<BsonDocument>("Test01");
  FatturaList.InsertOne(oBsonDocument);

e sembra che il dato memorizzato sia corretto.
