### ISSUE TITLE
PEC e verifica fattura

### ISSUE THREAD

**Issue by vbMizio** [FatturaElettronica/FatturaElettronica.NET#75]
Ho da pochi minuti scaricato l'aggiornamento v0.8.5. 
Nella verifica di una fattura, se il campo PEC del destinatario non è valorizzato, la fattura NON viene verificata, anche se nel campo fattura.Header.DatiTrasmissione.CodiceDestinatario viene indicato "0000000".

Come da specifiche 1.3, se non ho capito male, è possibile lasciare il campo "PEC" del destinatario vuoto, se viene indicato il codice "0000000". Ho comunque prodotto il file xml e, passandolo al sistema di verifica dell'agenzia delle entrate, il file viene indicato come conforme.

**Comment by nicolaiarocci** [comment]
Ciao, la 0.8.5 implementa questo controllo, comparso recentemente nelle specifiche tecniche (vedi #74):

![image](https://user-images.githubusercontent.com/512968/47163267-ec6a2580-d2f5-11e8-96f1-b4f313e17fc3.png)

[Questo] è il test (introdotto con la nuova versione) che si assicura che `PECDestinatario` sia valorizzato quando `CodiceDestinatario = "0000000"`.

**Comment by vbMizio** [comment]
Ciao, grazie della risposta.
Mi ero accorto della cosa, ma avendo sotto mano le specifiche 1.3, come da documento pdf scaricato dalla agenzia delle entrate all'indirizzo [https://www.google.it/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwiQhbqcoZDeAhXCDCwKHUu4C-4QFjAAegQIChAC&url=https%3A%2F%2Fwww.agenziaentrate.gov.it%2Fwps%2Fwcm%2Fconnect%2F804f90d4-e678-41b5-8d43-785d807df229%2FAllegato%2BA%2B-%2BSpecifiche%2Btecniche_30042018.pdf%3FMOD%3DAJPERES%26CACHEID%3D804f90d4-e678-41b5-8d43-785d807df229&usg=AOvVaw0xdJeweRaExT1-BguN0ahB](url)

dove alla pagina 7, capitolo 1, terzo paragrafo, c'è scritto che:
"l’eliminazione dell’obbligo di valorizzare l’elemento PECDestinatario, in corrispondenza del valore di default (“0000000”) per l’elemento CodiceDestinatario (v. paragrafo 1.5.5);"

lasciando quindi intendere che, specificando come codice destinatario "0000000", non è necessario inserire una PEC.

**Comment by sevenmay** [comment]
Scusate se intervengo.
Cito da qui: [Specifiche tecniche versione 1.3 (aggiornate al 10 ottobre 2018) - pdf](https://www.agenziaentrate.gov.it/wps/file/Nsilib/Nsi/Schede/Comunicazioni/Fatture+e+corrispettivi/Fatture+e+corrispettivi+ST/ST+invio+di+fatturazione+elettronica/ST+Fatturazione+elettronica+-+Allegato+A/Allegato+A+-+Specifiche+tecniche+vers+1.3.pdf)

Par. 2.1.1

> CodiceDestinatario: identifica il canale telematico sul quale
recapitare la fattura; deve contenere un valore alfanumerico di 7
caratteri corrispondente a:
>- uno dei codici che il Sistema di Interscambio attribuisce ai
soggetti, con canale accreditato in ricezione, che ne abbiano
fatto richiesta attraverso la funzione ‘Richiesta codici destinatario
B2B’ presente sul sito www.fatturapa.gov.it;
>- ‘0000000’, nei casi di fattura destinata ad un soggetto che riceve
tramite PEC e questa sia stata indicata nel campo
PECDestinatario;
30
>- **‘0000000’, nei casi di fattura destinata ad un soggetto per il quale
non si conosce il canale telematico (PEC o altro) sul quale
recapitare il file.**
>- XXXXXXX’, in caso di fattura emessa verso soggetti non
residenti, non stabiliti, non identificati in Italia, e inviata al
Sistema di Interscambio al fine di trasmettere i dati di cui al
paragrafo 3.

Inoltre nel par. 1.5.5

>se l’elemento informativo del file fattura CodiceDestinatario contiene
il valore “0000000” e l’elemento informativo PECDestinatario non è
valorizzato, il SdI mette a disposizione il file fattura nell’area
autenticata dei servizi telematici del cessionario/committente.

Quindi come si fa ad inviare una fattura fatta ad un privato senza codice e PEC?

Per quanto riguarda il controllo citato sul camp PECDestinatario, è presente nel file su http://fatturapa.gov.it:
 - [Rappresentazione tabellare del tracciato FatturaPA versione 1.2.1](http://fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.xls)

Ma non in quello su https://www.agenziaentrate.gov.it:
- [Rappresentazione tabellare del tracciato fattura ordinaria - xls](https://www.agenziaentrate.gov.it/wps/file/Nsilib/Nsi/Schede/Comunicazioni/Fatture+e+corrispettivi/Fatture+e+corrispettivi+ST/ST+invio+di+fatturazione+elettronica/ST+Fatturazione+elettronica+-+Rappresentazione+tabellare+del+tracciato+fattura+ordinaria/Rappresentazione+tabellare+del+tracciato+fattura+ordinaria.xls)

Qual'è quello corretto?

**Comment by nicolaiarocci** [comment]
Direi di usare il tool di verifica di Sdi/Sogei come riferimento, quind nel caso specifico probabilmente tocca intervenire

**Comment by sevenmay** [comment]
Se intendi questo: http://sdi.fatturapa.gov.it/SdI2FatturaPAWeb/AccediAlServizioAction.do?pagina=controlla_fattura

Ho provato con CodiceDestinatario="0000000" e PECDestinatario non valorizzata e passa il controllo.

**Comment by nicolaiarocci** [comment]
Sulla branch master c'è la probabile fix per questa questione. Se mi date feedback per favore (ideale sarebbe clonare, compilare e testare), così poi pubblichiamo su nuget se tutto torna. 

Su questo punto sono perplesso in quanto deroghiamo in parte dalla documentazione ufficiale (almeno dal tracciato).

**Comment by sevenmay** [comment]
Clonato, compilato e provato a generare la fattura. Tutto Ok.

Per quanto riguarda la documentazione qui sembra più aggiornata: https://www.agenziaentrate.gov.it/wps/content/nsilib/nsi/schede/comunicazioni/fatture+e+corrispettivi/fatture+e+corrispettivi+st/st+invio+di+fatturazione+elettronica

Se guardi "Rappresentazione tabellare del tracciato fattura ordinaria - xls" il controllo non c'è. Purtroppo non è indicata la versione.
