### ISSUE TITLE
Problema in fase di serializzazione automatica

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.NET#81]
Ciao,
Sto tentando di salvare le fatture elettroniche su MongoDB, mediante questa semplice funzione:

```
    public void insert(MongoClientSettings oMongoClientSettings, Fattura oFattura)
      {
      MongoClient oMongoClient = new MongoClient(oMongoClientSettings);
      IMongoDatabase MongoDatabase = oMongoClient.GetDatabase("InvoiceConveyor");
      IMongoCollection<Fattura> FatturaList = MongoDatabase.GetCollection<Fattura>("ActiveInvoicePackages");
      FatturaList.InsertOne(oFattura);
      }
```

quando vado a controllare i documenti inseriti su MongoDB mi trovo salvati anche tutti i tag "XmlOptions", che non essendo parte della tracciato Fatturaelettronica mi generano problemi nella successiva fase di reperimento e deserializzazione.

**Comment by nicolaiarocci** [comment]
Ciao, su che versione di FatturaElettronica.Core sei? La v0.4 ignora XmlOptions in serializzazione (la installi con FatturaElettronica v0.9)

**Comment by ardennext99** [comment]
Ciao,

sono con FatturaElettronica 0.9.0 e FatturaElettronica.Core 0.4.0

**Comment by ardennext99** [comment]
Sto continuando a fare delle prove.

 

FatturaList.InsertOne(oFattura); [KO – presenza XmlOption]

FatturaList.InsertOne(oFattura.ToBsonDocument());[KO – presenza XmlOption]

FatturaList.InsertOne(BsonSerializer.Deserialize<BsonDocument>(oFattura.ToJson()));[OK]

 

Serializzando l’istanza FatturaElettronica in Json (mediante il metodo ToJson), per poi deserializzarla in BsonDocument ed infine trasmetteela a MongoDB,

sembrerebbe che vengano esclusi il tag XmlOption, assieme a tutti i campi valorizzati a null.

 

Si verifica però un  problema in fase di deserializzazione leggendo da Mongo, e viene presentato questo stack ti errori:

 

public class Fattura_MDB:Fattura

  {

  [BsonId(IdGenerator = typeof(ObjectIdGenerator))]

  public ObjectId _id { get; set; }

  }

 

...

IMongoCollection<Fattura_MDB> FatturaList_Read = MongoDatabase.GetCollection<Fattura_MDB>("PassiveInvoicePackages_TestAsBsonDocumentFromJS");

List<Fattura_MDB> FatturaMDBList = await FatturaList_Read.Find(x => true).ToListAsync();

…

 

…

An error occurred while deserializing the Body property of class FatturaElettronica.Fattura: 

An error occurred while deserializing the DatiBeniServizi property of class FatturaElettronica.FatturaElettronicaBody.Body: 

An error occurred while deserializing the DettaglioLinee property of class FatturaElettronica.FatturaElettronicaBody.DatiBeniServizi.DatiBeniServizi: 

Element 'AltriDatiGestionali' does not match any field or property of class FatturaElettronica.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee."}

…

 

Sembrerebbe che la classe Fattura Elettronca non riconosca la proprietà “AltriDatiGestionali”, e quindi trovandoli nel sorgente da serializzare non sappia dove inserirli.

Confrontando i documenti salvati su MongoDB trasmettendo direttamente l’istanza FatturaElettronica (DocumentoKO.xml)

piuttosto che quelli salvati con BsonSerializer.Deserialize<BsonDocument>(oFattura.ToJson())(DocumentoOK.xml)

ho notato chenei primi due casi (quelli con l’XmlOption) non è presente nessun tag “AltriDatiGestionali”.

 

Nel caso potremmo sentirci vi Skype, in modo da poterti mostrare live cosa mi succede?

Il mio contatto è ArdenNext99 (Avatar con il simbolo degli Autobot).

 

Per ora grazie mille per l’aiuto, e per il tempo dedicato.

 

Ciao

**Comment by ardennext99** [comment]
Ciao, controllano il Codice su GitHub ho visto che il problema della deserializzazione leggendo da mongo

potrebbe essere il set;  mancante nella proprieta AltriDatiGestionali nel file “FatturaElettronicaBody/DatiBeniServizi/DettaglioLinee.cs”

 


[DataProperty]

	
public List<AltriDatiGestionali> AltriDatiGestionali { get; }

 

 

 

From: Arden Next '99 © [mailto:ardennext99@gmail.com] 
Sent: mercoledì 31 ottobre 2018 15:04
To: 'FatturaElettronica/FatturaElettronica.NET'
Subject: RE: [FatturaElettronica/FatturaElettronica.NET] Problema in fase di serializzazione automatica (#81)

 

Sto continuando a fare delle prove.

 

FatturaList.InsertOne(oFattura); [KO – presenza XmlOption]

FatturaList.InsertOne(oFattura.ToBsonDocument());[KO – presenza XmlOption]

FatturaList.InsertOne(BsonSerializer.Deserialize<BsonDocument>(oFattura.ToJson()));[OK]

 

Serializzando l’istanza FatturaElettronica in Json (mediante il metodo ToJson), per poi deserializzarla in BsonDocument ed infine trasmetteela a MongoDB,

sembrerebbe che vengano esclusi il tag XmlOption, assieme a tutti i campi valorizzati a null.

 

Si verifica però un  problema in fase di deserializzazione leggendo da Mongo, e viene presentato questo stack ti errori:

 

public class Fattura_MDB:Fattura

  {

  [BsonId(IdGenerator = typeof(ObjectIdGenerator))]

  public ObjectId _id { get; set; }

  }

 

...

IMongoCollection<Fattura_MDB> FatturaList_Read = MongoDatabase.GetCollection<Fattura_MDB>("PassiveInvoicePackages_TestAsBsonDocumentFromJS");

List<Fattura_MDB> FatturaMDBList = await FatturaList_Read.Find(x => true).ToListAsync();

…

 

…

An error occurred while deserializing the Body property of class FatturaElettronica.Fattura: 

An error occurred while deserializing the DatiBeniServizi property of class FatturaElettronica.FatturaElettronicaBody.Body: 

An error occurred while deserializing the DettaglioLinee property of class FatturaElettronica.FatturaElettronicaBody.DatiBeniServizi.DatiBeniServizi: 

Element 'AltriDatiGestionali' does not match any field or property of class FatturaElettronica.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee."}

…

 

Sembrerebbe che la classe Fattura Elettronca non riconosca la proprietà “AltriDatiGestionali”, e quindi trovandoli nel sorgente da serializzare non sappia dove inserirli.

Confrontando i documenti salvati su MongoDB trasmettendo direttamente l’istanza FatturaElettronica (DocumentoKO.xml)

piuttosto che quelli salvati con BsonSerializer.Deserialize<BsonDocument>(oFattura.ToJson())(DocumentoOK.xml)

ho notato chenei primi due casi (quelli con l’XmlOption) non è presente nessun tag “AltriDatiGestionali”.

 

Nel caso potremmo sentirci vi Skype, in modo da poterti mostrare live cosa mi succede?

Il mio contatto è ArdenNext99 (Avatar con il simbolo degli Autobot).

 

Per ora grazie mille per l’aiuto, e per il tempo dedicato.

 

Ciao

**Comment by nicolaiarocci** [comment]
Good catch. Temevo di essermene scordato qualcuno 😄

**Comment by ardennext99** [comment]
Non è che potresti pubblicarmi il fix della set, che sono un po bloccato e ho i capoccia col fiato sul collo?

Poi il problema della serializzazione dell’ XmlOption la guardi quando riesci, ma se riesco con la correzione della set ad andare avanti mi fai un grosso favore.

 

Grazie mille, ciao

**Comment by ardennext99** [comment]
Ciao,

Altra cosa che ho riscontrato è che pur essendoci i marcatori [XmlElement(ElementName = "FatturaElettronicaHeader")] e [XmlElement(ElementName = "FatturaElettronicaBody")]

quando si va a serializzare compare sempre “Header” e “Body”, in tutti i modi che si tenti di farlo.

Secondo me converrebbe cambiare proprio il nome della proprietà, anche se vorrebbe dire rivedere i namespace.

Fin che si serializza da FatturaElettronica e si deserializza su FatturaElettronica dovrebbe funzionare tutto,

ma se ad esempio bisogna ritrasmettere all’esterno l’xml serializzato per deserializzarlo con un componente di terze parti, questo non rispettando i tag del documento 1.2.1 non verrà deserializzato.

 

Ciao

**Comment by nicolaiarocci** [comment]
> Altra cosa che ho riscontrato è che pur essendoci i marcatori [XmlElement(ElementName = "FatturaElettronicaHeader")] e [XmlElement(ElementName = "FatturaElettronicaBody")] quando si va a serializzare compare sempre “Header” e “Body”, in tutti i modi che si tenti di farlo.

Passi da JSON? Perchè lì so che c'è il problema e la soluzione dovrebbe essere semplice. Per XML, se usi un deserializzatore XML di NET dovrebbe lavorare bene visti gli attributi.

**Comment by ardennext99** [comment]
Ciao, ho clonato su VS il branch ma quando tento di aprire la soluzione/progetto mi da errore di caricamento e non visualizzo nulla ne sul progetto "FatturaElettronica" ne su "FatturaElettronica.test". Io uso SV2015, potrebbe essere un problema?

**Comment by ardennext99** [comment]
Ok, alla fine ce l'ho fatta, ho ricreato da zero un progetto da VS2015, ho incluso nel progetto tutti i file del branch e ho lanciato il test. il problema della deserializzazione della proprietà AltriDatiGestionali pare risolto.
