### ISSUE TITLE
Problema in caso di serializzazione FatturaElettronicaHeader e FatturaElettronicaBody tramite MongoDB.Driver

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.NET#83]
Ciao,
Ho notato che salvando un istanza "Fattura" tramite MongoDB.Driver, questo viene serializzato utilizzando i nomi di classe originali "Header" e "Body", senza tener conto degli attributi già esistenti

```
[XmlElement(ElementName = "FatturaElettronicaHeader")]
[XmlElement(ElementName = "FatturaElettronicaBody")]
```

Questo capita perchè l'attributo "XmlElement" è utilizzato unicamente per la serializzazione XML, mentre  per far si che il nome delle proprietà vengano modificati dal serializzatore di MongoDB bisognerebbe inserire anche gli attributi:
```
[BsonElementAttribute("FatturaElettronicaHeader")]
[BsonElementAttribute("FatturaElettronicaBody")]
```
contenuti nel package "MongoDB.Bson.2.7.0"

In aggiunta, per fare in modo che ogni eventuale serializzazione esterna possa inserire i propri attributi a seconda delle necessita per rinominare le due proprietà, sarebbe utile aggiungere la parola chiave "virtual" alla definizione delle due proprietà

```
public virtual FatturaElettronicaHeader.Header Header { get; set; }
public virtual List<FatturaElettronicaBody.Body> Body { get; set; }
```

in modo da poter poi applicare gli attributi esternamente tramite override

```
public class FatturaMongoDB : Fattura
  {
  [DataProperty]
  [XmlElement(ElementName = "FatturaElettronicaBody")]
  [BsonElementAttribute("FatturaElettronicaHeader")]
  public override FatturaElettronica.FatturaElettronicaHeader.Header Header {  get { return base.Header; } set { base.Header = value;  }

  [DataProperty]
  [XmlElement(ElementName = "FatturaElettronicaBody")]
  [BsonElementAttribute("FatturaElettronicaBody")]
  public override List<FatturaElettronica.FatturaElettronicaBody.Body> Body {  get { return base.Body; } set { base.Body = value; }
  }
```

**Comment by nicolaiarocci** [comment]
Premesso che semplificare il nome di queste due proprietà è una scelta che rimpiango amaramente, rinomarle ora romperebbe molti progetti. Ho pubblicato una branch che dovrebbe risolvere il problema usando una terza via: il `JsonPropertyAttribute`. Testala, e fammi sapere se risolve.

**Comment by nicolaiarocci** [comment]
Ecco: https://github.com/FatturaElettronica/FatturaElettronica.NET/tree/serializzazione_body_e_header_%2383

**Comment by ardennext99** [comment]
Ciao, ho provato la soluzione del JsonProperty , in fase di scrittura ora vengono  correttamente riportati i campi “FatturaElettronicaHeader” e “FatturaElettronicaBody”, si genera pero un nuovo problema bloccante in fase di deserializzazione, che restituisce questo errore:

 

Element 'FatturaElettronicaHeader' does not match any field or property of class InvoiceConveyor_UT.InvoiceConveyorApiTest+Fattura_MDB.

 

Sembra che il deserializzatore non sappia dove andare a mappare il campo FatturaElettronicaHeader tirato su da MongoDB, perchè non ne trova la proprietà nella classe.

**Comment by ardennext99** [comment]
Una soluzione che ho testato e risolve questo problema è l'aggiunta di questo blocco,

```
[XmlIgnore]
[JsonIgnore]
public FatturaElettronicaHeader.Header FatturaElettronicaHeader {get { return Header; } set { Header = value; }}

[XmlIgnore]
[JsonIgnore]
public List<FatturaElettronicaBody.Body> FatturaElettronicaBody {get { return Body; } set { Body = value; }}
```

in questo modo si creano due proprietà con Nome corretto, che non fanno altro che esporre i valori esistenti Delle rispettive property Header e Body

**Comment by ardennext99** [comment]
o meglio ancora si leva l'esposizione in fase di serializzazione delle proprieta Header e Body, e si espongono solo quelle con nome corretto

```
[DataProperty]
[XmlIgnore]
[JsonIgnore]
public FatturaElettronicaHeader.Header Header { get; set; }

[DataProperty]
[XmlIgnore]
[JsonIgnore]
public List<FatturaElettronicaBody.Body> Body { get; set; }

public FatturaElettronicaHeader.Header FatturaElettronicaHeader {get { return Header; } set { Header = value; }}

public List<FatturaElettronicaBody.Body> FatturaElettronicaBody {get { return Body; } set { Body = value; }}
```

**Comment by nicolaiarocci** [comment]
Ho aggiornato branch col rename sia delle proprietà che le classi. Puoi verificare se in de/serializzazione ti torna tutto?

**Comment by ardennext99** [comment]
Ciao, ho verificato e funziona come un orologio svizzero. Come test ho lanciato un batch che importa su MongoDB e remporta su Fattura quasi 1000 fatture e nessuna ha dato errore. Direi che tutte le anomalie riscontrate siano risolte con questo branch

**Comment by ardennext99** [comment]
Ciao, sai per caso dirmi quando rilascerete la versione aggiornata su nuget? dovrei creare un nuovo progetto che referenzia il progetto che referenzia FatturaElettronica.net (che attualmente mi punta sul branch in locale), e se avete in previsione di pubblicare a breve mi evito di referenziare il progetto locale a cascata in tutti i progetti

**Comment by nicolaiarocci** [comment]
@ardennext99 ho fatto merge su master della branch, e l'ho cancellata. Alcune altre modifiche fatte nel frattempo su master (1 altro breaking change). Puoi confermarmi che tutto ok?

**Comment by ardennext99** [comment]
Ciao, ho rilanciato il task di salvataggio e reperimento su mongo delle 100 fatture e non ho riscontrato nessun problema nel branche master
