### ISSUE TITLE
Errore conformità iban

### ISSUE THREAD

**Issue by brux88** [FatturaElettronica/FatturaElettronica.NET#84]
ciao ho provato ad inviare una fattura elettronica, me lha generata senza errore ma se poi la vado a controllare nel sito dell agenzia dell'entrate mi da il seguwnte errore:
File non conforme al formato (nella descrizione del messaggio Ã¨ riportata lâ¬"indicazione puntuale della non conformitÃ ) - The value 'IT XX X XXXXX XXXXX 000XXXXXXXXX' of element 'IBAN' is not valid. riga: 100 - colonna: 54

non è implementato il controllo del codice iban , credo che siano gli spazi che l'agenzia non accetta

**Comment by nicolaiarocci** [comment]
Questo sembra un altro caso di controllo non dichiarato nelle specifiche tecniche (non ne trovo traccia nel formato tabellare). Sono dubbioso se rincorrere ognuna di queste verifica poichè non esiste una documentazione di riferimento.

**Comment by gminutillo** [comment]
è capitato anche a me, **sono sicuramente gli spazi**. 
nello schema dell'xml i caratteri ammessi nell'IBANType sono definito come espressione regolare:

```
<xs:simpleType name="IBANType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{11,30}"/>
  </xs:restriction>
</xs:simpleType>
```

**Comment by nicolaiarocci** [comment]
Ok ragazzi, grazie, mi avete convinto. Useremo la stessa regex in validazione

**Comment by donicom** [comment]
Salve,
in merito alla validazione dell'IBAN l'espressione regolare io l'ho sostituita con al seguente:
"^[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{11,30}$", in quanto nel mio caso, l'IBAN lo prendo da un campo di testo dove avevano inserito la stringa: "IBAN : {codice iban corretto}" che alla validazione risulta corretto perché contiene un IBAN corretto secondo l'espressione regolare vostra, ma la stringa in se è sbagliata quindi mi dava errore sul sito dell'agenzia. Per non incorrere in questo problema bisogna verificare che l'intera stringa sia solo formata da un codice IBAN.
