### ISSUE TITLE
Problema in fase di serializzazione e deserializzazione (proprietà CognomeNome)

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.NET#86]
Andando a serializzare e deserializzare un istanza di Fattura, in caso sia valorizzato uno dei campi Nome o Cognome, viene generato questo errore :

An error occurred while deserializing the Source property of class InvoiceConveyorApi.Pocos.InvoicePackage`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]: 
An error occurred while deserializing the FatturaElettronicaHeader property of class FatturaElettronica.Fattura: 
An error occurred while deserializing the CessionarioCommittente property of class FatturaElettronica.FatturaElettronicaHeader.Header: 
An error occurred while deserializing the DatiAnagrafici property of class FatturaElettronica.FatturaElettronicaHeader.CessionarioCommittente.CessionarioCommittente: 
An error occurred while deserializing the Anagrafica property of class FatturaElettronica.Common.DatiAnagrafici: 
Element 'CognomeNome' does not match any field or property of class FatturaElettronica.Common.Anagrafica.

Questo capita perchè in caso sia valorizzato Nome, Cognome, o entrambi viene serializzato anche il valore della proprietà "CognomeNome", che non fa parte del tracciato standard 1.2.1.

Il problema si dovrebbe risolvere andando ad aggiungere gli attributi "XmlIgnore" e "JsonIgnore"
nel file "Common/DenominazioneNomeCognome"

        [XmlIgnore]
        [JsonIgnore]
        public string CognomeNome
        {
            get
            {
                var r = ((Cognome ?? string.Empty) + " " + (Nome ?? string.Empty)).Trim();
                return string.IsNullOrEmpty(r) ? null : r;
            }
        }

**Comment by nicolaiarocci** [comment]
XML non dovrebbe venire impattato visto che non si tratta di una `DataProperty`. Ok per JSON.

**Comment by nicolaiarocci** [comment]
In realtà a ben guardare non dovrebbe nemmeno vernire serializzata con `ToJson`.

```c#
        [TestMethod]
        public void NomeCognomeIsIgnored()
        {
            var f = Fattura.CreateInstance(Instance.Privati);
            var anagrafica = f.Header.CedentePrestatore.DatiAnagrafici.Anagrafica;
            anagrafica.Nome = "nome";
            var json = f.Header.CedentePrestatore.DatiAnagrafici.Anagrafica.ToJson();

            Assert.AreEqual("nome", anagrafica.CognomeNome);
            Assert.IsFalse(json.Contains("NomeCognome"));
        }
```
