### ISSUE TITLE
Problema associato a "protected Fattura()"

### ISSUE THREAD

**Issue by ardennext99** [FatturaElettronica/FatturaElettronica.NET#99]
Ciao,
utilizzando la classe Fattura come tipo come riportato nell'esempio, il compilatore da errore perchè essendo il costruttore marchiato come protected non lo trova, e genera questo errore:

`'Fattura' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'ResultWithData<T>'
`
```
public class ResultWithData<T> : ResultInfo
where T:new()
  {
  public T DataObject { get; set; }
  public ResultWithData() { DataObject = new T(); }
  }

public async Task<StandardResponse.ResultWithData<Fattura>> GetActiveAccountingPreviewSource(Int32 ActiveAccountingPreviewID)
```

L'inserimento dell' attributo protected ha una finalità specifica o si può eliminare, rendendo pubblico il costruttore? La soluzione per quanto mi riguarda è creare una nuova classe ResultWithData2 senza la clausola where, ma se si potesse togliere il protected sarebbe forse più corretto.

Grazie mille, ciao

**Comment by nicolaiarocci** [comment]
Mah il motivo era evitare che venissero create fatture sbagliate di default, ovvero senza il FormatoTrasmissione. Discutibile ovviamente, anche passando per la factory mancano un sacco di informazioni necessarie, ma perlomeno si è sulla strada giusta :-)

In linea di massima il costruttore potrebbe diventare pubblico, anche se è un po' un anti-pattern avere il costruttore pubblico e il factory method nella stessa classe.

**Comment by nicolaiarocci** [comment]
Opinioni?

**Comment by ardennext99** [comment]
Ciao,

Instanziare Fatture senza il formato trasmissione mica è un errore anzi è indispensabile.

Ad esempio io che devo usare la classe Fattura come contenitore per degli stream che mi arrivano dai conservatori, non so in anticipo se lo stream è da PA o B2B, e lo inizializzo cosi:

 

Fattura oFattura = Fattura.CreateInstance(new Instance());

 

Poi con la ReadXML gli carico dentro i dati, e solo dopo so se arriva da PA o B2B.

**Comment by nicolaiarocci** [comment]
In effetti facciamo qualcosa di simile pure noi quando importiamo documenti provenienti da Sdi.

**Comment by albx** [comment]
La discussione mi interessa. @nicolaiarocci potrebbe avere senso avere una factory ImportFromStream(Stream stream)? In questo modo dato lo stream di un xml esterno si potrebbe generare l'istanza già compilata di Fattura senza rendere pubblico il costruttore. Che ne pensi?

**Comment by ardennext99** [comment]
using (XmlReader oXmlReader = XmlReader.Create(f.Result, new XmlReaderSettings { IgnoreWhitespace = true, IgnoreComments = true }))

                {

                //Caricamento fattura

                //Fattura oFattura = Fattura.CreateInstance(Instance.Privati);

                Fattura oFattura = Fattura.CreateInstance(new Instance());

                oFattura.ReadXml(oXmlReader);

 

                //Preparazione dati da salvare (serializzazione automatica)

                InvoicePackage<TArchiverPackageID> oInvoicePackage = new InvoicePackage<TArchiverPackageID>()

                  {

                  IDSDI = oInvoice.IDSDI,

                  Archiver = oInvoice.Archiver,

                  ArchiverPackageID = oInvoice.ArchiverPackageID,

                  SDIFileName = oInvoice.SDIFileName,

                  Source = oFattura,

                  Managed = false,

                  DateTimeUpdate = DateTime.Now

                  };

 

                //Memorizzazione

                InvoicePackageList.Add(oInvoicePackage);

                }

 

Io attualmente lo faccio così, il ReaderXml va a sovrascrivere ciò che imposta il CreateIstance, quindi passando il parametro new Instance() bypasso lo switch interno al CreateInstance.

Personalmente esporrei i seguenti costruttori, sarebbero utili quando si utilizza Unity IOC, che instanzia gli oggetti chiamando le new, e non i metodi generici come CreateIntance.

 

public Fattura()

                {

                FatturaElettronicaHeader = new FatturaElettronicaHeader.FatturaElettronicaHeader();

                FatturaElettronicaBody = new List<FatturaElettronicaBody.FatturaElettronicaBody>();

                }

 

public Fattura(XmlReader r)

                {

                FatturaElettronicaHeader = new FatturaElettronicaHeader.FatturaElettronicaHeader();

                FatturaElettronicaBody = new List<FatturaElettronicaBody.FatturaElettronicaBody>();

  

  this.ReadXml(r);

                }

 

public Fattura(MemoryStream m)

                {

                FatturaElettronicaHeader = new FatturaElettronicaHeader.FatturaElettronicaHeader();

                FatturaElettronicaBody = new List<FatturaElettronicaBody.FatturaElettronicaBody>();

  

  this.ReadXml(m);

                }

 

 

Oltretutto se si utilizzano i singleton, e si generano automaticamente mediante una funzione tipo questa, si ha bisogno di un costruttore pubblico comune da lanciare, non è possibile specificare un metodo generico nella clausola where

 

namespace Common

  {

  public sealed class Singleton<TObject>

    where TObject : class, new()

    {

    private static TObject _instance;

    private static object syncRoot = new Object();

 

    private Singleton() { new TObject(); }

 

    public static TObject Instance

      {

      get

        {

        if (_instance == null)

          {

          lock (syncRoot)

            {

            if (_instance == null)

              _instance = new TObject();

            }

          }

 

        return _instance;

        }

      }

    }

  }

**Comment by nicolaiarocci** [comment]
@ardennext99 vai di pull request, la guardo volentieri.

**Comment by nicolaiarocci** [comment]
@albx su FatturaElettronica.Extensions c'è una PR per lettura da stream, anche se incompleta al momento: https://github.com/FatturaElettronica/FatturaElettronica.Extensions/pull/19

**Comment by nicolaiarocci** [comment]
@ardennext99 ho reso il costruttore pubblico lasciando `CreateInstance` come helper method per chi desidera usarlo (e per non rompere compatibilità). Date occhiata se la soluzione per voi è ok per favore.

**Comment by ardennext99** [comment]
Domani torno in ufficio e di un occhiata. Ciao

Il giorno mer 2 gen 2019, 15:41 Nicola Iarocci <notifications@github.com>
ha scritto:

**Comment by ardennext99** [comment]
Ciao, ho tirato giu l’ultima versione1.0.4.0  da nuget, e tentando di utilizzare il costruttore, mi continua a dire che è Protected

**Comment by nicolaiarocci** [comment]
non è ancora su nuget, solo sul repository.
